StylesPath = .github/vale
MinAlertLevel = suggestion
Vocab = Velociraptor

[formats]
jsx = md
go = md

## -----------------------------------------------------------------
## VELOCIRAPTOR REPO 
## -----------------------------------------------------------------

[**/{*[!.pb].go}]

# Will run all the rules in these style folders unless they are
# individually forbidden like the Vale ones below.
BasedOnStyles = Velociraptor

# Vale.Spelling is replaced by Velociraptor/Spelling_Dictionaries
# which we can customize.
Vale.Terms = NO
Vale.Avoid = NO


# ------------------------------------------------------------------

[gui/velociraptor/src/**/*.jsx]

# Will run all the rules in these style folders unless they are
# individually forbidden like the Vale ones below.
BasedOnStyles = Velociraptor

# Vale.Spelling is replaced by Velociraptor/Spelling_Dictionaries
# which we can customize.
Vale.Terms = NO
Vale.Avoid = NO


# # ------------------------------------------------------------------

[**/*.md]

# Will run all the rules in these style folders unless they are
# individually forbidden like the Vale ones below.
BasedOnStyles = Velociraptor

# Vale.Spelling is replaced by Velociraptor/Spelling_Dictionaries
# which we can customize.
Vale.Terms = NO
Vale.Avoid = NO


# ------------------------------------------------------------------

# Make a vql2.yaml copy and add a root key to it, or else Vale won't parse it.
[docs/references/vql2.yaml]

TokenIgnores = ({{.+}})
BlockIgnores = ({{.+}})

# This will run all the rules in these style folders unless they are
# individually forbidden like the Vale ones below.
BasedOnStyles = Velociraptor

View = vqlref

# Vale.Spelling is replaced by Velociraptor/Spelling_Dictionaries
# which we can customize.
Vale.Terms = NO
Vale.Avoid = NO

Test.DumpScopes = NO


# ------------------------------------------------------------------

[artifacts/definitions/**/*.{yml,yaml}]

TokenIgnores = ({{.+}})
BlockIgnores = ({{.+}})

# This will run all the rules in these style folders unless they are
# individually forbidden like the Vale ones below.
BasedOnStyles = Velociraptor

View = artifacts

SpecialCases.ThisArtifact = NO

# Vale.Spelling is replaced by Velociraptor/Spelling_Dictionaries
# which we can customize.
Vale.Terms = NO
Vale.Avoid = NO

Test.DumpScopes = NO

