---
blacklist:
  - GPL-2.0

whitelist:
  - Apache-2.0
  - BSD-2-Clause
  - BSD-2-Clause-Views
  - BSD-3-Clause
  - MIT
  - NewBSD
  - FreeBSD
  - ISC
  - MPL-2.0
  - LGPL-3.0

exceptions:
  # Really MIT
  - github.com/mattn/go-pointer
