checks = ["all",
         #  error strings should not be capitalized (ST1005)
         "-ST1005",
         # receiver name should be a reflection of its identity
         "-ST1006",

         # should not use underscores in Go names
         "-ST1003",
         # at least one file in a package should have a package comment
         "-ST1000",
         # the surrounding loop is unconditionally terminated
         "-SA4004",

         # Dont tell me how to write comments.
         # The documentation of an exported function should start with the function’s name
         "-ST1020",
         # The documentation of an exported type should start with type’s name
         "-ST1021",
         # comment on exported const .. should be of the form
         "-ST1022",

         # Poorly chosen name for error variable
         "-ST1012",

         # Using a deprecated function, variable, constant or field
         "-SA1019",
         ]