package functions

import (
	"context"

	"github.com/Velocidex/ordereddict"
	"www.velocidex.com/golang/velociraptor/json"
	"www.velocidex.com/golang/velociraptor/logging"
	"www.velocidex.com/golang/velociraptor/services"
	"www.velocidex.com/golang/velociraptor/utils"
	vql_subsystem "www.velocidex.com/golang/velociraptor/vql"
	"www.velocidex.com/golang/vfilter"
	"www.velocidex.com/golang/vfilter/arg_parser"
	"www.velocidex.com/golang/vfilter/types"
)

/*
An alert is a structured log message which is generated by VQL
specifically to be routed into the high priority alert queue on the
server. Alerts are time deduplicated for a long time as they are
meant to just direct attention to some actiivty instead of a running
log of what actually happened.
*/
type AlertFunctionArgs struct {
	AlertName string    `vfilter:"required,field=name,doc=Name of the alert."`
	DedupTime int64     `vfilter:"optional,field=dedup,doc=Suppress same message in this many seconds (default 7200 sec or 2 hours)."`
	Condition types.Any `vfilter:"options,field=condition,doc=If specified we ignore the alert unless the condition is true"`
}

type AlertFunction struct{}

func (self *AlertFunction) Call(ctx context.Context,
	scope vfilter.Scope,
	args *ordereddict.Dict) vfilter.Any {

	defer vql_subsystem.RegisterMonitor(ctx, "alert", args)()

	arg := &AlertFunctionArgs{}
	kwargs, err := arg_parser.ExtractKWArgsWithContext(ctx, scope, args, arg)
	if err != nil {
		scope.Log("ERROR:alert: %v", err)
		return &vfilter.Null{}
	}

	// If a condition is specified we ignore the alert unless the
	// condition is true
	if arg.Condition != nil &&
		!scope.Bool(vql_subsystem.Materialize(ctx, scope, arg.Condition)) {
		return &vfilter.Null{}
	}

	if arg.DedupTime == 0 {
		arg.DedupTime = 7200
	}

	// Build a structured alert message
	alert := services.AlertMessage{
		Timestamp: utils.GetTime().Now(),
		AlertName: arg.AlertName,
		EventData: kwargs,
	}

	serialized, err := json.Marshal(alert)
	if err != nil {
		scope.Log("alert: %v", err)
		return &vfilter.Null{}
	}

	// Deduplicate alerts based on the alert name. If the alert is to
	// be duduplicated, we send a log at the logging.INFO level in
	// order to preserve the information.

	// The intention here is that the deduplicated ALERT level message
	// be captured by the system and direct attention of the user to a
	// client and time range of interest, where the full details of
	// the alert be further examined.
	log_fuction := &LogFunction{}
	if log_fuction.ShouldMessageBeSuppressed(
		ctx, scope, arg.AlertName, arg.DedupTime) {
		return (&LogFunction{}).Call(ctx, scope, ordereddict.NewDict().
			Set("message", string(serialized)).
			Set("dedup", arg.DedupTime).
			Set("level", logging.INFO))
	}

	return (&LogFunction{}).Call(ctx, scope, ordereddict.NewDict().
		Set("message", string(serialized)).
		Set("dedup", arg.DedupTime).
		Set("level", logging.ALERT))
}

func (self AlertFunction) Info(scope vfilter.Scope, type_map *vfilter.TypeMap) *vfilter.FunctionInfo {
	return &vfilter.FunctionInfo{
		Name:         "alert",
		Doc:          "Generate an alert message.",
		ArgType:      type_map.AddType(scope, &AlertFunctionArgs{}),
		FreeFormArgs: true,
		Version:      2,
	}
}

func init() {
	vql_subsystem.RegisterFunction(&AlertFunction{})
}
