// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	proto3 "www.velocidex.com/golang/velociraptor/actions/proto"
	proto2 "www.velocidex.com/golang/velociraptor/artifacts/proto"
	proto1 "www.velocidex.com/golang/velociraptor/flows/proto"
	_ "www.velocidex.com/golang/velociraptor/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StartFlowResponse struct {
	FlowId               string   `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartFlowResponse) Reset()         { *m = StartFlowResponse{} }
func (m *StartFlowResponse) String() string { return proto.CompactTextString(m) }
func (*StartFlowResponse) ProtoMessage()    {}
func (*StartFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *StartFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartFlowResponse.Unmarshal(m, b)
}
func (m *StartFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartFlowResponse.Marshal(b, m, deterministic)
}
func (m *StartFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartFlowResponse.Merge(m, src)
}
func (m *StartFlowResponse) XXX_Size() int {
	return xxx_messageInfo_StartFlowResponse.Size(m)
}
func (m *StartFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartFlowResponse proto.InternalMessageInfo

func (m *StartFlowResponse) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

type Approval struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Approval) Reset()         { *m = Approval{} }
func (m *Approval) String() string { return proto.CompactTextString(m) }
func (*Approval) ProtoMessage()    {}
func (*Approval) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Approval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Approval.Unmarshal(m, b)
}
func (m *Approval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Approval.Marshal(b, m, deterministic)
}
func (m *Approval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Approval.Merge(m, src)
}
func (m *Approval) XXX_Size() int {
	return xxx_messageInfo_Approval.Size(m)
}
func (m *Approval) XXX_DiscardUnknown() {
	xxx_messageInfo_Approval.DiscardUnknown(m)
}

var xxx_messageInfo_Approval proto.InternalMessageInfo

func (m *Approval) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ApprovalList struct {
	Items                []*Approval `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ApprovalList) Reset()         { *m = ApprovalList{} }
func (m *ApprovalList) String() string { return proto.CompactTextString(m) }
func (*ApprovalList) ProtoMessage()    {}
func (*ApprovalList) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ApprovalList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApprovalList.Unmarshal(m, b)
}
func (m *ApprovalList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApprovalList.Marshal(b, m, deterministic)
}
func (m *ApprovalList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovalList.Merge(m, src)
}
func (m *ApprovalList) XXX_Size() int {
	return xxx_messageInfo_ApprovalList.Size(m)
}
func (m *ApprovalList) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovalList.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovalList proto.InternalMessageInfo

func (m *ApprovalList) GetItems() []*Approval {
	if m != nil {
		return m.Items
	}
	return nil
}

type VFSRefreshDirectoryRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	VfsPath              string   `protobuf:"bytes,2,opt,name=vfs_path,json=vfsPath,proto3" json:"vfs_path,omitempty"`
	Depth                uint64   `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VFSRefreshDirectoryRequest) Reset()         { *m = VFSRefreshDirectoryRequest{} }
func (m *VFSRefreshDirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*VFSRefreshDirectoryRequest) ProtoMessage()    {}
func (*VFSRefreshDirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *VFSRefreshDirectoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VFSRefreshDirectoryRequest.Unmarshal(m, b)
}
func (m *VFSRefreshDirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VFSRefreshDirectoryRequest.Marshal(b, m, deterministic)
}
func (m *VFSRefreshDirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VFSRefreshDirectoryRequest.Merge(m, src)
}
func (m *VFSRefreshDirectoryRequest) XXX_Size() int {
	return xxx_messageInfo_VFSRefreshDirectoryRequest.Size(m)
}
func (m *VFSRefreshDirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VFSRefreshDirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VFSRefreshDirectoryRequest proto.InternalMessageInfo

func (m *VFSRefreshDirectoryRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VFSRefreshDirectoryRequest) GetVfsPath() string {
	if m != nil {
		return m.VfsPath
	}
	return ""
}

func (m *VFSRefreshDirectoryRequest) GetDepth() uint64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

type VFSFileBuffer struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	VfsPath              string   `protobuf:"bytes,2,opt,name=vfs_path,json=vfsPath,proto3" json:"vfs_path,omitempty"`
	Offset               uint64   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length               uint32   `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Data                 []byte   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VFSFileBuffer) Reset()         { *m = VFSFileBuffer{} }
func (m *VFSFileBuffer) String() string { return proto.CompactTextString(m) }
func (*VFSFileBuffer) ProtoMessage()    {}
func (*VFSFileBuffer) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *VFSFileBuffer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VFSFileBuffer.Unmarshal(m, b)
}
func (m *VFSFileBuffer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VFSFileBuffer.Marshal(b, m, deterministic)
}
func (m *VFSFileBuffer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VFSFileBuffer.Merge(m, src)
}
func (m *VFSFileBuffer) XXX_Size() int {
	return xxx_messageInfo_VFSFileBuffer.Size(m)
}
func (m *VFSFileBuffer) XXX_DiscardUnknown() {
	xxx_messageInfo_VFSFileBuffer.DiscardUnknown(m)
}

var xxx_messageInfo_VFSFileBuffer proto.InternalMessageInfo

func (m *VFSFileBuffer) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VFSFileBuffer) GetVfsPath() string {
	if m != nil {
		return m.VfsPath
	}
	return ""
}

func (m *VFSFileBuffer) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *VFSFileBuffer) GetLength() uint32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *VFSFileBuffer) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type NotificationRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	NotifyAll            bool     `protobuf:"varint,2,opt,name=notify_all,json=notifyAll,proto3" json:"notify_all,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotificationRequest) Reset()         { *m = NotificationRequest{} }
func (m *NotificationRequest) String() string { return proto.CompactTextString(m) }
func (*NotificationRequest) ProtoMessage()    {}
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *NotificationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationRequest.Unmarshal(m, b)
}
func (m *NotificationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationRequest.Marshal(b, m, deterministic)
}
func (m *NotificationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationRequest.Merge(m, src)
}
func (m *NotificationRequest) XXX_Size() int {
	return xxx_messageInfo_NotificationRequest.Size(m)
}
func (m *NotificationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationRequest proto.InternalMessageInfo

func (m *NotificationRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *NotificationRequest) GetNotifyAll() bool {
	if m != nil {
		return m.NotifyAll
	}
	return false
}

func init() {
	proto.RegisterType((*StartFlowResponse)(nil), "proto.StartFlowResponse")
	proto.RegisterType((*Approval)(nil), "proto.Approval")
	proto.RegisterType((*ApprovalList)(nil), "proto.ApprovalList")
	proto.RegisterType((*VFSRefreshDirectoryRequest)(nil), "proto.VFSRefreshDirectoryRequest")
	proto.RegisterType((*VFSFileBuffer)(nil), "proto.VFSFileBuffer")
	proto.RegisterType((*NotificationRequest)(nil), "proto.NotificationRequest")
}

func init() {
	proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c)
}

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4f, 0x73, 0x1b, 0x49,
	0x15, 0xcf, 0x24, 0xb1, 0x63, 0xb7, 0xed, 0x28, 0x6e, 0x3b, 0xb6, 0x2c, 0x2b, 0x9b, 0xf1, 0xb0,
	0x59, 0xbb, 0x96, 0x20, 0xb1, 0x4b, 0x51, 0xb5, 0xb5, 0xc5, 0x45, 0xfe, 0x23, 0xaf, 0x8b, 0xc4,
	0xe5, 0x8c, 0x6c, 0x03, 0x81, 0x5d, 0x57, 0x7b, 0xd4, 0x23, 0x0d, 0x8c, 0xa7, 0x27, 0x33, 0x2d,
	0x69, 0x05, 0xc5, 0x81, 0xe5, 0xc2, 0x81, 0x1b, 0x27, 0xaa, 0xf8, 0x18, 0x7c, 0x04, 0xae, 0x9c,
	0xb8, 0x73, 0x00, 0x3e, 0x06, 0x07, 0xaa, 0xff, 0xcd, 0xf4, 0xfc, 0xb3, 0x8d, 0x2b, 0x7b, 0xb2,
	0xfa, 0xbd, 0xd7, 0xbf, 0xdf, 0x7b, 0xaf, 0x5f, 0xbf, 0xd7, 0x63, 0x30, 0x8f, 0x42, 0xaf, 0x15,
	0x46, 0x84, 0x12, 0x38, 0xc3, 0xff, 0x34, 0x3e, 0x40, 0x11, 0xf5, 0x5c, 0xe4, 0xd0, 0xb8, 0xcd,
	0x05, 0x6d, 0xb5, 0x16, 0x66, 0x8d, 0x0f, 0x5d, 0x9f, 0x4c, 0xf2, 0xba, 0x0b, 0x87, 0xf8, 0x3e,
	0x76, 0x28, 0x89, 0xa4, 0xd5, 0x53, 0xdd, 0x6a, 0xec, 0xc6, 0x52, 0xbc, 0x2a, 0x04, 0x31, 0xbe,
	0x42, 0x01, 0xf5, 0x1c, 0x29, 0x5d, 0x47, 0x0e, 0xf5, 0x48, 0x90, 0x98, 0xbf, 0xf3, 0xa5, 0xa2,
	0x39, 0x20, 0x64, 0xe0, 0xe3, 0x36, 0x0a, 0xbd, 0x36, 0x0a, 0x02, 0x42, 0x11, 0xb7, 0x93, 0xda,
	0x4d, 0xa9, 0xe5, 0xab, 0xcb, 0x91, 0xdb, 0xc6, 0x57, 0x21, 0x9d, 0x4a, 0x65, 0x2d, 0x09, 0x43,
	0x0a, 0x96, 0x1c, 0xdf, 0xc3, 0x41, 0xb2, 0x5c, 0x18, 0x8e, 0xb4, 0x05, 0xf7, 0x56, 0xed, 0x0c,
	0x08, 0xc5, 0x97, 0x84, 0xfc, 0x2a, 0xd1, 0x8e, 0x62, 0x1c, 0xa9, 0xc5, 0xbc, 0x13, 0x8f, 0xe5,
	0xcf, 0xc7, 0x7d, 0x32, 0x09, 0x7c, 0x82, 0xfa, 0x72, 0xbd, 0xec, 0x90, 0xab, 0xd0, 0xc7, 0x9a,
	0x8b, 0xd6, 0x4b, 0xb0, 0xdc, 0xa3, 0x28, 0xa2, 0x5d, 0x9f, 0x4c, 0x6c, 0x1c, 0x87, 0x24, 0x88,
	0x31, 0x5c, 0x07, 0x8f, 0x18, 0xdf, 0x85, 0xd7, 0xaf, 0x1b, 0xa6, 0xb1, 0x33, 0x6f, 0xcf, 0xb2,
	0xe5, 0x51, 0xdf, 0xb2, 0xc0, 0x5c, 0x27, 0x0c, 0x23, 0x32, 0x46, 0x3e, 0x5c, 0x03, 0xb3, 0x11,
	0x46, 0x31, 0x09, 0x94, 0x8d, 0x58, 0x59, 0x3f, 0x04, 0x8b, 0xca, 0xe6, 0x95, 0x17, 0x53, 0xf8,
	0x02, 0xcc, 0x78, 0x14, 0x5f, 0xc5, 0x75, 0xc3, 0x7c, 0xb0, 0xb3, 0xf0, 0x69, 0x4d, 0x10, 0xb7,
	0x94, 0x8d, 0x2d, 0xb4, 0xd6, 0x3f, 0x0d, 0xd0, 0x38, 0xef, 0xf6, 0x6c, 0xec, 0x46, 0x38, 0x1e,
	0xee, 0x7b, 0x11, 0x3f, 0xac, 0xa9, 0x8d, 0xdf, 0x8d, 0x70, 0x4c, 0xe1, 0x2e, 0x98, 0x17, 0xe9,
	0x49, 0x9c, 0xda, 0x7d, 0xf1, 0xaf, 0xff, 0xfe, 0xfb, 0x6f, 0xc6, 0x73, 0x30, 0x6b, 0xef, 0x77,
	0xcf, 0xec, 0x63, 0x08, 0x4f, 0x87, 0xd8, 0x14, 0x46, 0x26, 0x25, 0xa6, 0xef, 0xc5, 0xb4, 0x61,
	0xdc, 0xb7, 0xe7, 0x84, 0xe8, 0xa8, 0x0f, 0x77, 0xc1, 0xdc, 0xd8, 0x8d, 0x2f, 0x42, 0x44, 0x87,
	0xf5, 0xfb, 0x1c, 0x62, 0x9b, 0x43, 0x6c, 0xc1, 0xe7, 0x6c, 0xeb, 0x79, 0xb7, 0x67, 0x9e, 0x20,
	0x3a, 0x54, 0x9b, 0x4d, 0xd7, 0xf3, 0x71, 0x6c, 0x7a, 0x81, 0xd9, 0xb2, 0x1f, 0x8d, 0xdd, 0x98,
	0xe9, 0xe0, 0x67, 0x60, 0xa6, 0x8f, 0x43, 0x3a, 0xac, 0x3f, 0x30, 0x8d, 0x9d, 0x87, 0xbb, 0x16,
	0x07, 0x68, 0xc2, 0xc6, 0x3e, 0x13, 0x9a, 0xc4, 0x35, 0xfb, 0xca, 0x73, 0x33, 0x12, 0xa1, 0xd8,
	0x62, 0x83, 0xf5, 0x57, 0x03, 0x2c, 0x9d, 0x77, 0x7b, 0x5d, 0xcf, 0xc7, 0xbb, 0x23, 0xd7, 0xc5,
	0x11, 0xdc, 0x2c, 0xc4, 0xf4, 0x9e, 0x9d, 0x5d, 0x03, 0xb3, 0xc4, 0x75, 0x63, 0x4c, 0x85, 0xb7,
	0xb6, 0x5c, 0x31, 0xb9, 0x8f, 0x83, 0x01, 0x1d, 0xd6, 0x1f, 0x9a, 0xc6, 0xce, 0x92, 0x2d, 0x57,
	0x10, 0x82, 0x87, 0x7d, 0x44, 0x51, 0x7d, 0xc6, 0x34, 0x76, 0x16, 0x6d, 0xfe, 0xdb, 0x7a, 0x03,
	0x56, 0x8e, 0x09, 0xf5, 0x5c, 0xcf, 0xe1, 0xa5, 0xad, 0xce, 0xe3, 0x5a, 0xdf, 0x9f, 0x01, 0x10,
	0xb0, 0x3d, 0xd3, 0x0b, 0xe4, 0xfb, 0xdc, 0xfb, 0x39, 0x7b, 0x5e, 0x48, 0x3a, 0xbe, 0xff, 0xe9,
	0xdf, 0xb7, 0xc1, 0x83, 0xce, 0xc9, 0x11, 0xb4, 0x01, 0xd8, 0x8b, 0x30, 0xa2, 0xf8, 0x8b, 0x51,
	0x40, 0xe1, 0x82, 0x2c, 0x0c, 0xb6, 0x68, 0xd4, 0xe5, 0xa2, 0x50, 0x9b, 0xd6, 0xb3, 0x6f, 0xfe,
	0xf1, 0x9f, 0x3f, 0xdd, 0x5f, 0xb7, 0x20, 0xbf, 0x73, 0xe3, 0x4f, 0xda, 0x29, 0xc4, 0xe7, 0xc6,
	0xc7, 0xf0, 0x67, 0x60, 0x9e, 0x55, 0x1d, 0x5b, 0xc6, 0x70, 0x5d, 0xa2, 0x24, 0x12, 0xe9, 0x7d,
	0x02, 0xaf, 0x29, 0x24, 0xfc, 0x06, 0x87, 0x5f, 0x81, 0xcb, 0x0a, 0x3e, 0x45, 0xeb, 0x82, 0x47,
	0x87, 0x98, 0xff, 0x86, 0x4f, 0xe5, 0x7e, 0xb9, 0x56, 0xb0, 0x7a, 0x08, 0xd6, 0x3a, 0x47, 0x5a,
	0x86, 0x35, 0x85, 0xa4, 0x36, 0x9f, 0x00, 0xf0, 0x9a, 0xf4, 0x3d, 0x77, 0x5a, 0x0c, 0x7b, 0xad,
	0x25, 0x3a, 0x46, 0x4b, 0x75, 0x8c, 0xd6, 0x01, 0xeb, 0x18, 0xc5, 0xa0, 0x53, 0x00, 0x16, 0xf4,
	0x00, 0x3c, 0x4e, 0x3c, 0x89, 0x47, 0x3e, 0x8d, 0x61, 0x33, 0xef, 0x20, 0x17, 0x2b, 0x3f, 0xd7,
	0x53, 0xed, 0x29, 0xba, 0xf4, 0x71, 0x12, 0xfd, 0x07, 0x9c, 0xa7, 0x0e, 0xd7, 0x72, 0x3e, 0x2b,
	0xd8, 0x3e, 0x58, 0xe2, 0xc5, 0x30, 0xdd, 0x13, 0xad, 0x0a, 0x36, 0x24, 0x52, 0x49, 0x89, 0x54,
	0x06, 0xf3, 0x9c, 0x93, 0x6c, 0x58, 0xab, 0x8a, 0x44, 0x87, 0x64, 0xe1, 0x5c, 0x80, 0xc5, 0x57,
	0xe8, 0x12, 0xfb, 0x79, 0x12, 0x5d, 0xa8, 0x48, 0xa0, 0x6a, 0x27, 0x27, 0x47, 0x49, 0x14, 0x05,
	0x02, 0x7d, 0xa3, 0xc8, 0xd7, 0x02, 0x3b, 0x56, 0x85, 0xbf, 0xa9, 0x8a, 0x0d, 0xa3, 0xc8, 0x19,
	0xe6, 0x08, 0x9a, 0xe5, 0xca, 0x6c, 0x35, 0xc2, 0xa7, 0x8a, 0x2a, 0x63, 0x06, 0xbf, 0x04, 0xf3,
	0x87, 0x58, 0xf2, 0x40, 0x2d, 0xeb, 0x42, 0xa2, 0x28, 0x9e, 0x24, 0x2d, 0xd1, 0x13, 0x0a, 0xeb,
	0x05, 0x87, 0x7d, 0x0e, 0x9f, 0x69, 0xe7, 0x20, 0x54, 0xed, 0xdf, 0x24, 0xd7, 0xee, 0xb7, 0xf0,
	0xcf, 0x06, 0x3f, 0x78, 0xa1, 0x61, 0xb7, 0x24, 0x4e, 0x2a, 0xb3, 0x13, 0x7a, 0xe2, 0xda, 0xa8,
	0xb3, 0xc8, 0x89, 0xa5, 0xff, 0x3f, 0xe5, 0x44, 0x36, 0xb4, 0x0a, 0x44, 0x1c, 0x4e, 0x67, 0x7b,
	0xfb, 0x72, 0xf7, 0x63, 0xf0, 0xf0, 0x8b, 0x83, 0xce, 0xfe, 0x6d, 0xac, 0xe1, 0x97, 0xa0, 0x76,
	0x88, 0xe9, 0x59, 0x8c, 0xa3, 0xb3, 0xa3, 0xd3, 0x08, 0x79, 0x34, 0x86, 0x15, 0x05, 0xd1, 0x58,
	0x4e, 0x9d, 0x3b, 0x8c, 0x22, 0xb6, 0x45, 0x1d, 0x21, 0x5c, 0xd7, 0x98, 0x32, 0x58, 0x7f, 0x30,
	0xc0, 0xaa, 0x94, 0xe9, 0xb5, 0x17, 0x43, 0x2b, 0xcd, 0x72, 0x41, 0xa9, 0xb2, 0xf1, 0x9d, 0x6b,
	0x6d, 0x64, 0x6a, 0xb6, 0xb9, 0x0b, 0x5b, 0x56, 0x33, 0xe7, 0x42, 0xc6, 0x9a, 0x55, 0xd3, 0xaf,
	0x41, 0xbd, 0x44, 0xb5, 0x47, 0xd8, 0xed, 0xae, 0x0a, 0x59, 0x55, 0x55, 0xe9, 0x2e, 0x6b, 0x87,
	0x53, 0x5b, 0xd0, 0xbc, 0x86, 0x5a, 0xe0, 0x13, 0xf0, 0xe4, 0xbc, 0xdb, 0x63, 0xc5, 0x9c, 0x4c,
	0xcc, 0xa4, 0x04, 0xa4, 0x22, 0x5f, 0x02, 0x89, 0x58, 0xc6, 0xf9, 0x92, 0x93, 0x7d, 0x04, 0x3f,
	0x54, 0x64, 0x79, 0xc0, 0xcc, 0xb1, 0x7e, 0x63, 0x80, 0x95, 0x92, 0x31, 0x0d, 0xb7, 0x52, 0xf4,
	0x8a, 0x11, 0xde, 0x30, 0xd5, 0x31, 0xcb, 0x77, 0xcf, 0x9e, 0x7a, 0x91, 0x25, 0xae, 0x7c, 0xc4,
	0x5d, 0x31, 0xad, 0x4d, 0xcd, 0x95, 0x3c, 0x1a, 0xcb, 0xb8, 0xc3, 0xa3, 0xee, 0x51, 0x74, 0xf7,
	0xa8, 0x4d, 0x4e, 0xd5, 0x80, 0x75, 0x8d, 0x2a, 0x0b, 0x88, 0x40, 0x4d, 0xc9, 0xe4, 0x2b, 0xea,
	0x16, 0x1c, 0xca, 0xf4, 0x28, 0x70, 0x49, 0xb1, 0x88, 0xf3, 0x78, 0x3f, 0x02, 0x8b, 0xe7, 0xdd,
	0xde, 0x21, 0xa6, 0xf2, 0x41, 0xb0, 0x9a, 0x02, 0xa5, 0xcf, 0x84, 0x46, 0xa9, 0xd4, 0xba, 0x07,
	0xcf, 0xc0, 0x9c, 0x6a, 0xe0, 0x70, 0xad, 0xd0, 0xd1, 0x6f, 0xe8, 0xf4, 0x75, 0xee, 0x1b, 0x84,
	0x4f, 0xb4, 0x12, 0x13, 0x50, 0x23, 0x50, 0x93, 0x27, 0xa3, 0x0e, 0x2a, 0x99, 0x26, 0x85, 0x93,
	0xeb, 0x44, 0x83, 0xf8, 0x16, 0xe7, 0x6a, 0x71, 0xb2, 0xa6, 0x95, 0x24, 0x22, 0x47, 0xc0, 0xce,
	0xf4, 0x17, 0x00, 0xec, 0xa1, 0xc0, 0xc1, 0x3e, 0x6b, 0x25, 0x55, 0x6d, 0xec, 0xff, 0x79, 0x16,
	0x24, 0x60, 0x0c, 0xfd, 0x2b, 0xb0, 0xd0, 0x89, 0x9c, 0xa1, 0x37, 0xc6, 0x77, 0x83, 0x97, 0x83,
	0xd1, 0x5a, 0x51, 0xf0, 0x1a, 0x1a, 0xc3, 0xff, 0x39, 0x6f, 0xc4, 0x6c, 0xb5, 0x8f, 0x29, 0xf2,
	0xfc, 0xca, 0x46, 0xac, 0xe6, 0x95, 0x66, 0x5a, 0x3a, 0x75, 0x75, 0xa8, 0x01, 0x6f, 0xa5, 0x1a,
	0x4a, 0x25, 0x7a, 0xb3, 0x54, 0xac, 0x78, 0xca, 0x9a, 0x6a, 0x06, 0xf5, 0x14, 0x2c, 0xed, 0xe3,
	0xd8, 0x89, 0xbc, 0x4b, 0x7c, 0x3a, 0x0d, 0x71, 0x75, 0xc7, 0x5e, 0x94, 0x3c, 0xdc, 0xaa, 0x38,
	0x04, 0xb3, 0x20, 0xef, 0xc0, 0xd3, 0x43, 0x4c, 0x7f, 0x8c, 0xa7, 0x13, 0x12, 0xf5, 0xf7, 0xd2,
	0x2f, 0x90, 0x4a, 0xf4, 0x0d, 0x89, 0x5e, 0xdc, 0x52, 0x3a, 0x18, 0x4b, 0x90, 0xfb, 0x60, 0xf1,
	0x10, 0x27, 0xe5, 0x95, 0xbe, 0x20, 0x74, 0xa1, 0xca, 0x59, 0x23, 0x57, 0xbe, 0xc2, 0xf9, 0x90,
	0x92, 0x28, 0xb6, 0x9a, 0x9c, 0x6e, 0x0d, 0xae, 0x6a, 0x74, 0x29, 0xaa, 0xc7, 0xcf, 0x45, 0xad,
	0xd9, 0xdd, 0x84, 0x1b, 0x45, 0xa2, 0x3c, 0x4f, 0x46, 0x95, 0x7d, 0xb1, 0x64, 0x4e, 0x26, 0x83,
	0xdb, 0x07, 0xb5, 0x5e, 0x05, 0x55, 0xaf, 0x48, 0x55, 0xf6, 0x28, 0x2a, 0xdc, 0xc1, 0x1c, 0x9e,
	0xb8, 0x83, 0xec, 0xb9, 0x62, 0xe3, 0x90, 0x44, 0x99, 0xe7, 0x8a, 0x90, 0xe4, 0x6f, 0x89, 0xa6,
	0x90, 0x1c, 0x32, 0x5d, 0xd6, 0xb2, 0x16, 0x86, 0x30, 0x49, 0xe7, 0x64, 0x0f, 0x47, 0x63, 0x1c,
	0xbd, 0x26, 0x81, 0x47, 0x49, 0xe4, 0x05, 0x03, 0xd6, 0x10, 0xf1, 0x8d, 0x73, 0xb2, 0xb4, 0xf3,
	0x94, 0xce, 0xc9, 0x72, 0xfc, 0xdf, 0x1b, 0xa0, 0xde, 0xab, 0x52, 0x5e, 0xdf, 0xde, 0xae, 0x77,
	0xe1, 0xbb, 0xdc, 0x85, 0x17, 0x96, 0xa9, 0xa5, 0xb5, 0x94, 0x25, 0xcd, 0x80, 0x78, 0x31, 0x7d,
	0x7b, 0x19, 0x28, 0xc7, 0x97, 0x19, 0x28, 0x57, 0xbe, 0xef, 0x0c, 0x94, 0xb2, 0xb0, 0x0c, 0xfc,
	0xc5, 0x00, 0x1b, 0x6c, 0x74, 0x76, 0xc6, 0xc8, 0xf3, 0xd9, 0xb8, 0x39, 0x18, 0xe3, 0xf4, 0xf3,
	0x62, 0x5b, 0xfb, 0x2c, 0x2b, 0xb5, 0x50, 0x25, 0xb8, 0x73, 0xb3, 0x61, 0xf6, 0x75, 0x63, 0x6d,
	0xe9, 0xdf, 0x73, 0xa5, 0x5b, 0x98, 0x7b, 0x57, 0x00, 0x8a, 0xcf, 0x49, 0x35, 0xa2, 0xf9, 0x4d,
	0x53, 0xf1, 0x67, 0x55, 0x37, 0x7d, 0xe6, 0x6c, 0x71, 0xe6, 0x4d, 0x6b, 0x2d, 0xfb, 0xa1, 0xaa,
	0xb6, 0x33, 0xba, 0xb7, 0xbc, 0x4d, 0x1d, 0xab, 0xff, 0xe6, 0xe8, 0x5f, 0x53, 0x5c, 0xb2, 0x87,
	0x7d, 0x3f, 0xff, 0x91, 0x90, 0x58, 0x97, 0x36, 0xa7, 0x14, 0xeb, 0x2b, 0xb0, 0x70, 0x8c, 0x27,
	0x6a, 0x9d, 0xdc, 0x66, 0x25, 0x78, 0x8d, 0x29, 0x62, 0xdf, 0xf7, 0x95, 0xee, 0x17, 0x26, 0x9e,
	0x86, 0xc6, 0x7c, 0xc7, 0xe0, 0xf1, 0x59, 0xd8, 0x47, 0x14, 0xdf, 0x4c, 0x51, 0xa5, 0x28, 0xa6,
	0x28, 0x8b, 0xc8, 0x68, 0x7e, 0x09, 0x6a, 0x1a, 0x31, 0x4b, 0xc8, 0xb5, 0x59, 0xaa, 0xa4, 0x2a,
	0xb4, 0xbf, 0x1c, 0xaa, 0x78, 0x56, 0xd6, 0xb4, 0x14, 0xde, 0xc8, 0xb5, 0x52, 0xa2, 0x2b, 0xed,
	0xe4, 0x19, 0x44, 0x1f, 0xc0, 0x6c, 0x94, 0x77, 0xe3, 0x91, 0x83, 0xd0, 0x6a, 0x94, 0xa7, 0x4e,
	0x85, 0x44, 0x00, 0x14, 0x0f, 0xa1, 0x5b, 0xb3, 0x55, 0xd5, 0x43, 0x81, 0xb0, 0x88, 0xcb, 0x08,
	0x7f, 0x67, 0x80, 0x86, 0x28, 0x74, 0xa5, 0x29, 0xbd, 0x4a, 0x4a, 0x79, 0xf0, 0xb5, 0x3e, 0x59,
	0xaa, 0xb8, 0xbf, 0xc7, 0xb9, 0xb7, 0x2d, 0x2b, 0x7b, 0x95, 0xca, 0x18, 0x98, 0x0f, 0x7f, 0x34,
	0x40, 0xfd, 0x2c, 0x64, 0x12, 0x65, 0xd1, 0xa1, 0x14, 0x39, 0xc3, 0x2b, 0xf6, 0x15, 0x6e, 0xe6,
	0x3c, 0x60, 0x9b, 0x84, 0xb1, 0xf2, 0x62, 0xeb, 0x1a, 0x0b, 0xd9, 0x55, 0x0a, 0x3d, 0xaf, 0x8a,
	0x8e, 0xb9, 0xe3, 0x81, 0xc7, 0x22, 0xcc, 0xe4, 0xa6, 0xdc, 0x2d, 0x0b, 0x85, 0xdb, 0x92, 0x45,
	0x65, 0x54, 0x9f, 0x81, 0x99, 0x37, 0x23, 0x1c, 0x4d, 0x93, 0xbb, 0x78, 0xfe, 0xe6, 0x55, 0xb6,
	0x97, 0xc3, 0x54, 0x91, 0x44, 0x73, 0xef, 0xfb, 0x06, 0xfc, 0x1c, 0x80, 0x9f, 0x44, 0x1e, 0x15,
	0x1d, 0x11, 0x96, 0x58, 0x55, 0xba, 0x75, 0x6f, 0xf7, 0x93, 0xb7, 0xed, 0xc9, 0x64, 0xd2, 0x1a,
	0x63, 0x9f, 0x38, 0x5e, 0x1f, 0x7f, 0xdd, 0x72, 0xc8, 0x55, 0x7b, 0x40, 0x7c, 0x14, 0x0c, 0xda,
	0x42, 0x18, 0x21, 0xf6, 0x9e, 0xe2, 0x7e, 0x8b, 0xdd, 0xb3, 0xfc, 0xcf, 0x0f, 0xfe, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0xc4, 0xdb, 0xed, 0xde, 0x17, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	// Hunts
	CreateHunt(ctx context.Context, in *Hunt, opts ...grpc.CallOption) (*StartFlowResponse, error)
	ListHunts(ctx context.Context, in *ListHuntsRequest, opts ...grpc.CallOption) (*ListHuntsResponse, error)
	GetHunt(ctx context.Context, in *GetHuntRequest, opts ...grpc.CallOption) (*Hunt, error)
	ModifyHunt(ctx context.Context, in *Hunt, opts ...grpc.CallOption) (*empty.Empty, error)
	GetHuntResults(ctx context.Context, in *GetHuntResultsRequest, opts ...grpc.CallOption) (*GetTableResponse, error)
	// Clients.
	NotifyClients(ctx context.Context, in *NotificationRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	LabelClients(ctx context.Context, in *LabelClientsRequest, opts ...grpc.CallOption) (*APIResponse, error)
	ListClients(ctx context.Context, in *SearchClientsRequest, opts ...grpc.CallOption) (*SearchClientsResponse, error)
	GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*ApiClient, error)
	GetClientFlows(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowResponse, error)
	// Users
	GetUserUITraits(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ApiGrrUser, error)
	GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsResponse, error)
	GetUserNotificationCount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserNotificationCount, error)
	// VFS
	VFSListDirectory(ctx context.Context, in *proto1.VFSListRequest, opts ...grpc.CallOption) (*proto1.VFSListResponse, error)
	VFSRefreshDirectory(ctx context.Context, in *VFSRefreshDirectoryRequest, opts ...grpc.CallOption) (*proto1.ArtifactCollectorResponse, error)
	VFSStatDirectory(ctx context.Context, in *proto1.VFSListRequest, opts ...grpc.CallOption) (*proto1.VFSListResponse, error)
	VFSStatDownload(ctx context.Context, in *proto1.VFSListRequest, opts ...grpc.CallOption) (*proto1.VFSDownloadInfo, error)
	// This can be used by API clients to fetch file content.
	VFSGetBuffer(ctx context.Context, in *VFSFileBuffer, opts ...grpc.CallOption) (*VFSFileBuffer, error)
	GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*GetTableResponse, error)
	// Flows
	CollectArtifact(ctx context.Context, in *proto1.ArtifactCollectorArgs, opts ...grpc.CallOption) (*proto1.ArtifactCollectorResponse, error)
	CancelFlow(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*StartFlowResponse, error)
	ArchiveFlow(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*StartFlowResponse, error)
	GetFlowDetails(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*FlowDetails, error)
	GetFlowRequests(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowRequestDetails, error)
	DescribeTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*proto2.Types, error)
	GetKeywordCompletions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*KeywordCompletions, error)
	// Artifacts
	GetArtifacts(ctx context.Context, in *GetArtifactsRequest, opts ...grpc.CallOption) (*proto2.ArtifactDescriptors, error)
	GetArtifactFile(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*GetArtifactResponse, error)
	SetArtifactFile(ctx context.Context, in *SetArtifactRequest, opts ...grpc.CallOption) (*APIResponse, error)
	// Reporting and post processing.
	GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error)
	// Server Monitoring Artifacts - manage the Server Monitoring
	// Service..
	GetServerMonitoringState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*proto1.ArtifactCollectorArgs, error)
	// Server Monitoring Artifacts - manage the Server Monitoring
	// Service.
	SetServerMonitoringState(ctx context.Context, in *proto1.ArtifactCollectorArgs, opts ...grpc.CallOption) (*proto1.ArtifactCollectorArgs, error)
	// Client Monitoring Artifacts - manage the Client Monitoring
	// Service.
	GetClientMonitoringState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*proto1.ArtifactCollectorArgs, error)
	// Client Monitoring Artifacts - manage the Client Monitoring
	// Service.
	SetClientMonitoringState(ctx context.Context, in *proto1.ArtifactCollectorArgs, opts ...grpc.CallOption) (*proto1.ArtifactCollectorArgs, error)
	ListAvailableEventResults(ctx context.Context, in *ListAvailableEventResultsRequest, opts ...grpc.CallOption) (*ListAvailableEventResultsResponse, error)
	// Schedule downloads.
	CreateDownloadFile(ctx context.Context, in *CreateDownloadRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Notebook management
	GetNotebooks(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*Notebooks, error)
	NewNotebook(ctx context.Context, in *NotebookMetadata, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateNotebook(ctx context.Context, in *NotebookMetadata, opts ...grpc.CallOption) (*NotebookMetadata, error)
	NewNotebookCell(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*NotebookMetadata, error)
	GetNotebookCell(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*NotebookCell, error)
	UpdateNotebookCell(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*NotebookCell, error)
	CancelNotebookCell(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateNotebookDownloadFile(ctx context.Context, in *NotebookExportRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UploadNotebookAttachment(ctx context.Context, in *NotebookFileUploadRequest, opts ...grpc.CallOption) (*NotebookFileUploadResponse, error)
	ExportNotebook(ctx context.Context, in *NotebookExportRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Streaming free form VQL.
	Query(ctx context.Context, in *proto3.VQLCollectorArgs, opts ...grpc.CallOption) (API_QueryClient, error)
	// Push monitoring event to the server.
	WriteEvent(ctx context.Context, in *proto3.VQLResponse, opts ...grpc.CallOption) (*empty.Empty, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) CreateHunt(ctx context.Context, in *Hunt, opts ...grpc.CallOption) (*StartFlowResponse, error) {
	out := new(StartFlowResponse)
	err := c.cc.Invoke(ctx, "/proto.API/CreateHunt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListHunts(ctx context.Context, in *ListHuntsRequest, opts ...grpc.CallOption) (*ListHuntsResponse, error) {
	out := new(ListHuntsResponse)
	err := c.cc.Invoke(ctx, "/proto.API/ListHunts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetHunt(ctx context.Context, in *GetHuntRequest, opts ...grpc.CallOption) (*Hunt, error) {
	out := new(Hunt)
	err := c.cc.Invoke(ctx, "/proto.API/GetHunt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ModifyHunt(ctx context.Context, in *Hunt, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.API/ModifyHunt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetHuntResults(ctx context.Context, in *GetHuntResultsRequest, opts ...grpc.CallOption) (*GetTableResponse, error) {
	out := new(GetTableResponse)
	err := c.cc.Invoke(ctx, "/proto.API/GetHuntResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) NotifyClients(ctx context.Context, in *NotificationRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.API/NotifyClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) LabelClients(ctx context.Context, in *LabelClientsRequest, opts ...grpc.CallOption) (*APIResponse, error) {
	out := new(APIResponse)
	err := c.cc.Invoke(ctx, "/proto.API/LabelClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListClients(ctx context.Context, in *SearchClientsRequest, opts ...grpc.CallOption) (*SearchClientsResponse, error) {
	out := new(SearchClientsResponse)
	err := c.cc.Invoke(ctx, "/proto.API/ListClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*ApiClient, error) {
	out := new(ApiClient)
	err := c.cc.Invoke(ctx, "/proto.API/GetClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetClientFlows(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowResponse, error) {
	out := new(ApiFlowResponse)
	err := c.cc.Invoke(ctx, "/proto.API/GetClientFlows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetUserUITraits(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ApiGrrUser, error) {
	out := new(ApiGrrUser)
	err := c.cc.Invoke(ctx, "/proto.API/GetUserUITraits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetUserNotifications(ctx context.Context, in *GetUserNotificationsRequest, opts ...grpc.CallOption) (*GetUserNotificationsResponse, error) {
	out := new(GetUserNotificationsResponse)
	err := c.cc.Invoke(ctx, "/proto.API/GetUserNotifications", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetUserNotificationCount(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*UserNotificationCount, error) {
	out := new(UserNotificationCount)
	err := c.cc.Invoke(ctx, "/proto.API/GetUserNotificationCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) VFSListDirectory(ctx context.Context, in *proto1.VFSListRequest, opts ...grpc.CallOption) (*proto1.VFSListResponse, error) {
	out := new(proto1.VFSListResponse)
	err := c.cc.Invoke(ctx, "/proto.API/VFSListDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) VFSRefreshDirectory(ctx context.Context, in *VFSRefreshDirectoryRequest, opts ...grpc.CallOption) (*proto1.ArtifactCollectorResponse, error) {
	out := new(proto1.ArtifactCollectorResponse)
	err := c.cc.Invoke(ctx, "/proto.API/VFSRefreshDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) VFSStatDirectory(ctx context.Context, in *proto1.VFSListRequest, opts ...grpc.CallOption) (*proto1.VFSListResponse, error) {
	out := new(proto1.VFSListResponse)
	err := c.cc.Invoke(ctx, "/proto.API/VFSStatDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) VFSStatDownload(ctx context.Context, in *proto1.VFSListRequest, opts ...grpc.CallOption) (*proto1.VFSDownloadInfo, error) {
	out := new(proto1.VFSDownloadInfo)
	err := c.cc.Invoke(ctx, "/proto.API/VFSStatDownload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) VFSGetBuffer(ctx context.Context, in *VFSFileBuffer, opts ...grpc.CallOption) (*VFSFileBuffer, error) {
	out := new(VFSFileBuffer)
	err := c.cc.Invoke(ctx, "/proto.API/VFSGetBuffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetTable(ctx context.Context, in *GetTableRequest, opts ...grpc.CallOption) (*GetTableResponse, error) {
	out := new(GetTableResponse)
	err := c.cc.Invoke(ctx, "/proto.API/GetTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CollectArtifact(ctx context.Context, in *proto1.ArtifactCollectorArgs, opts ...grpc.CallOption) (*proto1.ArtifactCollectorResponse, error) {
	out := new(proto1.ArtifactCollectorResponse)
	err := c.cc.Invoke(ctx, "/proto.API/CollectArtifact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CancelFlow(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*StartFlowResponse, error) {
	out := new(StartFlowResponse)
	err := c.cc.Invoke(ctx, "/proto.API/CancelFlow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ArchiveFlow(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*StartFlowResponse, error) {
	out := new(StartFlowResponse)
	err := c.cc.Invoke(ctx, "/proto.API/ArchiveFlow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetFlowDetails(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*FlowDetails, error) {
	out := new(FlowDetails)
	err := c.cc.Invoke(ctx, "/proto.API/GetFlowDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetFlowRequests(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowRequestDetails, error) {
	out := new(ApiFlowRequestDetails)
	err := c.cc.Invoke(ctx, "/proto.API/GetFlowRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DescribeTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*proto2.Types, error) {
	out := new(proto2.Types)
	err := c.cc.Invoke(ctx, "/proto.API/DescribeTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetKeywordCompletions(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*KeywordCompletions, error) {
	out := new(KeywordCompletions)
	err := c.cc.Invoke(ctx, "/proto.API/GetKeywordCompletions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetArtifacts(ctx context.Context, in *GetArtifactsRequest, opts ...grpc.CallOption) (*proto2.ArtifactDescriptors, error) {
	out := new(proto2.ArtifactDescriptors)
	err := c.cc.Invoke(ctx, "/proto.API/GetArtifacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetArtifactFile(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*GetArtifactResponse, error) {
	out := new(GetArtifactResponse)
	err := c.cc.Invoke(ctx, "/proto.API/GetArtifactFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SetArtifactFile(ctx context.Context, in *SetArtifactRequest, opts ...grpc.CallOption) (*APIResponse, error) {
	out := new(APIResponse)
	err := c.cc.Invoke(ctx, "/proto.API/SetArtifactFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetReport(ctx context.Context, in *GetReportRequest, opts ...grpc.CallOption) (*GetReportResponse, error) {
	out := new(GetReportResponse)
	err := c.cc.Invoke(ctx, "/proto.API/GetReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetServerMonitoringState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*proto1.ArtifactCollectorArgs, error) {
	out := new(proto1.ArtifactCollectorArgs)
	err := c.cc.Invoke(ctx, "/proto.API/GetServerMonitoringState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SetServerMonitoringState(ctx context.Context, in *proto1.ArtifactCollectorArgs, opts ...grpc.CallOption) (*proto1.ArtifactCollectorArgs, error) {
	out := new(proto1.ArtifactCollectorArgs)
	err := c.cc.Invoke(ctx, "/proto.API/SetServerMonitoringState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetClientMonitoringState(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*proto1.ArtifactCollectorArgs, error) {
	out := new(proto1.ArtifactCollectorArgs)
	err := c.cc.Invoke(ctx, "/proto.API/GetClientMonitoringState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) SetClientMonitoringState(ctx context.Context, in *proto1.ArtifactCollectorArgs, opts ...grpc.CallOption) (*proto1.ArtifactCollectorArgs, error) {
	out := new(proto1.ArtifactCollectorArgs)
	err := c.cc.Invoke(ctx, "/proto.API/SetClientMonitoringState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListAvailableEventResults(ctx context.Context, in *ListAvailableEventResultsRequest, opts ...grpc.CallOption) (*ListAvailableEventResultsResponse, error) {
	out := new(ListAvailableEventResultsResponse)
	err := c.cc.Invoke(ctx, "/proto.API/ListAvailableEventResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateDownloadFile(ctx context.Context, in *CreateDownloadRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.API/CreateDownloadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetNotebooks(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*Notebooks, error) {
	out := new(Notebooks)
	err := c.cc.Invoke(ctx, "/proto.API/GetNotebooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) NewNotebook(ctx context.Context, in *NotebookMetadata, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.API/NewNotebook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateNotebook(ctx context.Context, in *NotebookMetadata, opts ...grpc.CallOption) (*NotebookMetadata, error) {
	out := new(NotebookMetadata)
	err := c.cc.Invoke(ctx, "/proto.API/UpdateNotebook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) NewNotebookCell(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*NotebookMetadata, error) {
	out := new(NotebookMetadata)
	err := c.cc.Invoke(ctx, "/proto.API/NewNotebookCell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetNotebookCell(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*NotebookCell, error) {
	out := new(NotebookCell)
	err := c.cc.Invoke(ctx, "/proto.API/GetNotebookCell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateNotebookCell(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*NotebookCell, error) {
	out := new(NotebookCell)
	err := c.cc.Invoke(ctx, "/proto.API/UpdateNotebookCell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CancelNotebookCell(ctx context.Context, in *NotebookCellRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.API/CancelNotebookCell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateNotebookDownloadFile(ctx context.Context, in *NotebookExportRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.API/CreateNotebookDownloadFile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UploadNotebookAttachment(ctx context.Context, in *NotebookFileUploadRequest, opts ...grpc.CallOption) (*NotebookFileUploadResponse, error) {
	out := new(NotebookFileUploadResponse)
	err := c.cc.Invoke(ctx, "/proto.API/UploadNotebookAttachment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ExportNotebook(ctx context.Context, in *NotebookExportRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.API/ExportNotebook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Query(ctx context.Context, in *proto3.VQLCollectorArgs, opts ...grpc.CallOption) (API_QueryClient, error) {
	stream, err := c.cc.NewStream(ctx, &_API_serviceDesc.Streams[0], "/proto.API/Query", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIQueryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_QueryClient interface {
	Recv() (*proto3.VQLResponse, error)
	grpc.ClientStream
}

type aPIQueryClient struct {
	grpc.ClientStream
}

func (x *aPIQueryClient) Recv() (*proto3.VQLResponse, error) {
	m := new(proto3.VQLResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIClient) WriteEvent(ctx context.Context, in *proto3.VQLResponse, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.API/WriteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	// Hunts
	CreateHunt(context.Context, *Hunt) (*StartFlowResponse, error)
	ListHunts(context.Context, *ListHuntsRequest) (*ListHuntsResponse, error)
	GetHunt(context.Context, *GetHuntRequest) (*Hunt, error)
	ModifyHunt(context.Context, *Hunt) (*empty.Empty, error)
	GetHuntResults(context.Context, *GetHuntResultsRequest) (*GetTableResponse, error)
	// Clients.
	NotifyClients(context.Context, *NotificationRequest) (*empty.Empty, error)
	LabelClients(context.Context, *LabelClientsRequest) (*APIResponse, error)
	ListClients(context.Context, *SearchClientsRequest) (*SearchClientsResponse, error)
	GetClient(context.Context, *GetClientRequest) (*ApiClient, error)
	GetClientFlows(context.Context, *ApiFlowRequest) (*ApiFlowResponse, error)
	// Users
	GetUserUITraits(context.Context, *empty.Empty) (*ApiGrrUser, error)
	GetUserNotifications(context.Context, *GetUserNotificationsRequest) (*GetUserNotificationsResponse, error)
	GetUserNotificationCount(context.Context, *empty.Empty) (*UserNotificationCount, error)
	// VFS
	VFSListDirectory(context.Context, *proto1.VFSListRequest) (*proto1.VFSListResponse, error)
	VFSRefreshDirectory(context.Context, *VFSRefreshDirectoryRequest) (*proto1.ArtifactCollectorResponse, error)
	VFSStatDirectory(context.Context, *proto1.VFSListRequest) (*proto1.VFSListResponse, error)
	VFSStatDownload(context.Context, *proto1.VFSListRequest) (*proto1.VFSDownloadInfo, error)
	// This can be used by API clients to fetch file content.
	VFSGetBuffer(context.Context, *VFSFileBuffer) (*VFSFileBuffer, error)
	GetTable(context.Context, *GetTableRequest) (*GetTableResponse, error)
	// Flows
	CollectArtifact(context.Context, *proto1.ArtifactCollectorArgs) (*proto1.ArtifactCollectorResponse, error)
	CancelFlow(context.Context, *ApiFlowRequest) (*StartFlowResponse, error)
	ArchiveFlow(context.Context, *ApiFlowRequest) (*StartFlowResponse, error)
	GetFlowDetails(context.Context, *ApiFlowRequest) (*FlowDetails, error)
	GetFlowRequests(context.Context, *ApiFlowRequest) (*ApiFlowRequestDetails, error)
	DescribeTypes(context.Context, *empty.Empty) (*proto2.Types, error)
	GetKeywordCompletions(context.Context, *empty.Empty) (*KeywordCompletions, error)
	// Artifacts
	GetArtifacts(context.Context, *GetArtifactsRequest) (*proto2.ArtifactDescriptors, error)
	GetArtifactFile(context.Context, *GetArtifactRequest) (*GetArtifactResponse, error)
	SetArtifactFile(context.Context, *SetArtifactRequest) (*APIResponse, error)
	// Reporting and post processing.
	GetReport(context.Context, *GetReportRequest) (*GetReportResponse, error)
	// Server Monitoring Artifacts - manage the Server Monitoring
	// Service..
	GetServerMonitoringState(context.Context, *empty.Empty) (*proto1.ArtifactCollectorArgs, error)
	// Server Monitoring Artifacts - manage the Server Monitoring
	// Service.
	SetServerMonitoringState(context.Context, *proto1.ArtifactCollectorArgs) (*proto1.ArtifactCollectorArgs, error)
	// Client Monitoring Artifacts - manage the Client Monitoring
	// Service.
	GetClientMonitoringState(context.Context, *empty.Empty) (*proto1.ArtifactCollectorArgs, error)
	// Client Monitoring Artifacts - manage the Client Monitoring
	// Service.
	SetClientMonitoringState(context.Context, *proto1.ArtifactCollectorArgs) (*proto1.ArtifactCollectorArgs, error)
	ListAvailableEventResults(context.Context, *ListAvailableEventResultsRequest) (*ListAvailableEventResultsResponse, error)
	// Schedule downloads.
	CreateDownloadFile(context.Context, *CreateDownloadRequest) (*empty.Empty, error)
	// Notebook management
	GetNotebooks(context.Context, *NotebookCellRequest) (*Notebooks, error)
	NewNotebook(context.Context, *NotebookMetadata) (*empty.Empty, error)
	UpdateNotebook(context.Context, *NotebookMetadata) (*NotebookMetadata, error)
	NewNotebookCell(context.Context, *NotebookCellRequest) (*NotebookMetadata, error)
	GetNotebookCell(context.Context, *NotebookCellRequest) (*NotebookCell, error)
	UpdateNotebookCell(context.Context, *NotebookCellRequest) (*NotebookCell, error)
	CancelNotebookCell(context.Context, *NotebookCellRequest) (*empty.Empty, error)
	CreateNotebookDownloadFile(context.Context, *NotebookExportRequest) (*empty.Empty, error)
	UploadNotebookAttachment(context.Context, *NotebookFileUploadRequest) (*NotebookFileUploadResponse, error)
	ExportNotebook(context.Context, *NotebookExportRequest) (*empty.Empty, error)
	// Streaming free form VQL.
	Query(*proto3.VQLCollectorArgs, API_QueryServer) error
	// Push monitoring event to the server.
	WriteEvent(context.Context, *proto3.VQLResponse) (*empty.Empty, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) CreateHunt(ctx context.Context, req *Hunt) (*StartFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHunt not implemented")
}
func (*UnimplementedAPIServer) ListHunts(ctx context.Context, req *ListHuntsRequest) (*ListHuntsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHunts not implemented")
}
func (*UnimplementedAPIServer) GetHunt(ctx context.Context, req *GetHuntRequest) (*Hunt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHunt not implemented")
}
func (*UnimplementedAPIServer) ModifyHunt(ctx context.Context, req *Hunt) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyHunt not implemented")
}
func (*UnimplementedAPIServer) GetHuntResults(ctx context.Context, req *GetHuntResultsRequest) (*GetTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHuntResults not implemented")
}
func (*UnimplementedAPIServer) NotifyClients(ctx context.Context, req *NotificationRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyClients not implemented")
}
func (*UnimplementedAPIServer) LabelClients(ctx context.Context, req *LabelClientsRequest) (*APIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LabelClients not implemented")
}
func (*UnimplementedAPIServer) ListClients(ctx context.Context, req *SearchClientsRequest) (*SearchClientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListClients not implemented")
}
func (*UnimplementedAPIServer) GetClient(ctx context.Context, req *GetClientRequest) (*ApiClient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClient not implemented")
}
func (*UnimplementedAPIServer) GetClientFlows(ctx context.Context, req *ApiFlowRequest) (*ApiFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientFlows not implemented")
}
func (*UnimplementedAPIServer) GetUserUITraits(ctx context.Context, req *empty.Empty) (*ApiGrrUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserUITraits not implemented")
}
func (*UnimplementedAPIServer) GetUserNotifications(ctx context.Context, req *GetUserNotificationsRequest) (*GetUserNotificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserNotifications not implemented")
}
func (*UnimplementedAPIServer) GetUserNotificationCount(ctx context.Context, req *empty.Empty) (*UserNotificationCount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserNotificationCount not implemented")
}
func (*UnimplementedAPIServer) VFSListDirectory(ctx context.Context, req *proto1.VFSListRequest) (*proto1.VFSListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VFSListDirectory not implemented")
}
func (*UnimplementedAPIServer) VFSRefreshDirectory(ctx context.Context, req *VFSRefreshDirectoryRequest) (*proto1.ArtifactCollectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VFSRefreshDirectory not implemented")
}
func (*UnimplementedAPIServer) VFSStatDirectory(ctx context.Context, req *proto1.VFSListRequest) (*proto1.VFSListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VFSStatDirectory not implemented")
}
func (*UnimplementedAPIServer) VFSStatDownload(ctx context.Context, req *proto1.VFSListRequest) (*proto1.VFSDownloadInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VFSStatDownload not implemented")
}
func (*UnimplementedAPIServer) VFSGetBuffer(ctx context.Context, req *VFSFileBuffer) (*VFSFileBuffer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VFSGetBuffer not implemented")
}
func (*UnimplementedAPIServer) GetTable(ctx context.Context, req *GetTableRequest) (*GetTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTable not implemented")
}
func (*UnimplementedAPIServer) CollectArtifact(ctx context.Context, req *proto1.ArtifactCollectorArgs) (*proto1.ArtifactCollectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectArtifact not implemented")
}
func (*UnimplementedAPIServer) CancelFlow(ctx context.Context, req *ApiFlowRequest) (*StartFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelFlow not implemented")
}
func (*UnimplementedAPIServer) ArchiveFlow(ctx context.Context, req *ApiFlowRequest) (*StartFlowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveFlow not implemented")
}
func (*UnimplementedAPIServer) GetFlowDetails(ctx context.Context, req *ApiFlowRequest) (*FlowDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlowDetails not implemented")
}
func (*UnimplementedAPIServer) GetFlowRequests(ctx context.Context, req *ApiFlowRequest) (*ApiFlowRequestDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFlowRequests not implemented")
}
func (*UnimplementedAPIServer) DescribeTypes(ctx context.Context, req *empty.Empty) (*proto2.Types, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeTypes not implemented")
}
func (*UnimplementedAPIServer) GetKeywordCompletions(ctx context.Context, req *empty.Empty) (*KeywordCompletions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeywordCompletions not implemented")
}
func (*UnimplementedAPIServer) GetArtifacts(ctx context.Context, req *GetArtifactsRequest) (*proto2.ArtifactDescriptors, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArtifacts not implemented")
}
func (*UnimplementedAPIServer) GetArtifactFile(ctx context.Context, req *GetArtifactRequest) (*GetArtifactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArtifactFile not implemented")
}
func (*UnimplementedAPIServer) SetArtifactFile(ctx context.Context, req *SetArtifactRequest) (*APIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetArtifactFile not implemented")
}
func (*UnimplementedAPIServer) GetReport(ctx context.Context, req *GetReportRequest) (*GetReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReport not implemented")
}
func (*UnimplementedAPIServer) GetServerMonitoringState(ctx context.Context, req *empty.Empty) (*proto1.ArtifactCollectorArgs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerMonitoringState not implemented")
}
func (*UnimplementedAPIServer) SetServerMonitoringState(ctx context.Context, req *proto1.ArtifactCollectorArgs) (*proto1.ArtifactCollectorArgs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetServerMonitoringState not implemented")
}
func (*UnimplementedAPIServer) GetClientMonitoringState(ctx context.Context, req *empty.Empty) (*proto1.ArtifactCollectorArgs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientMonitoringState not implemented")
}
func (*UnimplementedAPIServer) SetClientMonitoringState(ctx context.Context, req *proto1.ArtifactCollectorArgs) (*proto1.ArtifactCollectorArgs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetClientMonitoringState not implemented")
}
func (*UnimplementedAPIServer) ListAvailableEventResults(ctx context.Context, req *ListAvailableEventResultsRequest) (*ListAvailableEventResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableEventResults not implemented")
}
func (*UnimplementedAPIServer) CreateDownloadFile(ctx context.Context, req *CreateDownloadRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDownloadFile not implemented")
}
func (*UnimplementedAPIServer) GetNotebooks(ctx context.Context, req *NotebookCellRequest) (*Notebooks, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotebooks not implemented")
}
func (*UnimplementedAPIServer) NewNotebook(ctx context.Context, req *NotebookMetadata) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewNotebook not implemented")
}
func (*UnimplementedAPIServer) UpdateNotebook(ctx context.Context, req *NotebookMetadata) (*NotebookMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotebook not implemented")
}
func (*UnimplementedAPIServer) NewNotebookCell(ctx context.Context, req *NotebookCellRequest) (*NotebookMetadata, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewNotebookCell not implemented")
}
func (*UnimplementedAPIServer) GetNotebookCell(ctx context.Context, req *NotebookCellRequest) (*NotebookCell, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotebookCell not implemented")
}
func (*UnimplementedAPIServer) UpdateNotebookCell(ctx context.Context, req *NotebookCellRequest) (*NotebookCell, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNotebookCell not implemented")
}
func (*UnimplementedAPIServer) CancelNotebookCell(ctx context.Context, req *NotebookCellRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelNotebookCell not implemented")
}
func (*UnimplementedAPIServer) CreateNotebookDownloadFile(ctx context.Context, req *NotebookExportRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNotebookDownloadFile not implemented")
}
func (*UnimplementedAPIServer) UploadNotebookAttachment(ctx context.Context, req *NotebookFileUploadRequest) (*NotebookFileUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadNotebookAttachment not implemented")
}
func (*UnimplementedAPIServer) ExportNotebook(ctx context.Context, req *NotebookExportRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportNotebook not implemented")
}
func (*UnimplementedAPIServer) Query(req *proto3.VQLCollectorArgs, srv API_QueryServer) error {
	return status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (*UnimplementedAPIServer) WriteEvent(ctx context.Context, req *proto3.VQLResponse) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteEvent not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_CreateHunt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hunt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateHunt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CreateHunt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateHunt(ctx, req.(*Hunt))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListHunts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHuntsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListHunts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/ListHunts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListHunts(ctx, req.(*ListHuntsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetHunt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHuntRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetHunt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetHunt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetHunt(ctx, req.(*GetHuntRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ModifyHunt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hunt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ModifyHunt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/ModifyHunt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ModifyHunt(ctx, req.(*Hunt))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetHuntResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHuntResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetHuntResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetHuntResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetHuntResults(ctx, req.(*GetHuntResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_NotifyClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).NotifyClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/NotifyClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).NotifyClients(ctx, req.(*NotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_LabelClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LabelClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).LabelClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/LabelClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).LabelClients(ctx, req.(*LabelClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/ListClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListClients(ctx, req.(*SearchClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetClient(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetClientFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetClientFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetClientFlows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetClientFlows(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetUserUITraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetUserUITraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetUserUITraits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetUserUITraits(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetUserNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetUserNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetUserNotifications",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetUserNotifications(ctx, req.(*GetUserNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetUserNotificationCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetUserNotificationCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetUserNotificationCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetUserNotificationCount(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_VFSListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.VFSListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).VFSListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/VFSListDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).VFSListDirectory(ctx, req.(*proto1.VFSListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_VFSRefreshDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VFSRefreshDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).VFSRefreshDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/VFSRefreshDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).VFSRefreshDirectory(ctx, req.(*VFSRefreshDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_VFSStatDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.VFSListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).VFSStatDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/VFSStatDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).VFSStatDirectory(ctx, req.(*proto1.VFSListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_VFSStatDownload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.VFSListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).VFSStatDownload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/VFSStatDownload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).VFSStatDownload(ctx, req.(*proto1.VFSListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_VFSGetBuffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VFSFileBuffer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).VFSGetBuffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/VFSGetBuffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).VFSGetBuffer(ctx, req.(*VFSFileBuffer))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetTable(ctx, req.(*GetTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CollectArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.ArtifactCollectorArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CollectArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CollectArtifact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CollectArtifact(ctx, req.(*proto1.ArtifactCollectorArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CancelFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CancelFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CancelFlow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CancelFlow(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ArchiveFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ArchiveFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/ArchiveFlow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ArchiveFlow(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetFlowDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetFlowDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetFlowDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetFlowDetails(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetFlowRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetFlowRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetFlowRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetFlowRequests(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DescribeTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DescribeTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/DescribeTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DescribeTypes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetKeywordCompletions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetKeywordCompletions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetKeywordCompletions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetKeywordCompletions(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetArtifacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetArtifacts(ctx, req.(*GetArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetArtifactFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetArtifactFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetArtifactFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetArtifactFile(ctx, req.(*GetArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SetArtifactFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SetArtifactFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/SetArtifactFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SetArtifactFile(ctx, req.(*SetArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetReport(ctx, req.(*GetReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetServerMonitoringState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetServerMonitoringState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetServerMonitoringState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetServerMonitoringState(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SetServerMonitoringState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.ArtifactCollectorArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SetServerMonitoringState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/SetServerMonitoringState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SetServerMonitoringState(ctx, req.(*proto1.ArtifactCollectorArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetClientMonitoringState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetClientMonitoringState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetClientMonitoringState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetClientMonitoringState(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_SetClientMonitoringState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.ArtifactCollectorArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).SetClientMonitoringState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/SetClientMonitoringState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).SetClientMonitoringState(ctx, req.(*proto1.ArtifactCollectorArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListAvailableEventResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableEventResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListAvailableEventResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/ListAvailableEventResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListAvailableEventResults(ctx, req.(*ListAvailableEventResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateDownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateDownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CreateDownloadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateDownloadFile(ctx, req.(*CreateDownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetNotebooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetNotebooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetNotebooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetNotebooks(ctx, req.(*NotebookCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_NewNotebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).NewNotebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/NewNotebook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).NewNotebook(ctx, req.(*NotebookMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateNotebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookMetadata)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateNotebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/UpdateNotebook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateNotebook(ctx, req.(*NotebookMetadata))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_NewNotebookCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).NewNotebookCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/NewNotebookCell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).NewNotebookCell(ctx, req.(*NotebookCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetNotebookCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetNotebookCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetNotebookCell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetNotebookCell(ctx, req.(*NotebookCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateNotebookCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateNotebookCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/UpdateNotebookCell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateNotebookCell(ctx, req.(*NotebookCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CancelNotebookCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CancelNotebookCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CancelNotebookCell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CancelNotebookCell(ctx, req.(*NotebookCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateNotebookDownloadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateNotebookDownloadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/CreateNotebookDownloadFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateNotebookDownloadFile(ctx, req.(*NotebookExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UploadNotebookAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookFileUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UploadNotebookAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/UploadNotebookAttachment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UploadNotebookAttachment(ctx, req.(*NotebookFileUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ExportNotebook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotebookExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ExportNotebook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/ExportNotebook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ExportNotebook(ctx, req.(*NotebookExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Query_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(proto3.VQLCollectorArgs)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).Query(m, &aPIQueryServer{stream})
}

type API_QueryServer interface {
	Send(*proto3.VQLResponse) error
	grpc.ServerStream
}

type aPIQueryServer struct {
	grpc.ServerStream
}

func (x *aPIQueryServer) Send(m *proto3.VQLResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _API_WriteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto3.VQLResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).WriteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/WriteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).WriteEvent(ctx, req.(*proto3.VQLResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHunt",
			Handler:    _API_CreateHunt_Handler,
		},
		{
			MethodName: "ListHunts",
			Handler:    _API_ListHunts_Handler,
		},
		{
			MethodName: "GetHunt",
			Handler:    _API_GetHunt_Handler,
		},
		{
			MethodName: "ModifyHunt",
			Handler:    _API_ModifyHunt_Handler,
		},
		{
			MethodName: "GetHuntResults",
			Handler:    _API_GetHuntResults_Handler,
		},
		{
			MethodName: "NotifyClients",
			Handler:    _API_NotifyClients_Handler,
		},
		{
			MethodName: "LabelClients",
			Handler:    _API_LabelClients_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _API_ListClients_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _API_GetClient_Handler,
		},
		{
			MethodName: "GetClientFlows",
			Handler:    _API_GetClientFlows_Handler,
		},
		{
			MethodName: "GetUserUITraits",
			Handler:    _API_GetUserUITraits_Handler,
		},
		{
			MethodName: "GetUserNotifications",
			Handler:    _API_GetUserNotifications_Handler,
		},
		{
			MethodName: "GetUserNotificationCount",
			Handler:    _API_GetUserNotificationCount_Handler,
		},
		{
			MethodName: "VFSListDirectory",
			Handler:    _API_VFSListDirectory_Handler,
		},
		{
			MethodName: "VFSRefreshDirectory",
			Handler:    _API_VFSRefreshDirectory_Handler,
		},
		{
			MethodName: "VFSStatDirectory",
			Handler:    _API_VFSStatDirectory_Handler,
		},
		{
			MethodName: "VFSStatDownload",
			Handler:    _API_VFSStatDownload_Handler,
		},
		{
			MethodName: "VFSGetBuffer",
			Handler:    _API_VFSGetBuffer_Handler,
		},
		{
			MethodName: "GetTable",
			Handler:    _API_GetTable_Handler,
		},
		{
			MethodName: "CollectArtifact",
			Handler:    _API_CollectArtifact_Handler,
		},
		{
			MethodName: "CancelFlow",
			Handler:    _API_CancelFlow_Handler,
		},
		{
			MethodName: "ArchiveFlow",
			Handler:    _API_ArchiveFlow_Handler,
		},
		{
			MethodName: "GetFlowDetails",
			Handler:    _API_GetFlowDetails_Handler,
		},
		{
			MethodName: "GetFlowRequests",
			Handler:    _API_GetFlowRequests_Handler,
		},
		{
			MethodName: "DescribeTypes",
			Handler:    _API_DescribeTypes_Handler,
		},
		{
			MethodName: "GetKeywordCompletions",
			Handler:    _API_GetKeywordCompletions_Handler,
		},
		{
			MethodName: "GetArtifacts",
			Handler:    _API_GetArtifacts_Handler,
		},
		{
			MethodName: "GetArtifactFile",
			Handler:    _API_GetArtifactFile_Handler,
		},
		{
			MethodName: "SetArtifactFile",
			Handler:    _API_SetArtifactFile_Handler,
		},
		{
			MethodName: "GetReport",
			Handler:    _API_GetReport_Handler,
		},
		{
			MethodName: "GetServerMonitoringState",
			Handler:    _API_GetServerMonitoringState_Handler,
		},
		{
			MethodName: "SetServerMonitoringState",
			Handler:    _API_SetServerMonitoringState_Handler,
		},
		{
			MethodName: "GetClientMonitoringState",
			Handler:    _API_GetClientMonitoringState_Handler,
		},
		{
			MethodName: "SetClientMonitoringState",
			Handler:    _API_SetClientMonitoringState_Handler,
		},
		{
			MethodName: "ListAvailableEventResults",
			Handler:    _API_ListAvailableEventResults_Handler,
		},
		{
			MethodName: "CreateDownloadFile",
			Handler:    _API_CreateDownloadFile_Handler,
		},
		{
			MethodName: "GetNotebooks",
			Handler:    _API_GetNotebooks_Handler,
		},
		{
			MethodName: "NewNotebook",
			Handler:    _API_NewNotebook_Handler,
		},
		{
			MethodName: "UpdateNotebook",
			Handler:    _API_UpdateNotebook_Handler,
		},
		{
			MethodName: "NewNotebookCell",
			Handler:    _API_NewNotebookCell_Handler,
		},
		{
			MethodName: "GetNotebookCell",
			Handler:    _API_GetNotebookCell_Handler,
		},
		{
			MethodName: "UpdateNotebookCell",
			Handler:    _API_UpdateNotebookCell_Handler,
		},
		{
			MethodName: "CancelNotebookCell",
			Handler:    _API_CancelNotebookCell_Handler,
		},
		{
			MethodName: "CreateNotebookDownloadFile",
			Handler:    _API_CreateNotebookDownloadFile_Handler,
		},
		{
			MethodName: "UploadNotebookAttachment",
			Handler:    _API_UploadNotebookAttachment_Handler,
		},
		{
			MethodName: "ExportNotebook",
			Handler:    _API_ExportNotebook_Handler,
		},
		{
			MethodName: "WriteEvent",
			Handler:    _API_WriteEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Query",
			Handler:       _API_Query_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api.proto",
}
