// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import proto2 "www.velocidex.com/golang/velociraptor/actions/proto"
import proto1 "www.velocidex.com/golang/velociraptor/flows/proto"
import _ "www.velocidex.com/golang/velociraptor/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GUISettings_UIMode int32

const (
	GUISettings_BASIC    GUISettings_UIMode = 0
	GUISettings_ADVANCED GUISettings_UIMode = 1
	GUISettings_DEBUG    GUISettings_UIMode = 2
)

var GUISettings_UIMode_name = map[int32]string{
	0: "BASIC",
	1: "ADVANCED",
	2: "DEBUG",
}
var GUISettings_UIMode_value = map[string]int32{
	"BASIC":    0,
	"ADVANCED": 1,
	"DEBUG":    2,
}

func (x GUISettings_UIMode) String() string {
	return proto.EnumName(GUISettings_UIMode_name, int32(x))
}
func (GUISettings_UIMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{7, 0}
}

type ApiGrrUser_UserType int32

const (
	ApiGrrUser_USER_TYPE_NONE     ApiGrrUser_UserType = 0
	ApiGrrUser_USER_TYPE_STANDARD ApiGrrUser_UserType = 1
	ApiGrrUser_USER_TYPE_ADMIN    ApiGrrUser_UserType = 2
)

var ApiGrrUser_UserType_name = map[int32]string{
	0: "USER_TYPE_NONE",
	1: "USER_TYPE_STANDARD",
	2: "USER_TYPE_ADMIN",
}
var ApiGrrUser_UserType_value = map[string]int32{
	"USER_TYPE_NONE":     0,
	"USER_TYPE_STANDARD": 1,
	"USER_TYPE_ADMIN":    2,
}

func (x ApiGrrUser_UserType) String() string {
	return proto.EnumName(ApiGrrUser_UserType_name, int32(x))
}
func (ApiGrrUser_UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{9, 0}
}

type StartFlowResponse struct {
	FlowId               string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	RunnerArgs           *proto1.FlowRunnerArgs `protobuf:"bytes,2,opt,name=runner_args,json=runnerArgs,proto3" json:"runner_args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StartFlowResponse) Reset()         { *m = StartFlowResponse{} }
func (m *StartFlowResponse) String() string { return proto.CompactTextString(m) }
func (*StartFlowResponse) ProtoMessage()    {}
func (*StartFlowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{0}
}
func (m *StartFlowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartFlowResponse.Unmarshal(m, b)
}
func (m *StartFlowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartFlowResponse.Marshal(b, m, deterministic)
}
func (dst *StartFlowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartFlowResponse.Merge(dst, src)
}
func (m *StartFlowResponse) XXX_Size() int {
	return xxx_messageInfo_StartFlowResponse.Size(m)
}
func (m *StartFlowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartFlowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartFlowResponse proto.InternalMessageInfo

func (m *StartFlowResponse) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *StartFlowResponse) GetRunnerArgs() *proto1.FlowRunnerArgs {
	if m != nil {
		return m.RunnerArgs
	}
	return nil
}

type FieldDescriptor struct {
	FriendlyName         string       `protobuf:"bytes,1,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Repeated             bool         `protobuf:"varint,3,opt,name=repeated,proto3" json:"repeated,omitempty"`
	Type                 string       `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Doc                  string       `protobuf:"bytes,5,opt,name=doc,proto3" json:"doc,omitempty"`
	Labels               []string     `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Default              string       `protobuf:"bytes,7,opt,name=default,proto3" json:"default,omitempty"`
	AllowedValues        []*EnumValue `protobuf:"bytes,8,rep,name=allowed_values,json=allowedValues,proto3" json:"allowed_values,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FieldDescriptor) Reset()         { *m = FieldDescriptor{} }
func (m *FieldDescriptor) String() string { return proto.CompactTextString(m) }
func (*FieldDescriptor) ProtoMessage()    {}
func (*FieldDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{1}
}
func (m *FieldDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDescriptor.Unmarshal(m, b)
}
func (m *FieldDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDescriptor.Marshal(b, m, deterministic)
}
func (dst *FieldDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDescriptor.Merge(dst, src)
}
func (m *FieldDescriptor) XXX_Size() int {
	return xxx_messageInfo_FieldDescriptor.Size(m)
}
func (m *FieldDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDescriptor proto.InternalMessageInfo

func (m *FieldDescriptor) GetFriendlyName() string {
	if m != nil {
		return m.FriendlyName
	}
	return ""
}

func (m *FieldDescriptor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldDescriptor) GetRepeated() bool {
	if m != nil {
		return m.Repeated
	}
	return false
}

func (m *FieldDescriptor) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *FieldDescriptor) GetDoc() string {
	if m != nil {
		return m.Doc
	}
	return ""
}

func (m *FieldDescriptor) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *FieldDescriptor) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

func (m *FieldDescriptor) GetAllowedValues() []*EnumValue {
	if m != nil {
		return m.AllowedValues
	}
	return nil
}

type EnumValue struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnumValue) Reset()         { *m = EnumValue{} }
func (m *EnumValue) String() string { return proto.CompactTextString(m) }
func (*EnumValue) ProtoMessage()    {}
func (*EnumValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{2}
}
func (m *EnumValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnumValue.Unmarshal(m, b)
}
func (m *EnumValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnumValue.Marshal(b, m, deterministic)
}
func (dst *EnumValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnumValue.Merge(dst, src)
}
func (m *EnumValue) XXX_Size() int {
	return xxx_messageInfo_EnumValue.Size(m)
}
func (m *EnumValue) XXX_DiscardUnknown() {
	xxx_messageInfo_EnumValue.DiscardUnknown(m)
}

var xxx_messageInfo_EnumValue proto.InternalMessageInfo

func (m *EnumValue) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *EnumValue) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TypeDescriptor struct {
	Doc          string             `protobuf:"bytes,1,opt,name=doc,proto3" json:"doc,omitempty"`
	Fields       []*FieldDescriptor `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Name         string             `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	FriendlyName string             `protobuf:"bytes,7,opt,name=friendly_name,json=friendlyName,proto3" json:"friendly_name,omitempty"`
	Kind         string             `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	// The fields are all part of a single one of structure. NOTE:
	// Currently we only support an all or nothing approach to oneof -
	// there can be at most a single oneof group within the proto and
	// it implies that all the fields belong to it.
	Oneof                bool     `protobuf:"varint,5,opt,name=oneof,proto3" json:"oneof,omitempty"`
	Default              string   `protobuf:"bytes,6,opt,name=default,proto3" json:"default,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TypeDescriptor) Reset()         { *m = TypeDescriptor{} }
func (m *TypeDescriptor) String() string { return proto.CompactTextString(m) }
func (*TypeDescriptor) ProtoMessage()    {}
func (*TypeDescriptor) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{3}
}
func (m *TypeDescriptor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeDescriptor.Unmarshal(m, b)
}
func (m *TypeDescriptor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeDescriptor.Marshal(b, m, deterministic)
}
func (dst *TypeDescriptor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeDescriptor.Merge(dst, src)
}
func (m *TypeDescriptor) XXX_Size() int {
	return xxx_messageInfo_TypeDescriptor.Size(m)
}
func (m *TypeDescriptor) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeDescriptor.DiscardUnknown(m)
}

var xxx_messageInfo_TypeDescriptor proto.InternalMessageInfo

func (m *TypeDescriptor) GetDoc() string {
	if m != nil {
		return m.Doc
	}
	return ""
}

func (m *TypeDescriptor) GetFields() []*FieldDescriptor {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *TypeDescriptor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TypeDescriptor) GetFriendlyName() string {
	if m != nil {
		return m.FriendlyName
	}
	return ""
}

func (m *TypeDescriptor) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *TypeDescriptor) GetOneof() bool {
	if m != nil {
		return m.Oneof
	}
	return false
}

func (m *TypeDescriptor) GetDefault() string {
	if m != nil {
		return m.Default
	}
	return ""
}

type Types struct {
	Items                []*TypeDescriptor `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Types) Reset()         { *m = Types{} }
func (m *Types) String() string { return proto.CompactTextString(m) }
func (*Types) ProtoMessage()    {}
func (*Types) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{4}
}
func (m *Types) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Types.Unmarshal(m, b)
}
func (m *Types) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Types.Marshal(b, m, deterministic)
}
func (dst *Types) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Types.Merge(dst, src)
}
func (m *Types) XXX_Size() int {
	return xxx_messageInfo_Types.Size(m)
}
func (m *Types) XXX_DiscardUnknown() {
	xxx_messageInfo_Types.DiscardUnknown(m)
}

var xxx_messageInfo_Types proto.InternalMessageInfo

func (m *Types) GetItems() []*TypeDescriptor {
	if m != nil {
		return m.Items
	}
	return nil
}

type Approval struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Approval) Reset()         { *m = Approval{} }
func (m *Approval) String() string { return proto.CompactTextString(m) }
func (*Approval) ProtoMessage()    {}
func (*Approval) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{5}
}
func (m *Approval) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Approval.Unmarshal(m, b)
}
func (m *Approval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Approval.Marshal(b, m, deterministic)
}
func (dst *Approval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Approval.Merge(dst, src)
}
func (m *Approval) XXX_Size() int {
	return xxx_messageInfo_Approval.Size(m)
}
func (m *Approval) XXX_DiscardUnknown() {
	xxx_messageInfo_Approval.DiscardUnknown(m)
}

var xxx_messageInfo_Approval proto.InternalMessageInfo

func (m *Approval) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ApprovalList struct {
	Items                []*Approval `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ApprovalList) Reset()         { *m = ApprovalList{} }
func (m *ApprovalList) String() string { return proto.CompactTextString(m) }
func (*ApprovalList) ProtoMessage()    {}
func (*ApprovalList) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{6}
}
func (m *ApprovalList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApprovalList.Unmarshal(m, b)
}
func (m *ApprovalList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApprovalList.Marshal(b, m, deterministic)
}
func (dst *ApprovalList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApprovalList.Merge(dst, src)
}
func (m *ApprovalList) XXX_Size() int {
	return xxx_messageInfo_ApprovalList.Size(m)
}
func (m *ApprovalList) XXX_DiscardUnknown() {
	xxx_messageInfo_ApprovalList.DiscardUnknown(m)
}

var xxx_messageInfo_ApprovalList proto.InternalMessageInfo

func (m *ApprovalList) GetItems() []*Approval {
	if m != nil {
		return m.Items
	}
	return nil
}

// Next field: 4
type GUISettings struct {
	Mode                 GUISettings_UIMode `protobuf:"varint,1,opt,name=mode,proto3,enum=proto.GUISettings_UIMode" json:"mode,omitempty"`
	CanaryMode           bool               `protobuf:"varint,3,opt,name=canary_mode,json=canaryMode,proto3" json:"canary_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GUISettings) Reset()         { *m = GUISettings{} }
func (m *GUISettings) String() string { return proto.CompactTextString(m) }
func (*GUISettings) ProtoMessage()    {}
func (*GUISettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{7}
}
func (m *GUISettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GUISettings.Unmarshal(m, b)
}
func (m *GUISettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GUISettings.Marshal(b, m, deterministic)
}
func (dst *GUISettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GUISettings.Merge(dst, src)
}
func (m *GUISettings) XXX_Size() int {
	return xxx_messageInfo_GUISettings.Size(m)
}
func (m *GUISettings) XXX_DiscardUnknown() {
	xxx_messageInfo_GUISettings.DiscardUnknown(m)
}

var xxx_messageInfo_GUISettings proto.InternalMessageInfo

func (m *GUISettings) GetMode() GUISettings_UIMode {
	if m != nil {
		return m.Mode
	}
	return GUISettings_BASIC
}

func (m *GUISettings) GetCanaryMode() bool {
	if m != nil {
		return m.CanaryMode
	}
	return false
}

// These traits are used by the AdminUI Angular app to disable certain UI
// elements.
type ApiGrrUserInterfaceTraits struct {
	CronJobsNavItemEnabled                bool     `protobuf:"varint,1,opt,name=cron_jobs_nav_item_enabled,json=cronJobsNavItemEnabled,proto3" json:"cron_jobs_nav_item_enabled,omitempty"`
	CreateCronJobActionEnabled            bool     `protobuf:"varint,2,opt,name=create_cron_job_action_enabled,json=createCronJobActionEnabled,proto3" json:"create_cron_job_action_enabled,omitempty"`
	HuntManagerNavItemEnabled             bool     `protobuf:"varint,3,opt,name=hunt_manager_nav_item_enabled,json=huntManagerNavItemEnabled,proto3" json:"hunt_manager_nav_item_enabled,omitempty"`
	CreateHuntActionEnabled               bool     `protobuf:"varint,4,opt,name=create_hunt_action_enabled,json=createHuntActionEnabled,proto3" json:"create_hunt_action_enabled,omitempty"`
	ShowStatisticsNavItemEnabled          bool     `protobuf:"varint,5,opt,name=show_statistics_nav_item_enabled,json=showStatisticsNavItemEnabled,proto3" json:"show_statistics_nav_item_enabled,omitempty"`
	ServerLoadNavItemEnabled              bool     `protobuf:"varint,7,opt,name=server_load_nav_item_enabled,json=serverLoadNavItemEnabled,proto3" json:"server_load_nav_item_enabled,omitempty"`
	ManageBinariesNavItemEnabled          bool     `protobuf:"varint,9,opt,name=manage_binaries_nav_item_enabled,json=manageBinariesNavItemEnabled,proto3" json:"manage_binaries_nav_item_enabled,omitempty"`
	UploadBinaryActionEnabled             bool     `protobuf:"varint,10,opt,name=upload_binary_action_enabled,json=uploadBinaryActionEnabled,proto3" json:"upload_binary_action_enabled,omitempty"`
	SettingsNavItemEnabled                bool     `protobuf:"varint,11,opt,name=settings_nav_item_enabled,json=settingsNavItemEnabled,proto3" json:"settings_nav_item_enabled,omitempty"`
	ArtifactManagerNavItemEnabled         bool     `protobuf:"varint,12,opt,name=artifact_manager_nav_item_enabled,json=artifactManagerNavItemEnabled,proto3" json:"artifact_manager_nav_item_enabled,omitempty"`
	UploadArtifactActionEnabled           bool     `protobuf:"varint,13,opt,name=upload_artifact_action_enabled,json=uploadArtifactActionEnabled,proto3" json:"upload_artifact_action_enabled,omitempty"`
	SearchClientsActionEnabled            bool     `protobuf:"varint,14,opt,name=search_clients_action_enabled,json=searchClientsActionEnabled,proto3" json:"search_clients_action_enabled,omitempty"`
	BrowseVirtualFileSystemNavItemEnabled bool     `protobuf:"varint,15,opt,name=browse_virtual_file_system_nav_item_enabled,json=browseVirtualFileSystemNavItemEnabled,proto3" json:"browse_virtual_file_system_nav_item_enabled,omitempty"`
	StartClientFlowNavItemEnabled         bool     `protobuf:"varint,16,opt,name=start_client_flow_nav_item_enabled,json=startClientFlowNavItemEnabled,proto3" json:"start_client_flow_nav_item_enabled,omitempty"`
	ManageClientFlowsNavItemEnabled       bool     `protobuf:"varint,17,opt,name=manage_client_flows_nav_item_enabled,json=manageClientFlowsNavItemEnabled,proto3" json:"manage_client_flows_nav_item_enabled,omitempty"`
	ModifyClientLabelsActionEnabled       bool     `protobuf:"varint,18,opt,name=modify_client_labels_action_enabled,json=modifyClientLabelsActionEnabled,proto3" json:"modify_client_labels_action_enabled,omitempty"`
	XXX_NoUnkeyedLiteral                  struct{} `json:"-"`
	XXX_unrecognized                      []byte   `json:"-"`
	XXX_sizecache                         int32    `json:"-"`
}

func (m *ApiGrrUserInterfaceTraits) Reset()         { *m = ApiGrrUserInterfaceTraits{} }
func (m *ApiGrrUserInterfaceTraits) String() string { return proto.CompactTextString(m) }
func (*ApiGrrUserInterfaceTraits) ProtoMessage()    {}
func (*ApiGrrUserInterfaceTraits) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{8}
}
func (m *ApiGrrUserInterfaceTraits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGrrUserInterfaceTraits.Unmarshal(m, b)
}
func (m *ApiGrrUserInterfaceTraits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGrrUserInterfaceTraits.Marshal(b, m, deterministic)
}
func (dst *ApiGrrUserInterfaceTraits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGrrUserInterfaceTraits.Merge(dst, src)
}
func (m *ApiGrrUserInterfaceTraits) XXX_Size() int {
	return xxx_messageInfo_ApiGrrUserInterfaceTraits.Size(m)
}
func (m *ApiGrrUserInterfaceTraits) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGrrUserInterfaceTraits.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGrrUserInterfaceTraits proto.InternalMessageInfo

func (m *ApiGrrUserInterfaceTraits) GetCronJobsNavItemEnabled() bool {
	if m != nil {
		return m.CronJobsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetCreateCronJobActionEnabled() bool {
	if m != nil {
		return m.CreateCronJobActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetHuntManagerNavItemEnabled() bool {
	if m != nil {
		return m.HuntManagerNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetCreateHuntActionEnabled() bool {
	if m != nil {
		return m.CreateHuntActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetShowStatisticsNavItemEnabled() bool {
	if m != nil {
		return m.ShowStatisticsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetServerLoadNavItemEnabled() bool {
	if m != nil {
		return m.ServerLoadNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetManageBinariesNavItemEnabled() bool {
	if m != nil {
		return m.ManageBinariesNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetUploadBinaryActionEnabled() bool {
	if m != nil {
		return m.UploadBinaryActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetSettingsNavItemEnabled() bool {
	if m != nil {
		return m.SettingsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetArtifactManagerNavItemEnabled() bool {
	if m != nil {
		return m.ArtifactManagerNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetUploadArtifactActionEnabled() bool {
	if m != nil {
		return m.UploadArtifactActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetSearchClientsActionEnabled() bool {
	if m != nil {
		return m.SearchClientsActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetBrowseVirtualFileSystemNavItemEnabled() bool {
	if m != nil {
		return m.BrowseVirtualFileSystemNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetStartClientFlowNavItemEnabled() bool {
	if m != nil {
		return m.StartClientFlowNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetManageClientFlowsNavItemEnabled() bool {
	if m != nil {
		return m.ManageClientFlowsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetModifyClientLabelsActionEnabled() bool {
	if m != nil {
		return m.ModifyClientLabelsActionEnabled
	}
	return false
}

type ApiGrrUser struct {
	Username             string                     `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Settings             *GUISettings               `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	InterfaceTraits      *ApiGrrUserInterfaceTraits `protobuf:"bytes,3,opt,name=interface_traits,json=interfaceTraits,proto3" json:"interface_traits,omitempty"`
	UserType             ApiGrrUser_UserType        `protobuf:"varint,4,opt,name=user_type,json=userType,proto3,enum=proto.ApiGrrUser_UserType" json:"user_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ApiGrrUser) Reset()         { *m = ApiGrrUser{} }
func (m *ApiGrrUser) String() string { return proto.CompactTextString(m) }
func (*ApiGrrUser) ProtoMessage()    {}
func (*ApiGrrUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{9}
}
func (m *ApiGrrUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGrrUser.Unmarshal(m, b)
}
func (m *ApiGrrUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGrrUser.Marshal(b, m, deterministic)
}
func (dst *ApiGrrUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGrrUser.Merge(dst, src)
}
func (m *ApiGrrUser) XXX_Size() int {
	return xxx_messageInfo_ApiGrrUser.Size(m)
}
func (m *ApiGrrUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGrrUser.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGrrUser proto.InternalMessageInfo

func (m *ApiGrrUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ApiGrrUser) GetSettings() *GUISettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *ApiGrrUser) GetInterfaceTraits() *ApiGrrUserInterfaceTraits {
	if m != nil {
		return m.InterfaceTraits
	}
	return nil
}

func (m *ApiGrrUser) GetUserType() ApiGrrUser_UserType {
	if m != nil {
		return m.UserType
	}
	return ApiGrrUser_USER_TYPE_NONE
}

type VFSRefreshDirectoryRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	VfsPath              string   `protobuf:"bytes,2,opt,name=vfs_path,json=vfsPath,proto3" json:"vfs_path,omitempty"`
	Depth                uint64   `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VFSRefreshDirectoryRequest) Reset()         { *m = VFSRefreshDirectoryRequest{} }
func (m *VFSRefreshDirectoryRequest) String() string { return proto.CompactTextString(m) }
func (*VFSRefreshDirectoryRequest) ProtoMessage()    {}
func (*VFSRefreshDirectoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_d961a4b3f959a4a3, []int{10}
}
func (m *VFSRefreshDirectoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VFSRefreshDirectoryRequest.Unmarshal(m, b)
}
func (m *VFSRefreshDirectoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VFSRefreshDirectoryRequest.Marshal(b, m, deterministic)
}
func (dst *VFSRefreshDirectoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VFSRefreshDirectoryRequest.Merge(dst, src)
}
func (m *VFSRefreshDirectoryRequest) XXX_Size() int {
	return xxx_messageInfo_VFSRefreshDirectoryRequest.Size(m)
}
func (m *VFSRefreshDirectoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VFSRefreshDirectoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VFSRefreshDirectoryRequest proto.InternalMessageInfo

func (m *VFSRefreshDirectoryRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VFSRefreshDirectoryRequest) GetVfsPath() string {
	if m != nil {
		return m.VfsPath
	}
	return ""
}

func (m *VFSRefreshDirectoryRequest) GetDepth() uint64 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func init() {
	proto.RegisterType((*StartFlowResponse)(nil), "proto.StartFlowResponse")
	proto.RegisterType((*FieldDescriptor)(nil), "proto.FieldDescriptor")
	proto.RegisterType((*EnumValue)(nil), "proto.EnumValue")
	proto.RegisterType((*TypeDescriptor)(nil), "proto.TypeDescriptor")
	proto.RegisterType((*Types)(nil), "proto.Types")
	proto.RegisterType((*Approval)(nil), "proto.Approval")
	proto.RegisterType((*ApprovalList)(nil), "proto.ApprovalList")
	proto.RegisterType((*GUISettings)(nil), "proto.GUISettings")
	proto.RegisterType((*ApiGrrUserInterfaceTraits)(nil), "proto.ApiGrrUserInterfaceTraits")
	proto.RegisterType((*ApiGrrUser)(nil), "proto.ApiGrrUser")
	proto.RegisterType((*VFSRefreshDirectoryRequest)(nil), "proto.VFSRefreshDirectoryRequest")
	proto.RegisterEnum("proto.GUISettings_UIMode", GUISettings_UIMode_name, GUISettings_UIMode_value)
	proto.RegisterEnum("proto.ApiGrrUser_UserType", ApiGrrUser_UserType_name, ApiGrrUser_UserType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	LaunchFlow(ctx context.Context, in *proto1.FlowRunnerArgs, opts ...grpc.CallOption) (*StartFlowResponse, error)
	ListClients(ctx context.Context, in *SearchClientsRequest, opts ...grpc.CallOption) (*SearchClientsResponse, error)
	GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*ApiClient, error)
	GetClientFlows(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowResponse, error)
	GetClientApprovalForUser(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*ApprovalList, error)
	GetUserUITraits(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ApiGrrUser, error)
	// VFS
	VFSListDirectory(ctx context.Context, in *proto1.VFSListRequest, opts ...grpc.CallOption) (*proto2.VQLResponse, error)
	VFSRefreshDirectory(ctx context.Context, in *VFSRefreshDirectoryRequest, opts ...grpc.CallOption) (*StartFlowResponse, error)
	// Flows
	GetFlowDetails(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlow, error)
	GetFlowRequests(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowRequestDetails, error)
	GetFlowResults(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowResultDetails, error)
	GetFlowLogs(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowLogDetails, error)
	GetFlowDescriptors(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FlowDescriptors, error)
	DescribeTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Types, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) LaunchFlow(ctx context.Context, in *proto1.FlowRunnerArgs, opts ...grpc.CallOption) (*StartFlowResponse, error) {
	out := new(StartFlowResponse)
	err := c.cc.Invoke(ctx, "/proto.API/LaunchFlow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListClients(ctx context.Context, in *SearchClientsRequest, opts ...grpc.CallOption) (*SearchClientsResponse, error) {
	out := new(SearchClientsResponse)
	err := c.cc.Invoke(ctx, "/proto.API/ListClients", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetClient(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*ApiClient, error) {
	out := new(ApiClient)
	err := c.cc.Invoke(ctx, "/proto.API/GetClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetClientFlows(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowResponse, error) {
	out := new(ApiFlowResponse)
	err := c.cc.Invoke(ctx, "/proto.API/GetClientFlows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetClientApprovalForUser(ctx context.Context, in *GetClientRequest, opts ...grpc.CallOption) (*ApprovalList, error) {
	out := new(ApprovalList)
	err := c.cc.Invoke(ctx, "/proto.API/GetClientApprovalForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetUserUITraits(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ApiGrrUser, error) {
	out := new(ApiGrrUser)
	err := c.cc.Invoke(ctx, "/proto.API/GetUserUITraits", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) VFSListDirectory(ctx context.Context, in *proto1.VFSListRequest, opts ...grpc.CallOption) (*proto2.VQLResponse, error) {
	out := new(proto2.VQLResponse)
	err := c.cc.Invoke(ctx, "/proto.API/VFSListDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) VFSRefreshDirectory(ctx context.Context, in *VFSRefreshDirectoryRequest, opts ...grpc.CallOption) (*StartFlowResponse, error) {
	out := new(StartFlowResponse)
	err := c.cc.Invoke(ctx, "/proto.API/VFSRefreshDirectory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetFlowDetails(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlow, error) {
	out := new(ApiFlow)
	err := c.cc.Invoke(ctx, "/proto.API/GetFlowDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetFlowRequests(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowRequestDetails, error) {
	out := new(ApiFlowRequestDetails)
	err := c.cc.Invoke(ctx, "/proto.API/GetFlowRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetFlowResults(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowResultDetails, error) {
	out := new(ApiFlowResultDetails)
	err := c.cc.Invoke(ctx, "/proto.API/GetFlowResults", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetFlowLogs(ctx context.Context, in *ApiFlowRequest, opts ...grpc.CallOption) (*ApiFlowLogDetails, error) {
	out := new(ApiFlowLogDetails)
	err := c.cc.Invoke(ctx, "/proto.API/GetFlowLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetFlowDescriptors(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*FlowDescriptors, error) {
	out := new(FlowDescriptors)
	err := c.cc.Invoke(ctx, "/proto.API/GetFlowDescriptors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DescribeTypes(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Types, error) {
	out := new(Types)
	err := c.cc.Invoke(ctx, "/proto.API/DescribeTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	LaunchFlow(context.Context, *proto1.FlowRunnerArgs) (*StartFlowResponse, error)
	ListClients(context.Context, *SearchClientsRequest) (*SearchClientsResponse, error)
	GetClient(context.Context, *GetClientRequest) (*ApiClient, error)
	GetClientFlows(context.Context, *ApiFlowRequest) (*ApiFlowResponse, error)
	GetClientApprovalForUser(context.Context, *GetClientRequest) (*ApprovalList, error)
	GetUserUITraits(context.Context, *empty.Empty) (*ApiGrrUser, error)
	// VFS
	VFSListDirectory(context.Context, *proto1.VFSListRequest) (*proto2.VQLResponse, error)
	VFSRefreshDirectory(context.Context, *VFSRefreshDirectoryRequest) (*StartFlowResponse, error)
	// Flows
	GetFlowDetails(context.Context, *ApiFlowRequest) (*ApiFlow, error)
	GetFlowRequests(context.Context, *ApiFlowRequest) (*ApiFlowRequestDetails, error)
	GetFlowResults(context.Context, *ApiFlowRequest) (*ApiFlowResultDetails, error)
	GetFlowLogs(context.Context, *ApiFlowRequest) (*ApiFlowLogDetails, error)
	GetFlowDescriptors(context.Context, *empty.Empty) (*FlowDescriptors, error)
	DescribeTypes(context.Context, *empty.Empty) (*Types, error)
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_LaunchFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.FlowRunnerArgs)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).LaunchFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/LaunchFlow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).LaunchFlow(ctx, req.(*proto1.FlowRunnerArgs))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListClients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchClientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListClients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/ListClients",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListClients(ctx, req.(*SearchClientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetClient(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetClientFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetClientFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetClientFlows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetClientFlows(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetClientApprovalForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetClientApprovalForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetClientApprovalForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetClientApprovalForUser(ctx, req.(*GetClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetUserUITraits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetUserUITraits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetUserUITraits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetUserUITraits(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_VFSListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(proto1.VFSListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).VFSListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/VFSListDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).VFSListDirectory(ctx, req.(*proto1.VFSListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_VFSRefreshDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VFSRefreshDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).VFSRefreshDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/VFSRefreshDirectory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).VFSRefreshDirectory(ctx, req.(*VFSRefreshDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetFlowDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetFlowDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetFlowDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetFlowDetails(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetFlowRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetFlowRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetFlowRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetFlowRequests(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetFlowResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetFlowResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetFlowResults",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetFlowResults(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetFlowLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetFlowLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetFlowLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetFlowLogs(ctx, req.(*ApiFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetFlowDescriptors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetFlowDescriptors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/GetFlowDescriptors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetFlowDescriptors(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DescribeTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DescribeTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.API/DescribeTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DescribeTypes(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LaunchFlow",
			Handler:    _API_LaunchFlow_Handler,
		},
		{
			MethodName: "ListClients",
			Handler:    _API_ListClients_Handler,
		},
		{
			MethodName: "GetClient",
			Handler:    _API_GetClient_Handler,
		},
		{
			MethodName: "GetClientFlows",
			Handler:    _API_GetClientFlows_Handler,
		},
		{
			MethodName: "GetClientApprovalForUser",
			Handler:    _API_GetClientApprovalForUser_Handler,
		},
		{
			MethodName: "GetUserUITraits",
			Handler:    _API_GetUserUITraits_Handler,
		},
		{
			MethodName: "VFSListDirectory",
			Handler:    _API_VFSListDirectory_Handler,
		},
		{
			MethodName: "VFSRefreshDirectory",
			Handler:    _API_VFSRefreshDirectory_Handler,
		},
		{
			MethodName: "GetFlowDetails",
			Handler:    _API_GetFlowDetails_Handler,
		},
		{
			MethodName: "GetFlowRequests",
			Handler:    _API_GetFlowRequests_Handler,
		},
		{
			MethodName: "GetFlowResults",
			Handler:    _API_GetFlowResults_Handler,
		},
		{
			MethodName: "GetFlowLogs",
			Handler:    _API_GetFlowLogs_Handler,
		},
		{
			MethodName: "GetFlowDescriptors",
			Handler:    _API_GetFlowDescriptors_Handler,
		},
		{
			MethodName: "DescribeTypes",
			Handler:    _API_DescribeTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_d961a4b3f959a4a3) }

var fileDescriptor_api_d961a4b3f959a4a3 = []byte{
	// 1978 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0x4f, 0x73, 0x1b, 0xb7,
	0x15, 0x0f, 0xf5, 0x97, 0x02, 0x65, 0x89, 0x86, 0x63, 0x89, 0xa2, 0x24, 0x1b, 0xde, 0xc8, 0xb5,
	0xea, 0xa8, 0xcb, 0x46, 0x8d, 0xe3, 0xc4, 0x69, 0x9a, 0x92, 0xa2, 0x28, 0xb3, 0x91, 0x15, 0x77,
	0x29, 0x69, 0x92, 0x4c, 0x3b, 0x3b, 0xe0, 0x2e, 0x96, 0xdc, 0x64, 0xb9, 0xa0, 0x01, 0x90, 0x0a,
	0xc7, 0xe3, 0x4b, 0x66, 0x9a, 0x63, 0x2f, 0xed, 0xa5, 0x9f, 0xa2, 0x87, 0x7e, 0x85, 0x7e, 0x83,
	0xde, 0x7a, 0xe8, 0xa1, 0xed, 0x77, 0xe8, 0x25, 0x87, 0x0e, 0x80, 0xc5, 0xf2, 0xaf, 0x92, 0xf8,
	0x22, 0xed, 0x02, 0xbf, 0xf7, 0x7b, 0xef, 0xfd, 0xf0, 0xf0, 0x80, 0x25, 0x58, 0xc1, 0xdd, 0xd0,
	0xee, 0x32, 0x2a, 0x28, 0x5c, 0x54, 0xff, 0x8a, 0x1f, 0x5d, 0x5d, 0x5d, 0xd9, 0x7d, 0x12, 0x51,
	0x2f, 0xf4, 0xc9, 0xd7, 0xb6, 0x47, 0x3b, 0xa5, 0x16, 0x8d, 0x70, 0xdc, 0x2a, 0xe9, 0x41, 0x86,
	0xbb, 0x82, 0xb2, 0x52, 0x10, 0xd1, 0x2b, 0x5e, 0x52, 0x26, 0xfa, 0x59, 0xb3, 0x14, 0x3f, 0x7c,
	0x7d, 0xf3, 0x7e, 0x60, 0x8c, 0x9f, 0xfc, 0x38, 0x63, 0x6d, 0xc6, 0x49, 0x07, 0xc7, 0x22, 0xf4,
	0xec, 0xd7, 0x8a, 0x1b, 0x7b, 0x22, 0xa4, 0x71, 0xea, 0xfa, 0x45, 0x94, 0x98, 0xef, 0xb4, 0x28,
	0x6d, 0x45, 0xa4, 0x84, 0xbb, 0x61, 0x09, 0xc7, 0x31, 0x15, 0x58, 0xe1, 0x92, 0xd9, 0xed, 0x64,
	0x56, 0xbd, 0x35, 0x7b, 0x41, 0x89, 0x74, 0xba, 0x62, 0x90, 0x4c, 0xde, 0xf0, 0xa2, 0x90, 0xc4,
	0xc2, 0x60, 0x73, 0x23, 0x72, 0x58, 0x3e, 0xb8, 0xd9, 0x10, 0x98, 0x89, 0x5a, 0x44, 0xaf, 0x1c,
	0xc2, 0xbb, 0x34, 0xe6, 0x04, 0x6e, 0x82, 0x65, 0x89, 0x71, 0x43, 0xbf, 0x90, 0x41, 0x99, 0xfd,
	0x15, 0x67, 0x49, 0xbe, 0xd6, 0x7d, 0xf8, 0x1e, 0xc8, 0xb1, 0x5e, 0x1c, 0x13, 0xe6, 0x62, 0xd6,
	0xe2, 0x85, 0x39, 0x94, 0xd9, 0xcf, 0x1d, 0xde, 0xd6, 0x54, 0xb6, 0xa2, 0x50, 0xb3, 0x65, 0xd6,
	0xe2, 0x0e, 0x60, 0xe9, 0xb3, 0xf5, 0xbf, 0x0c, 0x58, 0xaf, 0x85, 0x24, 0xf2, 0xab, 0x84, 0x7b,
	0x2c, 0x94, 0x89, 0xc2, 0xb7, 0xc0, 0x8d, 0x80, 0x85, 0x24, 0xf6, 0xa3, 0x81, 0x1b, 0xe3, 0x0e,
	0x49, 0x5c, 0xad, 0x9a, 0xc1, 0x33, 0xdc, 0x21, 0x10, 0x82, 0x05, 0x35, 0x37, 0xa7, 0xe6, 0xd4,
	0x33, 0x2c, 0x82, 0x2c, 0x23, 0x5d, 0x82, 0x05, 0xf1, 0x0b, 0xf3, 0x28, 0xb3, 0x9f, 0x75, 0xd2,
	0x77, 0x89, 0x17, 0x83, 0x2e, 0x29, 0x2c, 0x68, 0xbc, 0x7c, 0x86, 0x79, 0x30, 0xef, 0x53, 0xaf,
	0xb0, 0xa8, 0x86, 0xe4, 0x23, 0xdc, 0x00, 0x4b, 0x11, 0x6e, 0x92, 0x88, 0x17, 0x96, 0xd0, 0xbc,
	0x4c, 0x4f, 0xbf, 0xc1, 0x02, 0x58, 0xf6, 0x49, 0x80, 0x7b, 0x91, 0x28, 0x2c, 0x2b, 0xb4, 0x79,
	0x85, 0x8f, 0xc1, 0x1a, 0x8e, 0x22, 0x7a, 0x45, 0x7c, 0xb7, 0x8f, 0xa3, 0x1e, 0xe1, 0x85, 0x2c,
	0x9a, 0xdf, 0xcf, 0x1d, 0xe6, 0x93, 0xdc, 0x8f, 0xe3, 0x5e, 0xe7, 0x52, 0x4e, 0x38, 0x37, 0x12,
	0x9c, 0x7a, 0xe3, 0xd6, 0x23, 0xb0, 0x92, 0xce, 0xc1, 0x37, 0xc1, 0xa2, 0xb2, 0x56, 0xa9, 0x2e,
	0x3a, 0xfa, 0x65, 0x56, 0x8e, 0xd6, 0xb7, 0x73, 0x60, 0xed, 0x7c, 0xd0, 0x25, 0x23, 0x7a, 0x25,
	0x69, 0x64, 0x86, 0x69, 0xd8, 0x60, 0x29, 0x90, 0xa2, 0xca, 0x85, 0x90, 0xc1, 0x6c, 0x98, 0x85,
	0x18, 0x57, 0xda, 0x49, 0x50, 0xa9, 0xa3, 0xf9, 0x11, 0x31, 0xa7, 0x56, 0x61, 0x79, 0xf6, 0x2a,
	0x7c, 0x15, 0xc6, 0xbe, 0x51, 0x55, 0x3e, 0xcb, 0x5c, 0x68, 0x4c, 0x68, 0xa0, 0x74, 0xcd, 0x3a,
	0xfa, 0x05, 0x7e, 0x3a, 0x54, 0x70, 0x49, 0x82, 0x2b, 0x8f, 0xfe, 0xfd, 0xdd, 0x7f, 0xfe, 0x9e,
	0x29, 0xc1, 0x9f, 0x9d, 0xb7, 0x09, 0xfa, 0x92, 0xd3, 0x18, 0x91, 0xd8, 0xa3, 0x3e, 0xf1, 0x51,
	0x82, 0x43, 0x4a, 0x04, 0x14, 0x50, 0x86, 0x44, 0x3b, 0xe4, 0x48, 0x2e, 0x99, 0x9d, 0x0a, 0x6f,
	0xbd, 0x0b, 0x16, 0xa5, 0x0e, 0x1c, 0xbe, 0x0d, 0x16, 0x43, 0x41, 0x3a, 0xbc, 0x90, 0x51, 0xb9,
	0x9a, 0xa2, 0x1b, 0x17, 0xc9, 0xd1, 0x18, 0xcb, 0x02, 0xd9, 0x72, 0xb7, 0xcb, 0x68, 0x1f, 0x47,
	0x72, 0xb1, 0x19, 0xc1, 0x9c, 0xc6, 0xa6, 0x96, 0xf5, 0x9b, 0xf5, 0x08, 0xac, 0x1a, 0xcc, 0x69,
	0xc8, 0x05, 0xbc, 0x3f, 0xee, 0x60, 0x3d, 0x71, 0x60, 0x30, 0x86, 0xfa, 0x8f, 0x73, 0x20, 0x77,
	0x72, 0x51, 0x6f, 0x10, 0x21, 0xc2, 0xb8, 0xc5, 0xe1, 0x27, 0x60, 0xa1, 0x43, 0x7d, 0xbd, 0xa4,
	0x6b, 0x87, 0x5b, 0x89, 0xd5, 0x08, 0xc2, 0xbe, 0xa8, 0x3f, 0xa3, 0x3e, 0xa9, 0xec, 0x28, 0x25,
	0x36, 0xe0, 0x9b, 0x17, 0x9c, 0x30, 0x14, 0xc6, 0x82, 0xb0, 0x00, 0x7b, 0x04, 0x49, 0x6b, 0xdb,
	0x51, 0x24, 0xf0, 0x33, 0x90, 0xf3, 0x70, 0x8c, 0xd9, 0xc0, 0x55, 0x9c, 0xaa, 0xba, 0x2b, 0x8f,
	0x95, 0xe1, 0x3b, 0xb0, 0x54, 0x0f, 0x90, 0x60, 0x3d, 0x72, 0x80, 0x78, 0x9b, 0x5e, 0xa1, 0x80,
	0x60, 0xd1, 0x63, 0x84, 0x23, 0xd1, 0xc6, 0x02, 0x61, 0x46, 0x50, 0x93, 0x84, 0x71, 0x0b, 0x29,
	0x82, 0x90, 0xf8, 0xb6, 0x03, 0x34, 0x97, 0xf4, 0x6e, 0x1d, 0x80, 0x25, 0x1d, 0x07, 0x5c, 0x01,
	0x8b, 0x95, 0x72, 0xa3, 0x7e, 0x94, 0x7f, 0x03, 0xae, 0x82, 0x6c, 0xb9, 0x7a, 0x59, 0x3e, 0x3b,
	0x3a, 0xae, 0xe6, 0x33, 0x72, 0xa2, 0x7a, 0x5c, 0xb9, 0x38, 0xc9, 0xcf, 0x3d, 0x79, 0xf8, 0x4f,
	0xe9, 0x72, 0x0f, 0x58, 0x2a, 0xd6, 0x93, 0x8b, 0x3a, 0xe2, 0x49, 0x36, 0x08, 0xc7, 0x3e, 0xea,
	0x32, 0x12, 0x10, 0x46, 0x62, 0x8f, 0x70, 0xdb, 0xfa, 0x2e, 0x0b, 0xb6, 0xca, 0xdd, 0xf0, 0x84,
	0x31, 0x09, 0xae, 0x9b, 0xbc, 0xce, 0x19, 0x0e, 0x05, 0x87, 0x4f, 0x40, 0xd1, 0x63, 0x34, 0x76,
	0xbf, 0xa4, 0x4d, 0xee, 0xc6, 0xb8, 0xef, 0x4a, 0x15, 0x5d, 0x12, 0xe3, 0x66, 0x44, 0x74, 0x77,
	0xc9, 0x3a, 0x1b, 0x12, 0xf1, 0x1b, 0xda, 0xe4, 0x67, 0xb8, 0x5f, 0x17, 0xa4, 0x73, 0xac, 0x67,
	0x61, 0x05, 0xdc, 0xf1, 0x98, 0xdc, 0xd7, 0xae, 0xa1, 0x70, 0x75, 0x77, 0x4c, 0xed, 0xe7, 0x94,
	0x7d, 0x51, 0xa3, 0x8e, 0x34, 0x4b, 0x59, 0x41, 0x0c, 0xc7, 0xaf, 0xc1, 0x6e, 0xbb, 0x17, 0x0b,
	0xb7, 0x83, 0x63, 0xdc, 0x22, 0x6c, 0x3a, 0x04, 0xdd, 0x41, 0xb6, 0x24, 0xe8, 0x99, 0xc6, 0x4c,
	0x44, 0xf1, 0x21, 0x48, 0xf8, 0x5d, 0x45, 0x34, 0x11, 0xc1, 0x82, 0x32, 0xdf, 0xd4, 0x88, 0xa7,
	0xbd, 0x58, 0x8c, 0xbb, 0xaf, 0x01, 0xb5, 0x58, 0x2e, 0x97, 0xed, 0x9a, 0x8b, 0xd0, 0x9b, 0x21,
	0x82, 0xde, 0x40, 0x3b, 0x12, 0xd7, 0x48, 0x61, 0x13, 0x41, 0xfc, 0x0a, 0xec, 0x70, 0xc2, 0xfa,
	0x84, 0xb9, 0x11, 0xc5, 0xfe, 0x34, 0xc7, 0xb2, 0xe2, 0x28, 0x68, 0xcc, 0x29, 0xc5, 0xfe, 0x84,
	0x7d, 0x0d, 0x20, 0xad, 0x80, 0xdb, 0x0c, 0x55, 0x79, 0xcc, 0x88, 0x63, 0x45, 0xc7, 0xa1, 0x71,
	0x95, 0x04, 0x36, 0xc1, 0xf3, 0x31, 0xd8, 0xe9, 0x75, 0x55, 0x08, 0x8a, 0x67, 0x30, 0x29, 0x07,
	0xd0, 0x6a, 0x6a, 0x8c, 0xe2, 0x18, 0x8c, 0x0b, 0xf2, 0x01, 0xd8, 0x32, 0xa5, 0x34, 0x1d, 0x41,
	0x4e, 0x97, 0x83, 0x01, 0x4c, 0xf8, 0x7e, 0x0a, 0xee, 0x61, 0x26, 0xc2, 0x00, 0x7b, 0xdf, 0xb3,
	0x9c, 0xab, 0x8a, 0x62, 0xd7, 0x00, 0x67, 0x2f, 0xe9, 0x11, 0xb8, 0x93, 0x64, 0x91, 0x12, 0x4e,
	0xe4, 0x71, 0x43, 0xd1, 0x6c, 0x6b, 0x54, 0x39, 0x01, 0x8d, 0x67, 0x52, 0x06, 0xbb, 0x9c, 0x60,
	0xe6, 0xb5, 0xdd, 0xe4, 0x78, 0x9d, 0xe4, 0x58, 0xd3, 0xc5, 0xa9, 0x41, 0x47, 0x1a, 0x33, 0x4e,
	0xf1, 0x05, 0x78, 0xbb, 0xc9, 0xe8, 0x15, 0x27, 0x6e, 0x3f, 0x64, 0xa2, 0x87, 0x23, 0x37, 0x08,
	0x23, 0xe2, 0xf2, 0x01, 0x97, 0x29, 0x4d, 0xe5, 0xb6, 0xae, 0x08, 0xef, 0x6b, 0x93, 0x4b, 0x6d,
	0x51, 0x0b, 0x23, 0xd2, 0x50, 0xf8, 0x89, 0x1c, 0xeb, 0xc0, 0xe2, 0xf2, 0x60, 0x4f, 0xa2, 0x73,
	0xd5, 0x81, 0x3e, 0x45, 0x99, 0xd7, 0x72, 0x29, 0xa4, 0x0e, 0x51, 0x9e, 0xe2, 0x13, 0x54, 0xcf,
	0xc0, 0x5e, 0x52, 0x3c, 0x23, 0x5c, 0x33, 0x96, 0xef, 0xa6, 0x22, 0xbb, 0xab, 0xb1, 0x43, 0xb6,
	0xc9, 0x75, 0x3c, 0x05, 0x6f, 0x75, 0xa8, 0x1f, 0x06, 0x03, 0x43, 0xa7, 0x4f, 0xdf, 0x49, 0xf9,
	0x60, 0xc2, 0xa6, 0xa0, 0x9a, 0xed, 0x54, 0x01, 0xc7, 0x34, 0xb4, 0xfe, 0x3a, 0x0f, 0xc0, 0xb0,
	0xfd, 0xc0, 0x0f, 0x40, 0xb6, 0xc7, 0x09, 0x1b, 0x5e, 0x28, 0x2a, 0xbb, 0xaa, 0x7d, 0x6e, 0xc2,
	0xdb, 0xf2, 0x04, 0x92, 0xe3, 0x88, 0x06, 0x48, 0xb4, 0x09, 0x92, 0x38, 0xdb, 0x49, 0xe1, 0xb0,
	0x0e, 0xb2, 0xa6, 0xf2, 0x92, 0x9b, 0x0d, 0x9c, 0xee, 0xe6, 0x95, 0x2d, 0x45, 0x77, 0x0b, 0xde,
	0x54, 0xad, 0x71, 0xa4, 0x33, 0xda, 0x4e, 0x6a, 0x0e, 0xff, 0x9c, 0x01, 0xf9, 0xb4, 0xc3, 0xbb,
	0x42, 0xb5, 0x42, 0xd5, 0x69, 0x72, 0x87, 0x28, 0x3d, 0x57, 0xae, 0x69, 0x99, 0x95, 0x13, 0xe5,
	0xa1, 0x0c, 0x3f, 0x96, 0x93, 0x0f, 0xf8, 0xc8, 0x51, 0xa1, 0x89, 0xd0, 0xfe, 0x95, 0xec, 0xf8,
	0xa2, 0x4d, 0x06, 0xb2, 0xd9, 0xab, 0x8e, 0xec, 0xe1, 0xf8, 0x81, 0x40, 0x3e, 0x45, 0x61, 0xac,
	0x72, 0xbb, 0xa8, 0xff, 0xd4, 0x76, 0xd6, 0xc3, 0x89, 0x66, 0xfc, 0x18, 0xac, 0xc8, 0x6c, 0xdd,
	0xf4, 0x8a, 0xb4, 0x76, 0x58, 0x9c, 0x0a, 0xc7, 0x96, 0x7f, 0xe4, 0xb1, 0xaa, 0xa5, 0x91, 0x4f,
	0xd6, 0x27, 0x20, 0x6b, 0x46, 0x21, 0x04, 0x6b, 0x17, 0x8d, 0x63, 0xc7, 0x3d, 0xff, 0xfc, 0xf9,
	0xb1, 0x7b, 0xf6, 0xe9, 0xd9, 0x71, 0xfe, 0x0d, 0xb8, 0x01, 0xe0, 0x70, 0xac, 0x71, 0x5e, 0x3e,
	0xab, 0x96, 0x1d, 0x79, 0xa4, 0xdc, 0x02, 0xeb, 0xc3, 0xf1, 0x72, 0xf5, 0x59, 0xfd, 0x2c, 0x3f,
	0x67, 0xfd, 0x2b, 0x03, 0x8a, 0x97, 0xb5, 0x86, 0x43, 0x02, 0x46, 0x78, 0xbb, 0x1a, 0x32, 0xe2,
	0x09, 0xca, 0x06, 0x0e, 0x79, 0xd1, 0x23, 0x5c, 0xc0, 0x0a, 0x58, 0x49, 0xea, 0xc2, 0x5c, 0x3f,
	0x2b, 0xf7, 0x95, 0x22, 0x77, 0xc1, 0x92, 0x53, 0xad, 0x5d, 0x38, 0x67, 0x10, 0xca, 0xa5, 0xd4,
	0x20, 0x24, 0x28, 0x8a, 0x42, 0x2e, 0x8a, 0x99, 0x39, 0x27, 0xab, 0x87, 0xea, 0xf2, 0xe4, 0xc8,
	0xf6, 0x03, 0xee, 0x76, 0xb1, 0x68, 0xeb, 0x6b, 0x55, 0xe5, 0x81, 0xa2, 0xb8, 0x07, 0xef, 0x4a,
	0xd3, 0xcb, 0x5a, 0x03, 0x3d, 0xc7, 0xa2, 0x6d, 0x8c, 0x91, 0xdc, 0x76, 0x52, 0x68, 0x64, 0x3b,
	0xcb, 0xfd, 0x80, 0xcb, 0x39, 0xf8, 0x3e, 0x58, 0xf4, 0x49, 0x57, 0xb4, 0xd5, 0xba, 0x2d, 0x54,
	0x2c, 0x45, 0xb0, 0x03, 0x8b, 0x55, 0x39, 0x28, 0x6b, 0xc8, 0x37, 0x91, 0x23, 0xa6, 0x53, 0x71,
	0xb4, 0xc1, 0xe1, 0xdf, 0x56, 0xc1, 0x7c, 0xf9, 0x79, 0x1d, 0xfe, 0x0e, 0x80, 0x53, 0xdc, 0x8b,
	0xbd, 0xb6, 0xdc, 0x05, 0x70, 0xf6, 0x35, 0xb9, 0x58, 0x48, 0x86, 0xa7, 0x6e, 0xe1, 0xd6, 0xee,
	0x37, 0xff, 0xf8, 0xef, 0x9f, 0xe6, 0x36, 0x2d, 0xa8, 0xee, 0xfc, 0xfd, 0x77, 0x4a, 0x43, 0xb2,
	0x27, 0x99, 0x87, 0xb0, 0x05, 0x72, 0xf2, 0xde, 0x92, 0x34, 0x16, 0xb8, 0x6d, 0x78, 0x46, 0xdb,
	0x4d, 0xa2, 0x69, 0x71, 0x67, 0xf6, 0xe4, 0xb8, 0x23, 0x78, 0xdb, 0x38, 0x1a, 0x83, 0xc1, 0xcf,
	0xc1, 0xca, 0x09, 0x49, 0xfc, 0xc0, 0x4d, 0xb3, 0x25, 0xcc, 0x88, 0x71, 0x91, 0x1f, 0x16, 0x92,
	0x9e, 0xb0, 0xee, 0x29, 0xda, 0x6d, 0xb8, 0x65, 0x68, 0x53, 0x9b, 0xd2, 0xcb, 0x17, 0x3d, 0xc2,
	0x06, 0xaf, 0xe0, 0x5f, 0x32, 0x60, 0x2d, 0x1d, 0x55, 0xbd, 0x22, 0x95, 0xa9, 0xdc, 0x0d, 0xb5,
	0x1a, 0x9a, 0x7e, 0x63, 0x72, 0x38, 0x89, 0xfd, 0x33, 0xe5, 0xc4, 0x81, 0xd6, 0x94, 0x13, 0x45,
	0x57, 0x7a, 0x99, 0xd6, 0xd2, 0xab, 0x2f, 0x0e, 0x2a, 0x0f, 0xc1, 0xc2, 0xd3, 0xe3, 0x72, 0xf5,
	0xc7, 0xa0, 0x61, 0x0c, 0x0a, 0xe9, 0xac, 0xb9, 0x04, 0xd6, 0xa8, 0xee, 0x32, 0xd7, 0xaa, 0x70,
	0x6b, 0xe2, 0xd6, 0x28, 0x57, 0xc8, 0xda, 0x53, 0x31, 0xde, 0x81, 0x3b, 0x23, 0x5e, 0x0d, 0x80,
	0xa7, 0x5a, 0xfc, 0x1e, 0xac, 0x9f, 0x10, 0x21, 0xe9, 0x2f, 0xea, 0xc9, 0x7e, 0xdd, 0xb0, 0xf5,
	0x67, 0x9d, 0x6d, 0x3e, 0xeb, 0xec, 0x63, 0xf9, 0x59, 0x57, 0xbc, 0x39, 0xb5, 0x69, 0xad, 0xbb,
	0xca, 0xc7, 0x16, 0xdc, 0x1c, 0xf1, 0x31, 0xc6, 0xf5, 0x15, 0xc8, 0x5f, 0xd6, 0x1a, 0x32, 0x9e,
	0x74, 0xc7, 0xa5, 0x5a, 0x27, 0x13, 0x26, 0x09, 0xd3, 0xf6, 0x2e, 0x7f, 0x7b, 0x9a, 0xea, 0x7c,
	0xa0, 0xf8, 0x7f, 0x02, 0xf7, 0x0c, 0xff, 0x24, 0xd9, 0x98, 0x76, 0xdf, 0x66, 0xc0, 0xad, 0x19,
	0x5b, 0x1c, 0xde, 0x1b, 0x3a, 0xbc, 0x66, 0xfb, 0x7f, 0xcf, 0x7e, 0x38, 0x54, 0x21, 0x1c, 0x58,
	0x0f, 0x46, 0x42, 0x98, 0x64, 0x19, 0x8d, 0x42, 0x6e, 0x12, 0x4f, 0xd5, 0x97, 0xa4, 0xa9, 0x12,
	0x81, 0xc3, 0xe8, 0xda, 0xfa, 0x5a, 0x1b, 0x1f, 0xb6, 0x1e, 0x2a, 0x67, 0x7b, 0x63, 0x95, 0x32,
	0x42, 0x33, 0x96, 0xed, 0x1f, 0x32, 0x6a, 0xe9, 0x46, 0xe8, 0xae, 0x75, 0xb3, 0x33, 0x73, 0x38,
	0x21, 0xb5, 0x3e, 0x52, 0x4e, 0x1f, 0xc3, 0x47, 0x3f, 0xec, 0xb4, 0xf4, 0x32, 0xf9, 0x42, 0x7f,
	0x55, 0x62, 0xc6, 0xe7, 0x37, 0x99, 0x34, 0x5b, 0x87, 0xf0, 0x5e, 0x74, 0x7d, 0x18, 0xdb, 0x53,
	0xbb, 0xa9, 0x17, 0xa5, 0x51, 0xfc, 0x52, 0x45, 0xf1, 0x1e, 0x7c, 0xf7, 0x35, 0xa3, 0xd0, 0x1e,
	0xbf, 0x06, 0xb9, 0x04, 0x7f, 0x4a, 0x5b, 0xd7, 0x06, 0x50, 0x18, 0x1f, 0x3e, 0xa5, 0x2d, 0xe3,
	0xfd, 0x7d, 0xe5, 0xfd, 0x10, 0xfe, 0xfc, 0xb5, 0xbc, 0x47, 0xb4, 0x05, 0x5b, 0x00, 0xa6, 0x58,
	0xf3, 0x41, 0x78, 0xfd, 0x1e, 0xda, 0x18, 0x69, 0xc7, 0x23, 0xf8, 0xe9, 0xae, 0xa5, 0x7f, 0x09,
	0xf2, 0x47, 0x28, 0xcf, 0xc1, 0x0d, 0x6d, 0xd1, 0x24, 0xfa, 0xdb, 0xf4, 0x3a, 0x1f, 0xab, 0x23,
	0x1f, 0xa9, 0x7c, 0xba, 0xcd, 0x8e, 0x91, 0x34, 0x97, 0x14, 0xf6, 0x17, 0xff, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0x20, 0x19, 0xe3, 0x63, 0xf2, 0x12, 0x00, 0x00,
}
