// Code generated by protoc-gen-go. DO NOT EDIT.
// source: download.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateDownloadRequest struct {
	FlowId   string `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	HuntId   string `protobuf:"bytes,3,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	// When set we only create combined hunt output and not individual
	// flow breakdowns.
	OnlyCombinedHunt bool `protobuf:"varint,4,opt,name=only_combined_hunt,json=onlyCombinedHunt,proto3" json:"only_combined_hunt,omitempty"`
	JsonFormat       bool `protobuf:"varint,5,opt,name=json_format,json=jsonFormat,proto3" json:"json_format,omitempty"`
	CsvFormat        bool `protobuf:"varint,6,opt,name=csv_format,json=csvFormat,proto3" json:"csv_format,omitempty"`
	// Can be "report" for html report or "" for just files.
	DownloadType         string   `protobuf:"bytes,7,opt,name=download_type,json=downloadType,proto3" json:"download_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDownloadRequest) Reset()         { *m = CreateDownloadRequest{} }
func (m *CreateDownloadRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDownloadRequest) ProtoMessage()    {}
func (*CreateDownloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7ce52b48c9eea83, []int{0}
}

func (m *CreateDownloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDownloadRequest.Unmarshal(m, b)
}
func (m *CreateDownloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDownloadRequest.Marshal(b, m, deterministic)
}
func (m *CreateDownloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDownloadRequest.Merge(m, src)
}
func (m *CreateDownloadRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDownloadRequest.Size(m)
}
func (m *CreateDownloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDownloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDownloadRequest proto.InternalMessageInfo

func (m *CreateDownloadRequest) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *CreateDownloadRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *CreateDownloadRequest) GetHuntId() string {
	if m != nil {
		return m.HuntId
	}
	return ""
}

func (m *CreateDownloadRequest) GetOnlyCombinedHunt() bool {
	if m != nil {
		return m.OnlyCombinedHunt
	}
	return false
}

func (m *CreateDownloadRequest) GetJsonFormat() bool {
	if m != nil {
		return m.JsonFormat
	}
	return false
}

func (m *CreateDownloadRequest) GetCsvFormat() bool {
	if m != nil {
		return m.CsvFormat
	}
	return false
}

func (m *CreateDownloadRequest) GetDownloadType() string {
	if m != nil {
		return m.DownloadType
	}
	return ""
}

type CreateDownloadResponse struct {
	VfsPath              string   `protobuf:"bytes,1,opt,name=vfs_path,json=vfsPath,proto3" json:"vfs_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDownloadResponse) Reset()         { *m = CreateDownloadResponse{} }
func (m *CreateDownloadResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDownloadResponse) ProtoMessage()    {}
func (*CreateDownloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f7ce52b48c9eea83, []int{1}
}

func (m *CreateDownloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDownloadResponse.Unmarshal(m, b)
}
func (m *CreateDownloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDownloadResponse.Marshal(b, m, deterministic)
}
func (m *CreateDownloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDownloadResponse.Merge(m, src)
}
func (m *CreateDownloadResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDownloadResponse.Size(m)
}
func (m *CreateDownloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDownloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDownloadResponse proto.InternalMessageInfo

func (m *CreateDownloadResponse) GetVfsPath() string {
	if m != nil {
		return m.VfsPath
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateDownloadRequest)(nil), "proto.CreateDownloadRequest")
	proto.RegisterType((*CreateDownloadResponse)(nil), "proto.CreateDownloadResponse")
}

func init() {
	proto.RegisterFile("download.proto", fileDescriptor_f7ce52b48c9eea83)
}

var fileDescriptor_f7ce52b48c9eea83 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0x86, 0xe9, 0xf7, 0x39, 0x7f, 0xc7, 0x1f, 0x24, 0xa0, 0x56, 0x44, 0x1c, 0xc6, 0xcd, 0x2c,
	0x64, 0x8a, 0xcc, 0x1d, 0x38, 0x22, 0xce, 0x4e, 0x06, 0x57, 0x6e, 0x42, 0x26, 0x49, 0xa7, 0x95,
	0x34, 0x27, 0x36, 0x69, 0x6b, 0x2f, 0xdd, 0x9d, 0x24, 0x6d, 0x37, 0xae, 0x0e, 0xe7, 0x79, 0xf2,
	0x42, 0xde, 0x03, 0x67, 0x02, 0x1b, 0xad, 0x90, 0x89, 0x95, 0x29, 0xd1, 0x21, 0x19, 0x85, 0xb1,
	0xf8, 0x89, 0xe0, 0x62, 0x53, 0x4a, 0xe6, 0xe4, 0x73, 0xef, 0x77, 0xf2, 0xab, 0x92, 0xd6, 0x91,
	0x2b, 0x98, 0xa4, 0x0a, 0x1b, 0x9a, 0x8b, 0x38, 0x9a, 0x47, 0xcb, 0xd9, 0x6e, 0xec, 0xd7, 0xad,
	0x20, 0x37, 0x30, 0xe3, 0x2a, 0x97, 0xda, 0x79, 0xf5, 0x2f, 0xa8, 0x69, 0x07, 0xb6, 0xc2, 0xa7,
	0xb2, 0xaa, 0x53, 0xff, 0xbb, 0x94, 0x5f, 0xb7, 0x82, 0x3c, 0x00, 0x41, 0xad, 0x5a, 0xca, 0xb1,
	0xd8, 0xe7, 0x5a, 0x0a, 0xea, 0x79, 0x7c, 0x34, 0x8f, 0x96, 0xd3, 0xdd, 0xb9, 0x37, 0x9b, 0x5e,
	0xbc, 0x56, 0xda, 0x91, 0x3b, 0x38, 0xfe, 0xb4, 0xa8, 0x69, 0x8a, 0x65, 0xc1, 0x5c, 0x3c, 0x0a,
	0xcf, 0xc0, 0xa3, 0x97, 0x40, 0xc8, 0x2d, 0x00, 0xb7, 0xf5, 0xe0, 0xc7, 0xc1, 0xcf, 0xb8, 0xad,
	0x7b, 0x7d, 0x0f, 0xa7, 0x43, 0x5f, 0xea, 0x5a, 0x23, 0xe3, 0x49, 0xf8, 0xcc, 0xc9, 0x00, 0xdf,
	0x5b, 0x23, 0x17, 0x6b, 0xb8, 0xfc, 0x5b, 0xdd, 0x1a, 0xd4, 0x56, 0x92, 0x6b, 0x98, 0xd6, 0xa9,
	0xa5, 0x86, 0xb9, 0xac, 0x2f, 0x3f, 0xa9, 0x53, 0xfb, 0xc6, 0x5c, 0xf6, 0xf4, 0xf8, 0x91, 0x34,
	0x4d, 0xb3, 0xaa, 0xa5, 0x42, 0x9e, 0x0b, 0xf9, 0xbd, 0xe2, 0x58, 0x24, 0x07, 0x54, 0x4c, 0x1f,
	0x92, 0x0e, 0x96, 0xcc, 0x38, 0x2c, 0x13, 0x66, 0xf2, 0x24, 0xdc, 0x78, 0x3f, 0x0e, 0x63, 0xfd,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x73, 0x56, 0x39, 0x83, 0x01, 0x00, 0x00,
}
