// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hunts.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "www.velocidex.com/golang/velociraptor/actions/proto"
import _ "www.velocidex.com/golang/velociraptor/crypto/proto"
import proto2 "www.velocidex.com/golang/velociraptor/flows/proto"
import _ "www.velocidex.com/golang/velociraptor/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HuntOsCondition_OS int32

const (
	HuntOsCondition_ALL     HuntOsCondition_OS = 0
	HuntOsCondition_WINDOWS HuntOsCondition_OS = 1
	HuntOsCondition_LINUX   HuntOsCondition_OS = 2
	HuntOsCondition_OSX     HuntOsCondition_OS = 3
)

var HuntOsCondition_OS_name = map[int32]string{
	0: "ALL",
	1: "WINDOWS",
	2: "LINUX",
	3: "OSX",
}
var HuntOsCondition_OS_value = map[string]int32{
	"ALL":     0,
	"WINDOWS": 1,
	"LINUX":   2,
	"OSX":     3,
}

func (x HuntOsCondition_OS) String() string {
	return proto.EnumName(HuntOsCondition_OS_name, int32(x))
}
func (HuntOsCondition_OS) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{2, 0}
}

type Hunt_State int32

const (
	Hunt_UNSET   Hunt_State = 0
	Hunt_PAUSED  Hunt_State = 1
	Hunt_RUNNING Hunt_State = 2
	Hunt_STOPPED Hunt_State = 3
)

var Hunt_State_name = map[int32]string{
	0: "UNSET",
	1: "PAUSED",
	2: "RUNNING",
	3: "STOPPED",
}
var Hunt_State_value = map[string]int32{
	"UNSET":   0,
	"PAUSED":  1,
	"RUNNING": 2,
	"STOPPED": 3,
}

func (x Hunt_State) String() string {
	return proto.EnumName(Hunt_State_name, int32(x))
}
func (Hunt_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{4, 0}
}

type HuntInfo_State int32

const (
	HuntInfo_UNSET   HuntInfo_State = 0
	HuntInfo_PENDING HuntInfo_State = 1
	HuntInfo_RUNNING HuntInfo_State = 2
)

var HuntInfo_State_name = map[int32]string{
	0: "UNSET",
	1: "PENDING",
	2: "RUNNING",
}
var HuntInfo_State_value = map[string]int32{
	"UNSET":   0,
	"PENDING": 1,
	"RUNNING": 2,
}

func (x HuntInfo_State) String() string {
	return proto.EnumName(HuntInfo_State_name, int32(x))
}
func (HuntInfo_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{5, 0}
}

type ListHuntClientsRequest_Type int32

const (
	ListHuntClientsRequest_PENDING   ListHuntClientsRequest_Type = 0
	ListHuntClientsRequest_SCHEDULED ListHuntClientsRequest_Type = 1
	ListHuntClientsRequest_COMPLETED ListHuntClientsRequest_Type = 2
	ListHuntClientsRequest_RESULTS   ListHuntClientsRequest_Type = 3
)

var ListHuntClientsRequest_Type_name = map[int32]string{
	0: "PENDING",
	1: "SCHEDULED",
	2: "COMPLETED",
	3: "RESULTS",
}
var ListHuntClientsRequest_Type_value = map[string]int32{
	"PENDING":   0,
	"SCHEDULED": 1,
	"COMPLETED": 2,
	"RESULTS":   3,
}

func (x ListHuntClientsRequest_Type) String() string {
	return proto.EnumName(ListHuntClientsRequest_Type_name, int32(x))
}
func (ListHuntClientsRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{11, 0}
}

type HuntConditionGeneric struct {
	FlowConditionQuery       *proto1.VQLCollectorArgs `protobuf:"bytes,4,opt,name=flow_condition_query,json=flowConditionQuery,proto3" json:"flow_condition_query,omitempty"`
	ServerSideConditionQuery *proto1.VQLCollectorArgs `protobuf:"bytes,5,opt,name=server_side_condition_query,json=serverSideConditionQuery,proto3" json:"server_side_condition_query,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                 `json:"-"`
	XXX_unrecognized         []byte                   `json:"-"`
	XXX_sizecache            int32                    `json:"-"`
}

func (m *HuntConditionGeneric) Reset()         { *m = HuntConditionGeneric{} }
func (m *HuntConditionGeneric) String() string { return proto.CompactTextString(m) }
func (*HuntConditionGeneric) ProtoMessage()    {}
func (*HuntConditionGeneric) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{0}
}
func (m *HuntConditionGeneric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HuntConditionGeneric.Unmarshal(m, b)
}
func (m *HuntConditionGeneric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HuntConditionGeneric.Marshal(b, m, deterministic)
}
func (dst *HuntConditionGeneric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HuntConditionGeneric.Merge(dst, src)
}
func (m *HuntConditionGeneric) XXX_Size() int {
	return xxx_messageInfo_HuntConditionGeneric.Size(m)
}
func (m *HuntConditionGeneric) XXX_DiscardUnknown() {
	xxx_messageInfo_HuntConditionGeneric.DiscardUnknown(m)
}

var xxx_messageInfo_HuntConditionGeneric proto.InternalMessageInfo

func (m *HuntConditionGeneric) GetFlowConditionQuery() *proto1.VQLCollectorArgs {
	if m != nil {
		return m.FlowConditionQuery
	}
	return nil
}

func (m *HuntConditionGeneric) GetServerSideConditionQuery() *proto1.VQLCollectorArgs {
	if m != nil {
		return m.ServerSideConditionQuery
	}
	return nil
}

type HuntLabelCondition struct {
	Label                []string `protobuf:"bytes,1,rep,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HuntLabelCondition) Reset()         { *m = HuntLabelCondition{} }
func (m *HuntLabelCondition) String() string { return proto.CompactTextString(m) }
func (*HuntLabelCondition) ProtoMessage()    {}
func (*HuntLabelCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{1}
}
func (m *HuntLabelCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HuntLabelCondition.Unmarshal(m, b)
}
func (m *HuntLabelCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HuntLabelCondition.Marshal(b, m, deterministic)
}
func (dst *HuntLabelCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HuntLabelCondition.Merge(dst, src)
}
func (m *HuntLabelCondition) XXX_Size() int {
	return xxx_messageInfo_HuntLabelCondition.Size(m)
}
func (m *HuntLabelCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_HuntLabelCondition.DiscardUnknown(m)
}

var xxx_messageInfo_HuntLabelCondition proto.InternalMessageInfo

func (m *HuntLabelCondition) GetLabel() []string {
	if m != nil {
		return m.Label
	}
	return nil
}

type HuntOsCondition struct {
	Os                   HuntOsCondition_OS `protobuf:"varint,1,opt,name=os,proto3,enum=proto.HuntOsCondition_OS" json:"os,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *HuntOsCondition) Reset()         { *m = HuntOsCondition{} }
func (m *HuntOsCondition) String() string { return proto.CompactTextString(m) }
func (*HuntOsCondition) ProtoMessage()    {}
func (*HuntOsCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{2}
}
func (m *HuntOsCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HuntOsCondition.Unmarshal(m, b)
}
func (m *HuntOsCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HuntOsCondition.Marshal(b, m, deterministic)
}
func (dst *HuntOsCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HuntOsCondition.Merge(dst, src)
}
func (m *HuntOsCondition) XXX_Size() int {
	return xxx_messageInfo_HuntOsCondition.Size(m)
}
func (m *HuntOsCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_HuntOsCondition.DiscardUnknown(m)
}

var xxx_messageInfo_HuntOsCondition proto.InternalMessageInfo

func (m *HuntOsCondition) GetOs() HuntOsCondition_OS {
	if m != nil {
		return m.Os
	}
	return HuntOsCondition_ALL
}

type HuntCondition struct {
	// Types that are valid to be assigned to UnionField:
	//	*HuntCondition_GenericCondition
	//	*HuntCondition_Labels
	//	*HuntCondition_Os
	UnionField           isHuntCondition_UnionField `protobuf_oneof:"union_field"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *HuntCondition) Reset()         { *m = HuntCondition{} }
func (m *HuntCondition) String() string { return proto.CompactTextString(m) }
func (*HuntCondition) ProtoMessage()    {}
func (*HuntCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{3}
}
func (m *HuntCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HuntCondition.Unmarshal(m, b)
}
func (m *HuntCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HuntCondition.Marshal(b, m, deterministic)
}
func (dst *HuntCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HuntCondition.Merge(dst, src)
}
func (m *HuntCondition) XXX_Size() int {
	return xxx_messageInfo_HuntCondition.Size(m)
}
func (m *HuntCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_HuntCondition.DiscardUnknown(m)
}

var xxx_messageInfo_HuntCondition proto.InternalMessageInfo

type isHuntCondition_UnionField interface {
	isHuntCondition_UnionField()
}

type HuntCondition_GenericCondition struct {
	GenericCondition *HuntConditionGeneric `protobuf:"bytes,1,opt,name=generic_condition,json=genericCondition,proto3,oneof"`
}
type HuntCondition_Labels struct {
	Labels *HuntLabelCondition `protobuf:"bytes,2,opt,name=labels,proto3,oneof"`
}
type HuntCondition_Os struct {
	Os *HuntOsCondition `protobuf:"bytes,3,opt,name=os,proto3,oneof"`
}

func (*HuntCondition_GenericCondition) isHuntCondition_UnionField() {}
func (*HuntCondition_Labels) isHuntCondition_UnionField()           {}
func (*HuntCondition_Os) isHuntCondition_UnionField()               {}

func (m *HuntCondition) GetUnionField() isHuntCondition_UnionField {
	if m != nil {
		return m.UnionField
	}
	return nil
}

func (m *HuntCondition) GetGenericCondition() *HuntConditionGeneric {
	if x, ok := m.GetUnionField().(*HuntCondition_GenericCondition); ok {
		return x.GenericCondition
	}
	return nil
}

func (m *HuntCondition) GetLabels() *HuntLabelCondition {
	if x, ok := m.GetUnionField().(*HuntCondition_Labels); ok {
		return x.Labels
	}
	return nil
}

func (m *HuntCondition) GetOs() *HuntOsCondition {
	if x, ok := m.GetUnionField().(*HuntCondition_Os); ok {
		return x.Os
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*HuntCondition) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _HuntCondition_OneofMarshaler, _HuntCondition_OneofUnmarshaler, _HuntCondition_OneofSizer, []interface{}{
		(*HuntCondition_GenericCondition)(nil),
		(*HuntCondition_Labels)(nil),
		(*HuntCondition_Os)(nil),
	}
}

func _HuntCondition_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*HuntCondition)
	// union_field
	switch x := m.UnionField.(type) {
	case *HuntCondition_GenericCondition:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GenericCondition); err != nil {
			return err
		}
	case *HuntCondition_Labels:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Labels); err != nil {
			return err
		}
	case *HuntCondition_Os:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Os); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("HuntCondition.UnionField has unexpected type %T", x)
	}
	return nil
}

func _HuntCondition_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*HuntCondition)
	switch tag {
	case 1: // union_field.generic_condition
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HuntConditionGeneric)
		err := b.DecodeMessage(msg)
		m.UnionField = &HuntCondition_GenericCondition{msg}
		return true, err
	case 2: // union_field.labels
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HuntLabelCondition)
		err := b.DecodeMessage(msg)
		m.UnionField = &HuntCondition_Labels{msg}
		return true, err
	case 3: // union_field.os
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HuntOsCondition)
		err := b.DecodeMessage(msg)
		m.UnionField = &HuntCondition_Os{msg}
		return true, err
	default:
		return false, nil
	}
}

func _HuntCondition_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*HuntCondition)
	// union_field
	switch x := m.UnionField.(type) {
	case *HuntCondition_GenericCondition:
		s := proto.Size(x.GenericCondition)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *HuntCondition_Labels:
		s := proto.Size(x.Labels)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *HuntCondition_Os:
		s := proto.Size(x.Os)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Hunt struct {
	HuntId                  string                 `protobuf:"bytes,1,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	CreateTime              uint64                 `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Expires                 uint64                 `protobuf:"varint,10,opt,name=expires,proto3" json:"expires,omitempty"`
	HuntDescription         string                 `protobuf:"bytes,11,opt,name=hunt_description,json=huntDescription,proto3" json:"hunt_description,omitempty"`
	StartRequest            *proto2.FlowRunnerArgs `protobuf:"bytes,3,opt,name=start_request,json=startRequest,proto3" json:"start_request,omitempty"`
	Condition               *HuntCondition         `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	ClientLimit             uint64                 `protobuf:"varint,6,opt,name=client_limit,json=clientLimit,proto3" json:"client_limit,omitempty"`
	ClientRate              uint64                 `protobuf:"varint,7,opt,name=client_rate,json=clientRate,proto3" json:"client_rate,omitempty"`
	TotalClientsScheduled   uint64                 `protobuf:"varint,9,opt,name=total_clients_scheduled,json=totalClientsScheduled,proto3" json:"total_clients_scheduled,omitempty"`
	TotalClientsWithResults uint64                 `protobuf:"varint,14,opt,name=total_clients_with_results,json=totalClientsWithResults,proto3" json:"total_clients_with_results,omitempty"`
	TotalClientsWithErrors  uint64                 `protobuf:"varint,15,opt,name=total_clients_with_errors,json=totalClientsWithErrors,proto3" json:"total_clients_with_errors,omitempty"`
	// The following fields are used to calculate the client
	// recruitment rate when the hunt is paused.
	LastUnpauseTime          uint64     `protobuf:"varint,12,opt,name=last_unpause_time,json=lastUnpauseTime,proto3" json:"last_unpause_time,omitempty"`
	TotalClientsWhenUnpaused uint64     `protobuf:"varint,13,opt,name=total_clients_when_unpaused,json=totalClientsWhenUnpaused,proto3" json:"total_clients_when_unpaused,omitempty"`
	State                    Hunt_State `protobuf:"varint,8,opt,name=state,proto3,enum=proto.Hunt_State" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}   `json:"-"`
	XXX_unrecognized         []byte     `json:"-"`
	XXX_sizecache            int32      `json:"-"`
}

func (m *Hunt) Reset()         { *m = Hunt{} }
func (m *Hunt) String() string { return proto.CompactTextString(m) }
func (*Hunt) ProtoMessage()    {}
func (*Hunt) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{4}
}
func (m *Hunt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hunt.Unmarshal(m, b)
}
func (m *Hunt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hunt.Marshal(b, m, deterministic)
}
func (dst *Hunt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hunt.Merge(dst, src)
}
func (m *Hunt) XXX_Size() int {
	return xxx_messageInfo_Hunt.Size(m)
}
func (m *Hunt) XXX_DiscardUnknown() {
	xxx_messageInfo_Hunt.DiscardUnknown(m)
}

var xxx_messageInfo_Hunt proto.InternalMessageInfo

func (m *Hunt) GetHuntId() string {
	if m != nil {
		return m.HuntId
	}
	return ""
}

func (m *Hunt) GetCreateTime() uint64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Hunt) GetExpires() uint64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *Hunt) GetHuntDescription() string {
	if m != nil {
		return m.HuntDescription
	}
	return ""
}

func (m *Hunt) GetStartRequest() *proto2.FlowRunnerArgs {
	if m != nil {
		return m.StartRequest
	}
	return nil
}

func (m *Hunt) GetCondition() *HuntCondition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *Hunt) GetClientLimit() uint64 {
	if m != nil {
		return m.ClientLimit
	}
	return 0
}

func (m *Hunt) GetClientRate() uint64 {
	if m != nil {
		return m.ClientRate
	}
	return 0
}

func (m *Hunt) GetTotalClientsScheduled() uint64 {
	if m != nil {
		return m.TotalClientsScheduled
	}
	return 0
}

func (m *Hunt) GetTotalClientsWithResults() uint64 {
	if m != nil {
		return m.TotalClientsWithResults
	}
	return 0
}

func (m *Hunt) GetTotalClientsWithErrors() uint64 {
	if m != nil {
		return m.TotalClientsWithErrors
	}
	return 0
}

func (m *Hunt) GetLastUnpauseTime() uint64 {
	if m != nil {
		return m.LastUnpauseTime
	}
	return 0
}

func (m *Hunt) GetTotalClientsWhenUnpaused() uint64 {
	if m != nil {
		return m.TotalClientsWhenUnpaused
	}
	return 0
}

func (m *Hunt) GetState() Hunt_State {
	if m != nil {
		return m.State
	}
	return Hunt_UNSET
}

type HuntInfo struct {
	HuntId               string                 `protobuf:"bytes,1,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	ScheduledTime        uint64                 `protobuf:"varint,2,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	ClientId             string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlowId               string                 `protobuf:"bytes,5,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	StartRequest         *proto2.FlowRunnerArgs `protobuf:"bytes,4,opt,name=start_request,json=startRequest,proto3" json:"start_request,omitempty"`
	State                HuntInfo_State         `protobuf:"varint,8,opt,name=state,proto3,enum=proto.HuntInfo_State" json:"state,omitempty"`
	Result               *proto2.FlowContext    `protobuf:"bytes,9,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *HuntInfo) Reset()         { *m = HuntInfo{} }
func (m *HuntInfo) String() string { return proto.CompactTextString(m) }
func (*HuntInfo) ProtoMessage()    {}
func (*HuntInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{5}
}
func (m *HuntInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HuntInfo.Unmarshal(m, b)
}
func (m *HuntInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HuntInfo.Marshal(b, m, deterministic)
}
func (dst *HuntInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HuntInfo.Merge(dst, src)
}
func (m *HuntInfo) XXX_Size() int {
	return xxx_messageInfo_HuntInfo.Size(m)
}
func (m *HuntInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HuntInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HuntInfo proto.InternalMessageInfo

func (m *HuntInfo) GetHuntId() string {
	if m != nil {
		return m.HuntId
	}
	return ""
}

func (m *HuntInfo) GetScheduledTime() uint64 {
	if m != nil {
		return m.ScheduledTime
	}
	return 0
}

func (m *HuntInfo) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *HuntInfo) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

func (m *HuntInfo) GetStartRequest() *proto2.FlowRunnerArgs {
	if m != nil {
		return m.StartRequest
	}
	return nil
}

func (m *HuntInfo) GetState() HuntInfo_State {
	if m != nil {
		return m.State
	}
	return HuntInfo_UNSET
}

func (m *HuntInfo) GetResult() *proto2.FlowContext {
	if m != nil {
		return m.Result
	}
	return nil
}

type ListHuntsRequest struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHuntsRequest) Reset()         { *m = ListHuntsRequest{} }
func (m *ListHuntsRequest) String() string { return proto.CompactTextString(m) }
func (*ListHuntsRequest) ProtoMessage()    {}
func (*ListHuntsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{6}
}
func (m *ListHuntsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHuntsRequest.Unmarshal(m, b)
}
func (m *ListHuntsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHuntsRequest.Marshal(b, m, deterministic)
}
func (dst *ListHuntsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHuntsRequest.Merge(dst, src)
}
func (m *ListHuntsRequest) XXX_Size() int {
	return xxx_messageInfo_ListHuntsRequest.Size(m)
}
func (m *ListHuntsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHuntsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHuntsRequest proto.InternalMessageInfo

func (m *ListHuntsRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListHuntsRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type GetHuntRequest struct {
	HuntId               string   `protobuf:"bytes,1,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHuntRequest) Reset()         { *m = GetHuntRequest{} }
func (m *GetHuntRequest) String() string { return proto.CompactTextString(m) }
func (*GetHuntRequest) ProtoMessage()    {}
func (*GetHuntRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{7}
}
func (m *GetHuntRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHuntRequest.Unmarshal(m, b)
}
func (m *GetHuntRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHuntRequest.Marshal(b, m, deterministic)
}
func (dst *GetHuntRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHuntRequest.Merge(dst, src)
}
func (m *GetHuntRequest) XXX_Size() int {
	return xxx_messageInfo_GetHuntRequest.Size(m)
}
func (m *GetHuntRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHuntRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHuntRequest proto.InternalMessageInfo

func (m *GetHuntRequest) GetHuntId() string {
	if m != nil {
		return m.HuntId
	}
	return ""
}

type GetHuntResultsRequest struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                uint64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	HuntId               string   `protobuf:"bytes,3,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHuntResultsRequest) Reset()         { *m = GetHuntResultsRequest{} }
func (m *GetHuntResultsRequest) String() string { return proto.CompactTextString(m) }
func (*GetHuntResultsRequest) ProtoMessage()    {}
func (*GetHuntResultsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{8}
}
func (m *GetHuntResultsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHuntResultsRequest.Unmarshal(m, b)
}
func (m *GetHuntResultsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHuntResultsRequest.Marshal(b, m, deterministic)
}
func (dst *GetHuntResultsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHuntResultsRequest.Merge(dst, src)
}
func (m *GetHuntResultsRequest) XXX_Size() int {
	return xxx_messageInfo_GetHuntResultsRequest.Size(m)
}
func (m *GetHuntResultsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHuntResultsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHuntResultsRequest proto.InternalMessageInfo

func (m *GetHuntResultsRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *GetHuntResultsRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GetHuntResultsRequest) GetHuntId() string {
	if m != nil {
		return m.HuntId
	}
	return ""
}

type HuntResults struct {
	Items                []*HuntInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *HuntResults) Reset()         { *m = HuntResults{} }
func (m *HuntResults) String() string { return proto.CompactTextString(m) }
func (*HuntResults) ProtoMessage()    {}
func (*HuntResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{9}
}
func (m *HuntResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HuntResults.Unmarshal(m, b)
}
func (m *HuntResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HuntResults.Marshal(b, m, deterministic)
}
func (dst *HuntResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HuntResults.Merge(dst, src)
}
func (m *HuntResults) XXX_Size() int {
	return xxx_messageInfo_HuntResults.Size(m)
}
func (m *HuntResults) XXX_DiscardUnknown() {
	xxx_messageInfo_HuntResults.DiscardUnknown(m)
}

var xxx_messageInfo_HuntResults proto.InternalMessageInfo

func (m *HuntResults) GetItems() []*HuntInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListHuntsResponse struct {
	Items                []*Hunt  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListHuntsResponse) Reset()         { *m = ListHuntsResponse{} }
func (m *ListHuntsResponse) String() string { return proto.CompactTextString(m) }
func (*ListHuntsResponse) ProtoMessage()    {}
func (*ListHuntsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{10}
}
func (m *ListHuntsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHuntsResponse.Unmarshal(m, b)
}
func (m *ListHuntsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHuntsResponse.Marshal(b, m, deterministic)
}
func (dst *ListHuntsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHuntsResponse.Merge(dst, src)
}
func (m *ListHuntsResponse) XXX_Size() int {
	return xxx_messageInfo_ListHuntsResponse.Size(m)
}
func (m *ListHuntsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHuntsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListHuntsResponse proto.InternalMessageInfo

func (m *ListHuntsResponse) GetItems() []*Hunt {
	if m != nil {
		return m.Items
	}
	return nil
}

type ListHuntClientsRequest struct {
	Type                 ListHuntClientsRequest_Type `protobuf:"varint,1,opt,name=type,proto3,enum=proto.ListHuntClientsRequest_Type" json:"type,omitempty"`
	HuntId               string                      `protobuf:"bytes,2,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	Offset               uint64                      `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                uint64                      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListHuntClientsRequest) Reset()         { *m = ListHuntClientsRequest{} }
func (m *ListHuntClientsRequest) String() string { return proto.CompactTextString(m) }
func (*ListHuntClientsRequest) ProtoMessage()    {}
func (*ListHuntClientsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_hunts_71df82c3dc889e43, []int{11}
}
func (m *ListHuntClientsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListHuntClientsRequest.Unmarshal(m, b)
}
func (m *ListHuntClientsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListHuntClientsRequest.Marshal(b, m, deterministic)
}
func (dst *ListHuntClientsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListHuntClientsRequest.Merge(dst, src)
}
func (m *ListHuntClientsRequest) XXX_Size() int {
	return xxx_messageInfo_ListHuntClientsRequest.Size(m)
}
func (m *ListHuntClientsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListHuntClientsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListHuntClientsRequest proto.InternalMessageInfo

func (m *ListHuntClientsRequest) GetType() ListHuntClientsRequest_Type {
	if m != nil {
		return m.Type
	}
	return ListHuntClientsRequest_PENDING
}

func (m *ListHuntClientsRequest) GetHuntId() string {
	if m != nil {
		return m.HuntId
	}
	return ""
}

func (m *ListHuntClientsRequest) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListHuntClientsRequest) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*HuntConditionGeneric)(nil), "proto.HuntConditionGeneric")
	proto.RegisterType((*HuntLabelCondition)(nil), "proto.HuntLabelCondition")
	proto.RegisterType((*HuntOsCondition)(nil), "proto.HuntOsCondition")
	proto.RegisterType((*HuntCondition)(nil), "proto.HuntCondition")
	proto.RegisterType((*Hunt)(nil), "proto.Hunt")
	proto.RegisterType((*HuntInfo)(nil), "proto.HuntInfo")
	proto.RegisterType((*ListHuntsRequest)(nil), "proto.ListHuntsRequest")
	proto.RegisterType((*GetHuntRequest)(nil), "proto.GetHuntRequest")
	proto.RegisterType((*GetHuntResultsRequest)(nil), "proto.GetHuntResultsRequest")
	proto.RegisterType((*HuntResults)(nil), "proto.HuntResults")
	proto.RegisterType((*ListHuntsResponse)(nil), "proto.ListHuntsResponse")
	proto.RegisterType((*ListHuntClientsRequest)(nil), "proto.ListHuntClientsRequest")
	proto.RegisterEnum("proto.HuntOsCondition_OS", HuntOsCondition_OS_name, HuntOsCondition_OS_value)
	proto.RegisterEnum("proto.Hunt_State", Hunt_State_name, Hunt_State_value)
	proto.RegisterEnum("proto.HuntInfo_State", HuntInfo_State_name, HuntInfo_State_value)
	proto.RegisterEnum("proto.ListHuntClientsRequest_Type", ListHuntClientsRequest_Type_name, ListHuntClientsRequest_Type_value)
}

func init() { proto.RegisterFile("hunts.proto", fileDescriptor_hunts_71df82c3dc889e43) }

var fileDescriptor_hunts_71df82c3dc889e43 = []byte{
	// 2124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0x4b, 0x8c, 0x1b, 0x49,
	0x19, 0x9e, 0xf6, 0x78, 0xc6, 0x71, 0x39, 0x33, 0xe3, 0x29, 0x65, 0x12, 0xc7, 0x01, 0xa9, 0x68,
	0x12, 0x65, 0x92, 0xcc, 0x76, 0xb2, 0xb3, 0x28, 0x11, 0x51, 0x42, 0x18, 0x7b, 0x9c, 0xcc, 0x80,
	0x77, 0x1e, 0x6d, 0x4f, 0x66, 0x61, 0xb5, 0x78, 0x7b, 0xba, 0xcb, 0xe3, 0x42, 0xed, 0x2a, 0xa7,
	0xaa, 0x3a, 0x8e, 0x15, 0x85, 0x97, 0x04, 0xac, 0x38, 0x00, 0x12, 0xe2, 0xce, 0x91, 0x13, 0x12,
	0x17, 0xa4, 0x3d, 0x70, 0xe3, 0x80, 0xb4, 0x07, 0xc4, 0x95, 0x23, 0x1c, 0x90, 0xb8, 0x71, 0xe7,
	0x80, 0xea, 0xaf, 0xf6, 0x33, 0x93, 0x88, 0xe5, 0xe4, 0xee, 0xaa, 0xff, 0xf1, 0xd5, 0x5f, 0x5f,
	0x7d, 0xf5, 0xb7, 0x51, 0xa1, 0x93, 0x70, 0xad, 0xbc, 0x9e, 0x14, 0x5a, 0xe0, 0x05, 0xf8, 0x29,
	0xdf, 0xef, 0xf7, 0xfb, 0xde, 0x73, 0x1a, 0x8b, 0x90, 0x45, 0xf4, 0x85, 0x17, 0x8a, 0xee, 0xed,
	0x53, 0x11, 0x07, 0xfc, 0xf4, 0xb6, 0x1d, 0x94, 0x41, 0x4f, 0x0b, 0x79, 0x1b, 0x8c, 0x6f, 0x2b,
	0xda, 0x0d, 0xb8, 0x66, 0xa1, 0x0d, 0x51, 0x7e, 0xf8, 0xbf, 0xf9, 0xb6, 0x63, 0xd1, 0x57, 0x69,
	0x04, 0x78, 0xfe, 0x7c, 0xee, 0xa1, 0x1c, 0xf4, 0xb4, 0x48, 0xfd, 0xbf, 0x2b, 0x4e, 0x3e, 0xa7,
	0x7b, 0x10, 0x6a, 0x26, 0xf8, 0x30, 0xff, 0xf3, 0x67, 0xb1, 0x75, 0x77, 0x7f, 0x9d, 0x45, 0x17,
	0x76, 0x12, 0xae, 0xab, 0x82, 0x47, 0xcc, 0x98, 0x3c, 0xa1, 0x9c, 0x4a, 0x16, 0xe2, 0xbf, 0x3a,
	0xe8, 0x82, 0x81, 0xd9, 0x0a, 0x87, 0x33, 0xad, 0x67, 0x09, 0x95, 0x83, 0x52, 0x96, 0x38, 0xeb,
	0x85, 0xcd, 0x4b, 0xd6, 0xdf, 0x7b, 0x7a, 0x58, 0xaf, 0x8a, 0x38, 0xa6, 0xa1, 0x16, 0x72, 0x4b,
	0x9e, 0xaa, 0xca, 0x8f, 0x9d, 0xbf, 0xff, 0xe7, 0x1f, 0x7f, 0x72, 0xbe, 0x8f, 0xdb, 0x5b, 0xe4,
	0xe9, 0x61, 0x9d, 0x80, 0x13, 0xd1, 0x82, 0xc8, 0x84, 0x13, 0xc6, 0x89, 0x90, 0x11, 0x95, 0xe6,
	0x3d, 0xb4, 0x6e, 0x84, 0xf1, 0xb6, 0x90, 0xdd, 0xc0, 0x64, 0x20, 0x6d, 0x21, 0x49, 0x44, 0x35,
	0x95, 0x5d, 0xc6, 0x19, 0x3f, 0x25, 0xac, 0x4d, 0x74, 0x87, 0x12, 0xb3, 0x61, 0x24, 0xe8, 0xf5,
	0x62, 0x46, 0x95, 0x71, 0xd5, 0x1d, 0xa6, 0x48, 0x18, 0x33, 0xca, 0xb5, 0xe7, 0xae, 0x55, 0xe1,
	0x81, 0x34, 0x58, 0x44, 0xc9, 0x68, 0x19, 0x3e, 0x36, 0xe0, 0x47, 0xaf, 0x87, 0x06, 0x05, 0xfe,
	0x6d, 0x06, 0x5d, 0x51, 0x54, 0x3e, 0xa7, 0xb2, 0xa5, 0x58, 0x44, 0x5f, 0x5b, 0xda, 0xc2, 0xdb,
	0x97, 0xf6, 0x17, 0xbb, 0xb4, 0x3f, 0x3b, 0xf8, 0x77, 0xce, 0xe4, 0xe2, 0xfa, 0x1d, 0x16, 0x76,
	0xcc, 0xfa, 0x14, 0xb1, 0xd1, 0x89, 0x89, 0x4e, 0x04, 0x07, 0xf0, 0x92, 0xaa, 0x24, 0xd6, 0x8a,
	0x08, 0xbb, 0x96, 0xb3, 0x6a, 0xea, 0x91, 0xdd, 0x36, 0x09, 0xf8, 0x80, 0x48, 0xd1, 0x57, 0x24,
	0x90, 0xc6, 0x49, 0x27, 0x92, 0xd3, 0xc8, 0xb8, 0xd8, 0x30, 0x23, 0x17, 0xc2, 0x14, 0x89, 0x28,
	0xed, 0xd2, 0x88, 0xb4, 0x93, 0xb8, 0xcd, 0xe2, 0x98, 0x46, 0x24, 0xe0, 0xd1, 0xb8, 0x52, 0x7d,
	0x16, 0xc7, 0xe4, 0x84, 0x12, 0x15, 0x76, 0x68, 0x94, 0xc4, 0x34, 0xf2, 0xdc, 0xb5, 0x86, 0x05,
	0x36, 0x53, 0xa4, 0x92, 0xc5, 0x6b, 0x46, 0xa7, 0x4b, 0xe5, 0xde, 0x44, 0xd8, 0xd0, 0xa2, 0x1e,
	0x9c, 0xd0, 0x78, 0x34, 0x85, 0x2f, 0xa0, 0x85, 0xd8, 0x8c, 0x94, 0x1c, 0x32, 0xbf, 0x9e, 0xf7,
	0xed, 0x8b, 0x1b, 0xa3, 0x15, 0x63, 0xbb, 0xaf, 0xc6, 0x86, 0x37, 0x50, 0x46, 0xa8, 0x92, 0x43,
	0x9c, 0xf5, 0xe5, 0xcd, 0xcb, 0x69, 0x3d, 0x67, 0x6c, 0xbc, 0xfd, 0x86, 0x9f, 0x11, 0xca, 0xf5,
	0x50, 0x66, 0xbf, 0x81, 0x73, 0x68, 0x7e, 0xab, 0x5e, 0x2f, 0xce, 0xe1, 0x02, 0xca, 0x1d, 0xef,
	0xee, 0x6d, 0xef, 0x1f, 0x37, 0x8a, 0x0e, 0xce, 0xa3, 0x85, 0xfa, 0xee, 0xde, 0xd1, 0x07, 0xc5,
	0x8c, 0x31, 0xd8, 0x6f, 0x7c, 0x50, 0x9c, 0x77, 0xff, 0x9d, 0x45, 0x4b, 0x53, 0x8c, 0xc5, 0x3f,
	0x9b, 0x47, 0xab, 0xa7, 0x96, 0xb6, 0xe3, 0xca, 0x42, 0xf2, 0xc2, 0xe6, 0x95, 0x89, 0xe4, 0xb3,
	0x1c, 0xaf, 0xfc, 0x31, 0x03, 0x1b, 0xfa, 0x87, 0x8c, 0xbb, 0x9a, 0x0e, 0x8d, 0x6b, 0xb3, 0xf9,
	0x9b, 0xcc, 0x4b, 0xf7, 0xac, 0xcd, 0x72, 0xef, 0x93, 0x97, 0xee, 0x61, 0xfa, 0xf4, 0xe1, 0x4b,
	0x77, 0x2f, 0xe8, 0x52, 0xf7, 0x3e, 0x71, 0x53, 0xae, 0x90, 0x88, 0xb6, 0x83, 0x24, 0xd6, 0x29,
	0x3f, 0x81, 0xde, 0xee, 0x06, 0x71, 0x9f, 0x1e, 0xd6, 0x8d, 0x55, 0xa3, 0x56, 0xaf, 0x55, 0x9b,
	0x64, 0xbf, 0xb1, 0x41, 0xb6, 0x64, 0xd8, 0x61, 0x9a, 0x86, 0x3a, 0x91, 0x74, 0x83, 0x3c, 0x7e,
	0x16, 0xf1, 0x0d, 0x72, 0x10, 0x07, 0xda, 0x1c, 0x87, 0x0d, 0xb3, 0xdf, 0x6d, 0x76, 0xea, 0x59,
	0x72, 0xb7, 0xa0, 0xd0, 0x8a, 0xb4, 0xa5, 0xe8, 0x42, 0xc4, 0xf5, 0x1b, 0xee, 0xab, 0x8f, 0x5e,
	0x6d, 0x10, 0xf7, 0x2d, 0x74, 0x7e, 0x13, 0xd0, 0x06, 0x05, 0x9c, 0x29, 0xbe, 0x93, 0xc1, 0x1b,
	0x20, 0xde, 0xb4, 0xd9, 0x80, 0x92, 0xfd, 0x0e, 0x95, 0x14, 0x20, 0x92, 0x87, 0xdf, 0x23, 0xd7,
	0xbd, 0xeb, 0x26, 0xfb, 0xab, 0x9d, 0x39, 0xbf, 0x98, 0xd6, 0x7d, 0xbc, 0x19, 0xdf, 0x44, 0x8b,
	0x16, 0x6c, 0x29, 0x03, 0x1b, 0x30, 0xb9, 0xfb, 0xd3, 0x6c, 0xaa, 0x5c, 0x84, 0xea, 0x17, 0xdd,
	0xe5, 0xf7, 0x03, 0x1d, 0x76, 0x0c, 0x12, 0xf0, 0xdc, 0x99, 0xf3, 0xd3, 0x10, 0xb8, 0x02, 0x34,
	0x9a, 0x87, 0x40, 0x17, 0xcf, 0xa6, 0x51, 0xa5, 0x04, 0x51, 0xb0, 0x5b, 0xdc, 0xef, 0x51, 0x19,
	0x68, 0x23, 0x1b, 0x8d, 0x81, 0xd2, 0xb4, 0xbb, 0x33, 0x67, 0xf8, 0x75, 0xff, 0xbd, 0xbf, 0x99,
	0xf9, 0x77, 0xd0, 0xad, 0xe6, 0xd4, 0x29, 0xd2, 0x82, 0x74, 0x21, 0x6d, 0x47, 0x28, 0xad, 0x40,
	0x79, 0x40, 0x56, 0xcc, 0x09, 0xf2, 0x2a, 0x4b, 0xa8, 0x90, 0x70, 0x53, 0xc9, 0x36, 0xa3, 0x71,
	0xe4, 0xfe, 0x6a, 0x09, 0x65, 0x4d, 0x5e, 0xbc, 0x8e, 0x72, 0xc6, 0xa0, 0xc5, 0x22, 0xe0, 0x57,
	0xbe, 0xb2, 0x02, 0xd9, 0xf3, 0x6e, 0xce, 0x4c, 0x93, 0xdd, 0x6d, 0x7f, 0xd1, 0xcc, 0xef, 0x46,
	0xf8, 0x63, 0x54, 0x08, 0x25, 0x0d, 0x34, 0x6d, 0x69, 0xd6, 0xa5, 0x50, 0x8c, 0x6c, 0xe5, 0x11,
	0x58, 0x7f, 0x15, 0x15, 0xfc, 0xed, 0xc7, 0xdb, 0x81, 0xa6, 0x66, 0x0a, 0x5f, 0x39, 0xb6, 0x67,
	0x3c, 0x4d, 0x4e, 0xfa, 0x81, 0x22, 0xd6, 0x35, 0xf2, 0xdc, 0xa5, 0xaa, 0x79, 0x32, 0x80, 0x9b,
	0xac, 0x4b, 0x7d, 0x64, 0x27, 0xcc, 0x33, 0x3e, 0x46, 0x39, 0xfa, 0xa2, 0xc7, 0x24, 0x55, 0x25,
	0x04, 0xd1, 0x1f, 0x42, 0xf4, 0x7b, 0x67, 0x45, 0x8f, 0x84, 0x51, 0xce, 0x51, 0x0a, 0xeb, 0xf7,
	0xc8, 0x2d, 0xd4, 0xcc, 0xc3, 0xc0, 0xc6, 0x1e, 0x46, 0xc3, 0x35, 0x54, 0x84, 0x45, 0x46, 0x54,
	0x85, 0x92, 0xf5, 0xe0, 0x34, 0x15, 0x60, 0xb5, 0x65, 0xc8, 0x70, 0x01, 0x83, 0x36, 0x5c, 0x37,
	0x3a, 0x34, 0xb2, 0xf0, 0x57, 0x8c, 0xcf, 0xf6, 0x78, 0x00, 0x7f, 0xe2, 0xa0, 0x25, 0xa5, 0x03,
	0xa9, 0x5b, 0x92, 0x3e, 0x4b, 0xa8, 0xd2, 0xe9, 0x46, 0xae, 0xa5, 0x1b, 0xf9, 0x38, 0x16, 0x7d,
	0x3f, 0xe1, 0x9c, 0x5a, 0x75, 0xad, 0x43, 0xec, 0xc7, 0xf8, 0x5e, 0x3d, 0x48, 0x78, 0xd8, 0xb1,
	0x68, 0xcd, 0x01, 0x1c, 0x0a, 0xe9, 0xf0, 0x40, 0xb5, 0x5f, 0xd7, 0x43, 0x2d, 0x13, 0xea, 0x16,
	0x52, 0x47, 0x88, 0x7b, 0x1e, 0x32, 0xfb, 0x36, 0x31, 0xfe, 0xb9, 0x83, 0xf2, 0x63, 0x65, 0xb0,
	0x37, 0xd8, 0x85, 0xb3, 0x94, 0xa1, 0xf2, 0x6d, 0x40, 0xd1, 0xc4, 0x95, 0x19, 0xb6, 0x74, 0x02,
	0x4d, 0xba, 0x89, 0xd2, 0xa0, 0xab, 0x81, 0x66, 0xaa, 0xcd, 0x8c, 0x00, 0x03, 0x6b, 0x52, 0xd9,
	0xd5, 0x62, 0x46, 0x74, 0x97, 0x81, 0x13, 0x63, 0xb5, 0x1d, 0x43, 0xc0, 0xdf, 0x42, 0xe7, 0xc3,
	0xf4, 0x64, 0xb3, 0x2e, 0xd3, 0xa5, 0x45, 0xd8, 0xc0, 0xbb, 0x90, 0xfc, 0x0e, 0xf6, 0x9a, 0x42,
	0x07, 0x31, 0xe1, 0x49, 0xf7, 0x84, 0x4a, 0x73, 0x71, 0x58, 0xdb, 0xc9, 0x1d, 0x04, 0x8d, 0x37,
	0x57, 0xaa, 0xe0, 0x9e, 0x5f, 0xb0, 0xf3, 0x75, 0x13, 0x0a, 0x7f, 0x84, 0xd2, 0xd7, 0x96, 0x0c,
	0x34, 0x2d, 0xe5, 0x20, 0xf2, 0x03, 0x88, 0x7c, 0x17, 0xdf, 0xb1, 0x91, 0x87, 0xf1, 0x7a, 0x54,
	0x92, 0x2e, 0xe3, 0x89, 0xa6, 0x76, 0x85, 0xa3, 0xa8, 0xc3, 0x45, 0x79, 0x9b, 0x99, 0xcd, 0x3b,
	0x3e, 0xb2, 0xf6, 0x7e, 0xa0, 0x29, 0xfe, 0x85, 0x83, 0x2e, 0x69, 0x13, 0xa4, 0x95, 0x06, 0x69,
	0x8d, 0x56, 0x5c, 0xca, 0x43, 0xae, 0x63, 0xc8, 0x75, 0x88, 0xbf, 0x66, 0x4a, 0xa8, 0xdf, 0xb0,
	0x92, 0x30, 0x91, 0x92, 0x72, 0x1d, 0x0f, 0xc6, 0x05, 0x9b, 0x39, 0x83, 0xee, 0x8a, 0xc5, 0xda,
	0x18, 0xce, 0xfb, 0x6b, 0x10, 0xcc, 0x2a, 0xa2, 0x1a, 0x0d, 0xe3, 0x9f, 0x38, 0xa8, 0x3c, 0x8d,
	0xa8, 0xcf, 0x74, 0xa7, 0x95, 0xde, 0xbb, 0xa5, 0x65, 0x00, 0xb5, 0x0b, 0xa0, 0xaa, 0xf8, 0xda,
	0x9b, 0x4a, 0x6b, 0x7c, 0x86, 0x77, 0xb5, 0xe7, 0x96, 0xad, 0x59, 0x75, 0x72, 0xd2, 0xb7, 0x93,
	0xfe, 0xa5, 0x49, 0x18, 0xc7, 0x4c, 0x77, 0xd2, 0x09, 0xfc, 0x23, 0x07, 0x5d, 0x3e, 0x03, 0x08,
	0x95, 0x52, 0x48, 0x55, 0x5a, 0x01, 0x1c, 0x4f, 0x00, 0xc7, 0x16, 0xbe, 0xfa, 0x56, 0x1c, 0xd6,
	0xc5, 0x73, 0x2f, 0x9f, 0x01, 0xa3, 0x06, 0x73, 0xfe, 0xc5, 0x59, 0x14, 0x76, 0x1c, 0xff, 0xc0,
	0x41, 0xab, 0x71, 0xa0, 0x74, 0x2b, 0xe1, 0xbd, 0x20, 0x51, 0xa9, 0xfc, 0x9c, 0x87, 0xe4, 0x4d,
	0x48, 0xbe, 0x37, 0x2d, 0x10, 0x0f, 0x60, 0x9b, 0x58, 0x97, 0x1a, 0x95, 0xe7, 0x13, 0x5d, 0x44,
	0xa0, 0x88, 0x09, 0x44, 0x20, 0x4c, 0x44, 0x52, 0xaa, 0x87, 0x43, 0x3d, 0x32, 0x2e, 0x5e, 0xd9,
	0xc9, 0xf8, 0x2b, 0xc6, 0xea, 0xc8, 0x66, 0x03, 0x61, 0xfa, 0xc4, 0x41, 0x57, 0x66, 0xea, 0xd0,
	0xa1, 0x7c, 0x08, 0x28, 0x2a, 0x2d, 0x4d, 0xed, 0xc8, 0x5b, 0x69, 0xa2, 0xc2, 0x8e, 0xe5, 0xc6,
	0xeb, 0xd8, 0x6c, 0x30, 0x40, 0x50, 0x9a, 0xaa, 0x45, 0x87, 0xf2, 0x14, 0x4d, 0x84, 0xaf, 0xa3,
	0x05, 0xa5, 0xcd, 0x31, 0x38, 0x07, 0xad, 0xc8, 0xea, 0xc4, 0x99, 0xf7, 0x1a, 0x66, 0xc2, 0xb7,
	0xf3, 0xee, 0xef, 0x1d, 0xb4, 0x00, 0x03, 0xa6, 0xe7, 0x38, 0xda, 0x6b, 0xd4, 0x9a, 0xc5, 0x39,
	0xbc, 0x83, 0x16, 0x0f, 0xb6, 0x8e, 0x1a, 0xb5, 0xed, 0xa2, 0x53, 0x7e, 0xf0, 0xaf, 0x4f, 0x3f,
	0xfb, 0xd4, 0xb9, 0xbb, 0x33, 0x3a, 0x7c, 0x5c, 0xe8, 0x11, 0x77, 0x09, 0xa7, 0xfd, 0x11, 0xe6,
	0x93, 0x44, 0x93, 0x30, 0xe0, 0x20, 0x06, 0x46, 0x84, 0x68, 0xe4, 0xe1, 0x77, 0x50, 0xce, 0x3f,
	0xda, 0xdb, 0xdb, 0xdd, 0x7b, 0x52, 0xcc, 0x94, 0x09, 0x84, 0x2a, 0x43, 0x28, 0xa6, 0xcc, 0x79,
	0x83, 0x66, 0xd7, 0xf4, 0x70, 0x92, 0x06, 0xd1, 0xc0, 0xc3, 0x57, 0x51, 0xae, 0xd1, 0xdc, 0x3f,
	0x38, 0xa8, 0x6d, 0x17, 0xe7, 0xcb, 0x97, 0xc0, 0x7c, 0x15, 0xcc, 0x3b, 0x81, 0x4a, 0xc5, 0x3b,
	0xf2, 0xdc, 0x7f, 0x66, 0xd1, 0x39, 0x33, 0xba, 0xcb, 0xdb, 0x02, 0x5f, 0x9a, 0xb9, 0x99, 0x46,
	0x17, 0xd1, 0x35, 0xb4, 0x3c, 0x3a, 0x62, 0x13, 0x77, 0x91, 0xbf, 0x34, 0x1a, 0x85, 0x4d, 0xbb,
	0x82, 0xf2, 0xa9, 0x6c, 0xb0, 0x08, 0x84, 0x3a, 0xef, 0x9f, 0xb3, 0x03, 0xbb, 0x11, 0xfe, 0x06,
	0xca, 0x41, 0x2b, 0xc4, 0x22, 0xe8, 0x91, 0xf3, 0x95, 0x77, 0x61, 0xf3, 0x6e, 0xe1, 0x1b, 0xcd,
	0xb4, 0xa5, 0x4d, 0xf5, 0x03, 0x38, 0x63, 0x54, 0xf8, 0xb5, 0xe3, 0xec, 0x2f, 0x1a, 0xb3, 0xdd,
	0x08, 0xff, 0xf0, 0xb5, 0x6b, 0x21, 0xfb, 0xb6, 0x6b, 0xa1, 0x06, 0x99, 0x1e, 0xe1, 0x87, 0x33,
	0x99, 0xd2, 0x1e, 0xd7, 0x4a, 0xe0, 0xe4, 0xfd, 0x00, 0x4c, 0x61, 0x50, 0xd9, 0xb1, 0x16, 0xcf,
	0xdc, 0x07, 0xb7, 0xa6, 0x69, 0xb1, 0x36, 0x41, 0x0b, 0x53, 0xcc, 0x29, 0x6a, 0x60, 0x8e, 0x16,
	0xad, 0x2e, 0x80, 0xbe, 0x15, 0x36, 0xf1, 0x04, 0xd0, 0xaa, 0xe0, 0x9a, 0xbe, 0xd0, 0x95, 0x0a,
	0xa0, 0x7c, 0x80, 0xef, 0x1f, 0x0f, 0x79, 0x0a, 0x50, 0xcd, 0x67, 0x8a, 0xe8, 0xf6, 0x62, 0xaa,
	0x29, 0x61, 0xa6, 0xcb, 0x60, 0x3c, 0x88, 0x53, 0x95, 0x01, 0x80, 0x5a, 0x48, 0x1a, 0x11, 0xd3,
	0x5d, 0x79, 0x7e, 0x9a, 0xc5, 0xfd, 0xe5, 0x59, 0x54, 0xac, 0xa2, 0xdc, 0x41, 0x6d, 0x6f, 0xdb,
	0x10, 0xc8, 0x29, 0xdf, 0x05, 0x46, 0xdc, 0x31, 0x00, 0x80, 0x11, 0x86, 0x8a, 0x03, 0x6a, 0xee,
	0x26, 0xca, 0x87, 0xad, 0x03, 0xd0, 0xd0, 0x96, 0xa1, 0x47, 0x79, 0xc4, 0xf8, 0xa9, 0x87, 0xef,
	0x4d, 0xb2, 0xf0, 0x26, 0x04, 0xb9, 0x3a, 0x0a, 0x32, 0xe5, 0x6c, 0xb8, 0x38, 0x71, 0x93, 0x7d,
	0x1d, 0x15, 0xeb, 0x4c, 0x69, 0x53, 0x1f, 0x35, 0xac, 0xe1, 0x45, 0xb4, 0x28, 0xda, 0x6d, 0x45,
	0x35, 0xf0, 0x2d, 0xeb, 0xa7, 0x6f, 0xe6, 0x1b, 0x21, 0x14, 0x09, 0xd7, 0x29, 0xcd, 0xec, 0x8b,
	0x7b, 0x03, 0x2d, 0x3f, 0xa1, 0x10, 0x60, 0xe8, 0xff, 0x26, 0xc2, 0xba, 0xdf, 0x41, 0x6b, 0x23,
	0x53, 0xab, 0xb8, 0xff, 0x4f, 0xc6, 0xc9, 0xf8, 0xf3, 0x53, 0xf1, 0xbf, 0x82, 0x0a, 0x13, 0xc1,
	0xf1, 0x35, 0xb4, 0xc0, 0x34, 0xed, 0x2a, 0xf8, 0xa6, 0x29, 0x6c, 0xae, 0xcc, 0x70, 0xc1, 0xb7,
	0xb3, 0xee, 0x5d, 0xb4, 0x3a, 0x51, 0x02, 0xd5, 0x13, 0x5c, 0x51, 0xfc, 0xa5, 0x69, 0xdf, 0xc2,
	0x84, 0xef, 0xd0, 0xef, 0xb3, 0x79, 0x74, 0x71, 0xe8, 0x98, 0x2a, 0xd4, 0x70, 0x3d, 0x1f, 0xa3,
	0xac, 0x1e, 0xf4, 0x68, 0xfa, 0x99, 0xe4, 0xa6, 0xce, 0x67, 0x1b, 0x7b, 0xcd, 0x41, 0x8f, 0x56,
	0xd6, 0x81, 0x66, 0x2e, 0x26, 0xc7, 0xd0, 0x90, 0x1b, 0xef, 0xa9, 0xf6, 0x40, 0x90, 0x88, 0xa9,
	0x5e, 0x1c, 0x0c, 0x7c, 0x88, 0x3c, 0x59, 0x83, 0xcc, 0x94, 0x28, 0x8c, 0x4b, 0x39, 0x7f, 0x76,
	0x29, 0xb3, 0x93, 0x9b, 0xf7, 0xd3, 0x0c, 0xca, 0x9a, 0xfc, 0xf8, 0xc3, 0x31, 0x0b, 0xe7, 0xca,
	0x7b, 0x40, 0xa0, 0x9d, 0xea, 0xa8, 0x37, 0x31, 0x2d, 0x92, 0x69, 0xa9, 0xe9, 0xc4, 0xb7, 0xe8,
	0xb8, 0x85, 0x32, 0x94, 0x32, 0x9f, 0xb6, 0xfd, 0x80, 0x41, 0x93, 0x3e, 0xdb, 0x2e, 0xe1, 0x87,
	0x28, 0xdf, 0xa8, 0xee, 0xd4, 0xb6, 0x8f, 0xea, 0x20, 0xb8, 0x1e, 0x84, 0x5f, 0xaf, 0x8e, 0x6f,
	0x82, 0xb4, 0x4d, 0x80, 0x5b, 0x10, 0xfe, 0x41, 0x21, 0x8c, 0x93, 0x9e, 0x14, 0xa7, 0x92, 0x2a,
	0x85, 0xdf, 0x45, 0xf9, 0xea, 0xfe, 0xfb, 0x07, 0xf5, 0x5a, 0xb3, 0xb6, 0x5d, 0xcc, 0x94, 0x5d,
	0x70, 0xff, 0xc2, 0xd4, 0xd5, 0x39, 0x3c, 0x8b, 0x91, 0x75, 0xc7, 0x77, 0x50, 0xce, 0xaf, 0x35,
	0x8e, 0xea, 0xcd, 0x46, 0x71, 0xbe, 0xfc, 0x65, 0x70, 0xf8, 0x62, 0xfa, 0x6f, 0x02, 0xd8, 0x73,
	0xc1, 0x09, 0xed, 0xf6, 0xf4, 0x60, 0xd8, 0x18, 0x9c, 0x2c, 0xc2, 0x1e, 0xbd, 0xf7, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x1b, 0x2b, 0x25, 0x6b, 0x44, 0x12, 0x00, 0x00,
}
