// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "www.velocidex.com/golang/velociraptor/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GUISettings_UIMode int32

const (
	GUISettings_BASIC    GUISettings_UIMode = 0
	GUISettings_ADVANCED GUISettings_UIMode = 1
	GUISettings_DEBUG    GUISettings_UIMode = 2
)

var GUISettings_UIMode_name = map[int32]string{
	0: "BASIC",
	1: "ADVANCED",
	2: "DEBUG",
}
var GUISettings_UIMode_value = map[string]int32{
	"BASIC":    0,
	"ADVANCED": 1,
	"DEBUG":    2,
}

func (x GUISettings_UIMode) String() string {
	return proto.EnumName(GUISettings_UIMode_name, int32(x))
}
func (GUISettings_UIMode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{1, 0}
}

type ApiGrrUser_UserType int32

const (
	ApiGrrUser_USER_TYPE_NONE     ApiGrrUser_UserType = 0
	ApiGrrUser_USER_TYPE_STANDARD ApiGrrUser_UserType = 1
	ApiGrrUser_USER_TYPE_ADMIN    ApiGrrUser_UserType = 2
)

var ApiGrrUser_UserType_name = map[int32]string{
	0: "USER_TYPE_NONE",
	1: "USER_TYPE_STANDARD",
	2: "USER_TYPE_ADMIN",
}
var ApiGrrUser_UserType_value = map[string]int32{
	"USER_TYPE_NONE":     0,
	"USER_TYPE_STANDARD": 1,
	"USER_TYPE_ADMIN":    2,
}

func (x ApiGrrUser_UserType) String() string {
	return proto.EnumName(ApiGrrUser_UserType_name, int32(x))
}
func (ApiGrrUser_UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{4, 0}
}

type UserNotification_Type int32

const (
	UserNotification_TYPE_UNSET                                  UserNotification_Type = 0
	UserNotification_TYPE_CLIENT_INTERROGATED                    UserNotification_Type = 1
	UserNotification_TYPE_CLIENT_APPROVAL_REQUESTED              UserNotification_Type = 2
	UserNotification_TYPE_HUNT_APPROVAL_REQUESTED                UserNotification_Type = 3
	UserNotification_TYPE_CRON_JOB_APPROVAL_REQUESTED            UserNotification_Type = 4
	UserNotification_TYPE_CLIENT_APPROVAL_GRANTED                UserNotification_Type = 5
	UserNotification_TYPE_HUNT_APPROVAL_GRANTED                  UserNotification_Type = 6
	UserNotification_TYPE_CRON_JOB_APPROVAL_GRANTED              UserNotification_Type = 7
	UserNotification_TYPE_VFS_FILE_COLLECTED                     UserNotification_Type = 8
	UserNotification_TYPE_VFS_FILE_COLLECTION_FAILED             UserNotification_Type = 9
	UserNotification_TYPE_HUNT_STOPPED                           UserNotification_Type = 10
	UserNotification_TYPE_FILE_ARCHIVE_GENERATED                 UserNotification_Type = 11
	UserNotification_TYPE_FILE_ARCHIVE_GENERATION_FAILED         UserNotification_Type = 12
	UserNotification_TYPE_FLOW_RUN_COMPLETED                     UserNotification_Type = 13
	UserNotification_TYPE_FLOW_RUN_FAILED                        UserNotification_Type = 14
	UserNotification_TYPE_VFS_LIST_DIRECTORY_COMPLETED           UserNotification_Type = 15
	UserNotification_TYPE_VFS_RECURSIVE_LIST_DIRECTORY_COMPLETED UserNotification_Type = 16
)

var UserNotification_Type_name = map[int32]string{
	0:  "TYPE_UNSET",
	1:  "TYPE_CLIENT_INTERROGATED",
	2:  "TYPE_CLIENT_APPROVAL_REQUESTED",
	3:  "TYPE_HUNT_APPROVAL_REQUESTED",
	4:  "TYPE_CRON_JOB_APPROVAL_REQUESTED",
	5:  "TYPE_CLIENT_APPROVAL_GRANTED",
	6:  "TYPE_HUNT_APPROVAL_GRANTED",
	7:  "TYPE_CRON_JOB_APPROVAL_GRANTED",
	8:  "TYPE_VFS_FILE_COLLECTED",
	9:  "TYPE_VFS_FILE_COLLECTION_FAILED",
	10: "TYPE_HUNT_STOPPED",
	11: "TYPE_FILE_ARCHIVE_GENERATED",
	12: "TYPE_FILE_ARCHIVE_GENERATION_FAILED",
	13: "TYPE_FLOW_RUN_COMPLETED",
	14: "TYPE_FLOW_RUN_FAILED",
	15: "TYPE_VFS_LIST_DIRECTORY_COMPLETED",
	16: "TYPE_VFS_RECURSIVE_LIST_DIRECTORY_COMPLETED",
}
var UserNotification_Type_value = map[string]int32{
	"TYPE_UNSET":                                  0,
	"TYPE_CLIENT_INTERROGATED":                    1,
	"TYPE_CLIENT_APPROVAL_REQUESTED":              2,
	"TYPE_HUNT_APPROVAL_REQUESTED":                3,
	"TYPE_CRON_JOB_APPROVAL_REQUESTED":            4,
	"TYPE_CLIENT_APPROVAL_GRANTED":                5,
	"TYPE_HUNT_APPROVAL_GRANTED":                  6,
	"TYPE_CRON_JOB_APPROVAL_GRANTED":              7,
	"TYPE_VFS_FILE_COLLECTED":                     8,
	"TYPE_VFS_FILE_COLLECTION_FAILED":             9,
	"TYPE_HUNT_STOPPED":                           10,
	"TYPE_FILE_ARCHIVE_GENERATED":                 11,
	"TYPE_FILE_ARCHIVE_GENERATION_FAILED":         12,
	"TYPE_FLOW_RUN_COMPLETED":                     13,
	"TYPE_FLOW_RUN_FAILED":                        14,
	"TYPE_VFS_LIST_DIRECTORY_COMPLETED":           15,
	"TYPE_VFS_RECURSIVE_LIST_DIRECTORY_COMPLETED": 16,
}

func (x UserNotification_Type) String() string {
	return proto.EnumName(UserNotification_Type_name, int32(x))
}
func (UserNotification_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{6, 0}
}

type UserNotification_State int32

const (
	UserNotification_STATE_UNSET       UserNotification_State = 0
	UserNotification_STATE_PENDING     UserNotification_State = 1
	UserNotification_STATE_NOT_PENDING UserNotification_State = 2
)

var UserNotification_State_name = map[int32]string{
	0: "STATE_UNSET",
	1: "STATE_PENDING",
	2: "STATE_NOT_PENDING",
}
var UserNotification_State_value = map[string]int32{
	"STATE_UNSET":       0,
	"STATE_PENDING":     1,
	"STATE_NOT_PENDING": 2,
}

func (x UserNotification_State) String() string {
	return proto.EnumName(UserNotification_State_name, int32(x))
}
func (UserNotification_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{6, 1}
}

type VelociraptorUser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PasswordHash         []byte   `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	PasswordSalt         []byte   `protobuf:"bytes,3,opt,name=password_salt,json=passwordSalt,proto3" json:"password_salt,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Picture              string   `protobuf:"bytes,5,opt,name=picture,proto3" json:"picture,omitempty"`
	VerifiedEmail        bool     `protobuf:"varint,6,opt,name=verified_email,json=verifiedEmail,proto3" json:"verified_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VelociraptorUser) Reset()         { *m = VelociraptorUser{} }
func (m *VelociraptorUser) String() string { return proto.CompactTextString(m) }
func (*VelociraptorUser) ProtoMessage()    {}
func (*VelociraptorUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{0}
}
func (m *VelociraptorUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VelociraptorUser.Unmarshal(m, b)
}
func (m *VelociraptorUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VelociraptorUser.Marshal(b, m, deterministic)
}
func (dst *VelociraptorUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VelociraptorUser.Merge(dst, src)
}
func (m *VelociraptorUser) XXX_Size() int {
	return xxx_messageInfo_VelociraptorUser.Size(m)
}
func (m *VelociraptorUser) XXX_DiscardUnknown() {
	xxx_messageInfo_VelociraptorUser.DiscardUnknown(m)
}

var xxx_messageInfo_VelociraptorUser proto.InternalMessageInfo

func (m *VelociraptorUser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VelociraptorUser) GetPasswordHash() []byte {
	if m != nil {
		return m.PasswordHash
	}
	return nil
}

func (m *VelociraptorUser) GetPasswordSalt() []byte {
	if m != nil {
		return m.PasswordSalt
	}
	return nil
}

func (m *VelociraptorUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VelociraptorUser) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *VelociraptorUser) GetVerifiedEmail() bool {
	if m != nil {
		return m.VerifiedEmail
	}
	return false
}

// Next field: 4
type GUISettings struct {
	Mode                 GUISettings_UIMode `protobuf:"varint,1,opt,name=mode,proto3,enum=proto.GUISettings_UIMode" json:"mode,omitempty"`
	CanaryMode           bool               `protobuf:"varint,3,opt,name=canary_mode,json=canaryMode,proto3" json:"canary_mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GUISettings) Reset()         { *m = GUISettings{} }
func (m *GUISettings) String() string { return proto.CompactTextString(m) }
func (*GUISettings) ProtoMessage()    {}
func (*GUISettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{1}
}
func (m *GUISettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GUISettings.Unmarshal(m, b)
}
func (m *GUISettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GUISettings.Marshal(b, m, deterministic)
}
func (dst *GUISettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GUISettings.Merge(dst, src)
}
func (m *GUISettings) XXX_Size() int {
	return xxx_messageInfo_GUISettings.Size(m)
}
func (m *GUISettings) XXX_DiscardUnknown() {
	xxx_messageInfo_GUISettings.DiscardUnknown(m)
}

var xxx_messageInfo_GUISettings proto.InternalMessageInfo

func (m *GUISettings) GetMode() GUISettings_UIMode {
	if m != nil {
		return m.Mode
	}
	return GUISettings_BASIC
}

func (m *GUISettings) GetCanaryMode() bool {
	if m != nil {
		return m.CanaryMode
	}
	return false
}

type UILink struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UILink) Reset()         { *m = UILink{} }
func (m *UILink) String() string { return proto.CompactTextString(m) }
func (*UILink) ProtoMessage()    {}
func (*UILink) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{2}
}
func (m *UILink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UILink.Unmarshal(m, b)
}
func (m *UILink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UILink.Marshal(b, m, deterministic)
}
func (dst *UILink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UILink.Merge(dst, src)
}
func (m *UILink) XXX_Size() int {
	return xxx_messageInfo_UILink.Size(m)
}
func (m *UILink) XXX_DiscardUnknown() {
	xxx_messageInfo_UILink.DiscardUnknown(m)
}

var xxx_messageInfo_UILink proto.InternalMessageInfo

func (m *UILink) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *UILink) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

// These traits are used by the AdminUI Angular app to disable certain UI
// elements.
type ApiGrrUserInterfaceTraits struct {
	CronJobsNavItemEnabled                bool      `protobuf:"varint,1,opt,name=cron_jobs_nav_item_enabled,json=cronJobsNavItemEnabled,proto3" json:"cron_jobs_nav_item_enabled,omitempty"`
	CreateCronJobActionEnabled            bool      `protobuf:"varint,2,opt,name=create_cron_job_action_enabled,json=createCronJobActionEnabled,proto3" json:"create_cron_job_action_enabled,omitempty"`
	HuntManagerNavItemEnabled             bool      `protobuf:"varint,3,opt,name=hunt_manager_nav_item_enabled,json=huntManagerNavItemEnabled,proto3" json:"hunt_manager_nav_item_enabled,omitempty"`
	CreateHuntActionEnabled               bool      `protobuf:"varint,4,opt,name=create_hunt_action_enabled,json=createHuntActionEnabled,proto3" json:"create_hunt_action_enabled,omitempty"`
	ShowStatisticsNavItemEnabled          bool      `protobuf:"varint,5,opt,name=show_statistics_nav_item_enabled,json=showStatisticsNavItemEnabled,proto3" json:"show_statistics_nav_item_enabled,omitempty"`
	ServerLoadNavItemEnabled              bool      `protobuf:"varint,7,opt,name=server_load_nav_item_enabled,json=serverLoadNavItemEnabled,proto3" json:"server_load_nav_item_enabled,omitempty"`
	ManageBinariesNavItemEnabled          bool      `protobuf:"varint,9,opt,name=manage_binaries_nav_item_enabled,json=manageBinariesNavItemEnabled,proto3" json:"manage_binaries_nav_item_enabled,omitempty"`
	UploadBinaryActionEnabled             bool      `protobuf:"varint,10,opt,name=upload_binary_action_enabled,json=uploadBinaryActionEnabled,proto3" json:"upload_binary_action_enabled,omitempty"`
	SettingsNavItemEnabled                bool      `protobuf:"varint,11,opt,name=settings_nav_item_enabled,json=settingsNavItemEnabled,proto3" json:"settings_nav_item_enabled,omitempty"`
	ArtifactManagerNavItemEnabled         bool      `protobuf:"varint,12,opt,name=artifact_manager_nav_item_enabled,json=artifactManagerNavItemEnabled,proto3" json:"artifact_manager_nav_item_enabled,omitempty"`
	UploadArtifactActionEnabled           bool      `protobuf:"varint,13,opt,name=upload_artifact_action_enabled,json=uploadArtifactActionEnabled,proto3" json:"upload_artifact_action_enabled,omitempty"`
	SearchClientsActionEnabled            bool      `protobuf:"varint,14,opt,name=search_clients_action_enabled,json=searchClientsActionEnabled,proto3" json:"search_clients_action_enabled,omitempty"`
	BrowseVirtualFileSystemNavItemEnabled bool      `protobuf:"varint,15,opt,name=browse_virtual_file_system_nav_item_enabled,json=browseVirtualFileSystemNavItemEnabled,proto3" json:"browse_virtual_file_system_nav_item_enabled,omitempty"`
	StartClientFlowNavItemEnabled         bool      `protobuf:"varint,16,opt,name=start_client_flow_nav_item_enabled,json=startClientFlowNavItemEnabled,proto3" json:"start_client_flow_nav_item_enabled,omitempty"`
	ManageClientFlowsNavItemEnabled       bool      `protobuf:"varint,17,opt,name=manage_client_flows_nav_item_enabled,json=manageClientFlowsNavItemEnabled,proto3" json:"manage_client_flows_nav_item_enabled,omitempty"`
	ModifyClientLabelsActionEnabled       bool      `protobuf:"varint,18,opt,name=modify_client_labels_action_enabled,json=modifyClientLabelsActionEnabled,proto3" json:"modify_client_labels_action_enabled,omitempty"`
	AuthUsingGoogle                       bool      `protobuf:"varint,19,opt,name=auth_using_google,json=authUsingGoogle,proto3" json:"auth_using_google,omitempty"`
	Picture                               string    `protobuf:"bytes,20,opt,name=picture,proto3" json:"picture,omitempty"`
	Links                                 []*UILink `protobuf:"bytes,21,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral                  struct{}  `json:"-"`
	XXX_unrecognized                      []byte    `json:"-"`
	XXX_sizecache                         int32     `json:"-"`
}

func (m *ApiGrrUserInterfaceTraits) Reset()         { *m = ApiGrrUserInterfaceTraits{} }
func (m *ApiGrrUserInterfaceTraits) String() string { return proto.CompactTextString(m) }
func (*ApiGrrUserInterfaceTraits) ProtoMessage()    {}
func (*ApiGrrUserInterfaceTraits) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{3}
}
func (m *ApiGrrUserInterfaceTraits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGrrUserInterfaceTraits.Unmarshal(m, b)
}
func (m *ApiGrrUserInterfaceTraits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGrrUserInterfaceTraits.Marshal(b, m, deterministic)
}
func (dst *ApiGrrUserInterfaceTraits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGrrUserInterfaceTraits.Merge(dst, src)
}
func (m *ApiGrrUserInterfaceTraits) XXX_Size() int {
	return xxx_messageInfo_ApiGrrUserInterfaceTraits.Size(m)
}
func (m *ApiGrrUserInterfaceTraits) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGrrUserInterfaceTraits.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGrrUserInterfaceTraits proto.InternalMessageInfo

func (m *ApiGrrUserInterfaceTraits) GetCronJobsNavItemEnabled() bool {
	if m != nil {
		return m.CronJobsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetCreateCronJobActionEnabled() bool {
	if m != nil {
		return m.CreateCronJobActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetHuntManagerNavItemEnabled() bool {
	if m != nil {
		return m.HuntManagerNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetCreateHuntActionEnabled() bool {
	if m != nil {
		return m.CreateHuntActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetShowStatisticsNavItemEnabled() bool {
	if m != nil {
		return m.ShowStatisticsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetServerLoadNavItemEnabled() bool {
	if m != nil {
		return m.ServerLoadNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetManageBinariesNavItemEnabled() bool {
	if m != nil {
		return m.ManageBinariesNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetUploadBinaryActionEnabled() bool {
	if m != nil {
		return m.UploadBinaryActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetSettingsNavItemEnabled() bool {
	if m != nil {
		return m.SettingsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetArtifactManagerNavItemEnabled() bool {
	if m != nil {
		return m.ArtifactManagerNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetUploadArtifactActionEnabled() bool {
	if m != nil {
		return m.UploadArtifactActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetSearchClientsActionEnabled() bool {
	if m != nil {
		return m.SearchClientsActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetBrowseVirtualFileSystemNavItemEnabled() bool {
	if m != nil {
		return m.BrowseVirtualFileSystemNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetStartClientFlowNavItemEnabled() bool {
	if m != nil {
		return m.StartClientFlowNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetManageClientFlowsNavItemEnabled() bool {
	if m != nil {
		return m.ManageClientFlowsNavItemEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetModifyClientLabelsActionEnabled() bool {
	if m != nil {
		return m.ModifyClientLabelsActionEnabled
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetAuthUsingGoogle() bool {
	if m != nil {
		return m.AuthUsingGoogle
	}
	return false
}

func (m *ApiGrrUserInterfaceTraits) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *ApiGrrUserInterfaceTraits) GetLinks() []*UILink {
	if m != nil {
		return m.Links
	}
	return nil
}

type ApiGrrUser struct {
	Username             string                     `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Settings             *GUISettings               `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	InterfaceTraits      *ApiGrrUserInterfaceTraits `protobuf:"bytes,3,opt,name=interface_traits,json=interfaceTraits,proto3" json:"interface_traits,omitempty"`
	UserType             ApiGrrUser_UserType        `protobuf:"varint,4,opt,name=user_type,json=userType,proto3,enum=proto.ApiGrrUser_UserType" json:"user_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ApiGrrUser) Reset()         { *m = ApiGrrUser{} }
func (m *ApiGrrUser) String() string { return proto.CompactTextString(m) }
func (*ApiGrrUser) ProtoMessage()    {}
func (*ApiGrrUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{4}
}
func (m *ApiGrrUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiGrrUser.Unmarshal(m, b)
}
func (m *ApiGrrUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiGrrUser.Marshal(b, m, deterministic)
}
func (dst *ApiGrrUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiGrrUser.Merge(dst, src)
}
func (m *ApiGrrUser) XXX_Size() int {
	return xxx_messageInfo_ApiGrrUser.Size(m)
}
func (m *ApiGrrUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiGrrUser.DiscardUnknown(m)
}

var xxx_messageInfo_ApiGrrUser proto.InternalMessageInfo

func (m *ApiGrrUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ApiGrrUser) GetSettings() *GUISettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

func (m *ApiGrrUser) GetInterfaceTraits() *ApiGrrUserInterfaceTraits {
	if m != nil {
		return m.InterfaceTraits
	}
	return nil
}

func (m *ApiGrrUser) GetUserType() ApiGrrUser_UserType {
	if m != nil {
		return m.UserType
	}
	return ApiGrrUser_USER_TYPE_NONE
}

type UserNotificationCount struct {
	Count                uint64   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserNotificationCount) Reset()         { *m = UserNotificationCount{} }
func (m *UserNotificationCount) String() string { return proto.CompactTextString(m) }
func (*UserNotificationCount) ProtoMessage()    {}
func (*UserNotificationCount) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{5}
}
func (m *UserNotificationCount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNotificationCount.Unmarshal(m, b)
}
func (m *UserNotificationCount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNotificationCount.Marshal(b, m, deterministic)
}
func (dst *UserNotificationCount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNotificationCount.Merge(dst, src)
}
func (m *UserNotificationCount) XXX_Size() int {
	return xxx_messageInfo_UserNotificationCount.Size(m)
}
func (m *UserNotificationCount) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNotificationCount.DiscardUnknown(m)
}

var xxx_messageInfo_UserNotificationCount proto.InternalMessageInfo

func (m *UserNotificationCount) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type UserNotification struct {
	Username             string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	NotificationType     UserNotification_Type  `protobuf:"varint,2,opt,name=notification_type,json=notificationType,proto3,enum=proto.UserNotification_Type" json:"notification_type,omitempty"`
	State                UserNotification_State `protobuf:"varint,3,opt,name=state,proto3,enum=proto.UserNotification_State" json:"state,omitempty"`
	Timestamp            uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message              string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Reference            *ObjectReference       `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UserNotification) Reset()         { *m = UserNotification{} }
func (m *UserNotification) String() string { return proto.CompactTextString(m) }
func (*UserNotification) ProtoMessage()    {}
func (*UserNotification) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{6}
}
func (m *UserNotification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserNotification.Unmarshal(m, b)
}
func (m *UserNotification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserNotification.Marshal(b, m, deterministic)
}
func (dst *UserNotification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserNotification.Merge(dst, src)
}
func (m *UserNotification) XXX_Size() int {
	return xxx_messageInfo_UserNotification.Size(m)
}
func (m *UserNotification) XXX_DiscardUnknown() {
	xxx_messageInfo_UserNotification.DiscardUnknown(m)
}

var xxx_messageInfo_UserNotification proto.InternalMessageInfo

func (m *UserNotification) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserNotification) GetNotificationType() UserNotification_Type {
	if m != nil {
		return m.NotificationType
	}
	return UserNotification_TYPE_UNSET
}

func (m *UserNotification) GetState() UserNotification_State {
	if m != nil {
		return m.State
	}
	return UserNotification_STATE_UNSET
}

func (m *UserNotification) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *UserNotification) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserNotification) GetReference() *ObjectReference {
	if m != nil {
		return m.Reference
	}
	return nil
}

type GetUserNotificationsResponse struct {
	Items                []*UserNotification `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetUserNotificationsResponse) Reset()         { *m = GetUserNotificationsResponse{} }
func (m *GetUserNotificationsResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserNotificationsResponse) ProtoMessage()    {}
func (*GetUserNotificationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{7}
}
func (m *GetUserNotificationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserNotificationsResponse.Unmarshal(m, b)
}
func (m *GetUserNotificationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserNotificationsResponse.Marshal(b, m, deterministic)
}
func (dst *GetUserNotificationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserNotificationsResponse.Merge(dst, src)
}
func (m *GetUserNotificationsResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserNotificationsResponse.Size(m)
}
func (m *GetUserNotificationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserNotificationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserNotificationsResponse proto.InternalMessageInfo

func (m *GetUserNotificationsResponse) GetItems() []*UserNotification {
	if m != nil {
		return m.Items
	}
	return nil
}

type GetUserNotificationsRequest struct {
	ClearPending         bool     `protobuf:"varint,1,opt,name=clear_pending,json=clearPending,proto3" json:"clear_pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserNotificationsRequest) Reset()         { *m = GetUserNotificationsRequest{} }
func (m *GetUserNotificationsRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserNotificationsRequest) ProtoMessage()    {}
func (*GetUserNotificationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_968c7833f35629b6, []int{8}
}
func (m *GetUserNotificationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserNotificationsRequest.Unmarshal(m, b)
}
func (m *GetUserNotificationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserNotificationsRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserNotificationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserNotificationsRequest.Merge(dst, src)
}
func (m *GetUserNotificationsRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserNotificationsRequest.Size(m)
}
func (m *GetUserNotificationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserNotificationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserNotificationsRequest proto.InternalMessageInfo

func (m *GetUserNotificationsRequest) GetClearPending() bool {
	if m != nil {
		return m.ClearPending
	}
	return false
}

func init() {
	proto.RegisterType((*VelociraptorUser)(nil), "proto.VelociraptorUser")
	proto.RegisterType((*GUISettings)(nil), "proto.GUISettings")
	proto.RegisterType((*UILink)(nil), "proto.UILink")
	proto.RegisterType((*ApiGrrUserInterfaceTraits)(nil), "proto.ApiGrrUserInterfaceTraits")
	proto.RegisterType((*ApiGrrUser)(nil), "proto.ApiGrrUser")
	proto.RegisterType((*UserNotificationCount)(nil), "proto.UserNotificationCount")
	proto.RegisterType((*UserNotification)(nil), "proto.UserNotification")
	proto.RegisterType((*GetUserNotificationsResponse)(nil), "proto.GetUserNotificationsResponse")
	proto.RegisterType((*GetUserNotificationsRequest)(nil), "proto.GetUserNotificationsRequest")
	proto.RegisterEnum("proto.GUISettings_UIMode", GUISettings_UIMode_name, GUISettings_UIMode_value)
	proto.RegisterEnum("proto.ApiGrrUser_UserType", ApiGrrUser_UserType_name, ApiGrrUser_UserType_value)
	proto.RegisterEnum("proto.UserNotification_Type", UserNotification_Type_name, UserNotification_Type_value)
	proto.RegisterEnum("proto.UserNotification_State", UserNotification_State_name, UserNotification_State_value)
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_users_968c7833f35629b6) }

var fileDescriptor_users_968c7833f35629b6 = []byte{
	// 1672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x56, 0x41, 0x77, 0x22, 0xc7,
	0x11, 0x5e, 0x69, 0x61, 0x57, 0x2a, 0x24, 0x84, 0x7a, 0xb5, 0xbb, 0x48, 0x8b, 0xb4, 0x63, 0xb4,
	0xfb, 0x56, 0xb1, 0x77, 0xd1, 0xb3, 0x9c, 0xc4, 0xcf, 0x9b, 0xf7, 0xe2, 0x0c, 0x30, 0xa0, 0xb1,
	0xd1, 0xa0, 0x34, 0xa0, 0xc4, 0xb9, 0xf4, 0x6b, 0x86, 0x06, 0xc6, 0x1e, 0x66, 0xf0, 0x74, 0x23,
	0xac, 0x73, 0xee, 0x39, 0xe5, 0x7f, 0x24, 0xc7, 0xfc, 0x80, 0xfc, 0x8a, 0x1c, 0x93, 0x43, 0xfe,
	0x44, 0x0e, 0x79, 0xdd, 0xcd, 0x00, 0x1a, 0x90, 0x2f, 0x30, 0x53, 0xf5, 0xd5, 0xd7, 0x5f, 0x55,
	0xf7, 0x54, 0x35, 0x64, 0x26, 0x9c, 0x45, 0xbc, 0x34, 0x8e, 0x42, 0x11, 0xa2, 0xb4, 0xfa, 0x3b,
	0xfa, 0x38, 0x9d, 0x4e, 0x4b, 0xb7, 0xcc, 0x0f, 0x5d, 0xaf, 0xc7, 0x7e, 0x2a, 0xb9, 0xe1, 0xe8,
	0x7c, 0x10, 0xfa, 0x34, 0x18, 0x9c, 0x6b, 0x63, 0x44, 0xc7, 0x22, 0x8c, 0xce, 0x15, 0xf8, 0x9c,
	0xb3, 0x11, 0x0d, 0x84, 0xe7, 0x6a, 0x8a, 0xa3, 0xdd, 0xb0, 0xfb, 0x3d, 0x73, 0xc5, 0x8c, 0xb1,
	0xf8, 0xe7, 0x4d, 0xc8, 0xdd, 0x2c, 0x05, 0x75, 0x38, 0x8b, 0xd0, 0x19, 0xa4, 0x02, 0x3a, 0x62,
	0xf9, 0x0d, 0x63, 0xe3, 0x6c, 0xbb, 0x7c, 0xf0, 0xef, 0xff, 0xfd, 0xe7, 0x9f, 0x1b, 0x59, 0xb4,
	0xd3, 0x1e, 0x32, 0x43, 0xaa, 0x91, 0x3e, 0xac, 0x10, 0xc8, 0x86, 0xdd, 0x31, 0xe5, 0x7c, 0x1a,
	0x46, 0x3d, 0x32, 0xa4, 0x7c, 0x98, 0xdf, 0x34, 0x36, 0xce, 0x76, 0xca, 0x6f, 0x54, 0xc8, 0x09,
	0x2a, 0xb4, 0x2e, 0xcd, 0x8b, 0x5f, 0xfd, 0xda, 0x90, 0x2e, 0x23, 0xec, 0x1b, 0x62, 0xc8, 0x8c,
	0x18, 0x5f, 0xc2, 0x3b, 0xf1, 0xe3, 0x25, 0xe5, 0x43, 0x74, 0xba, 0x44, 0xc5, 0xa9, 0x2f, 0xf2,
	0x8f, 0x25, 0xd5, 0x02, 0xd4, 0xa2, 0xbe, 0x40, 0x07, 0x90, 0x66, 0x23, 0xea, 0xf9, 0xf9, 0x94,
	0x94, 0x86, 0xf5, 0x0b, 0xca, 0xc3, 0xd3, 0xb1, 0xe7, 0x8a, 0x49, 0xc4, 0xf2, 0x69, 0x65, 0x8f,
	0x5f, 0xd1, 0x5b, 0xc8, 0xde, 0xb2, 0xc8, 0xeb, 0x7b, 0xac, 0x47, 0x74, 0xe0, 0x13, 0x63, 0xe3,
	0x6c, 0x0b, 0xef, 0xc6, 0x56, 0x4b, 0x1a, 0x8b, 0x7f, 0xd9, 0x84, 0x4c, 0xbd, 0x63, 0xb7, 0x98,
	0x10, 0x5e, 0x30, 0xe0, 0xe8, 0x5b, 0x48, 0x8d, 0xc2, 0x9e, 0x2e, 0x40, 0xf6, 0xe2, 0x50, 0xd7,
	0xaa, 0xb4, 0x84, 0x28, 0x75, 0xec, 0xab, 0xb0, 0xc7, 0xca, 0x05, 0x95, 0xe8, 0x0b, 0x74, 0x20,
	0xeb, 0x66, 0x78, 0x81, 0x60, 0x51, 0x9f, 0xba, 0xcc, 0x90, 0xd1, 0x25, 0xac, 0x48, 0xd0, 0x1f,
	0x21, 0xe3, 0xd2, 0x80, 0x46, 0x77, 0x44, 0x71, 0xca, 0xb4, 0xb6, 0xca, 0x5f, 0xaa, 0xc0, 0xcf,
	0xd1, 0xb9, 0xdd, 0x37, 0x44, 0x34, 0x61, 0xef, 0x0d, 0x3e, 0x0c, 0xa7, 0x46, 0x9f, 0x51, 0xa9,
	0x9b, 0x1b, 0x62, 0x48, 0x85, 0x41, 0x23, 0x66, 0x74, 0x99, 0x17, 0x0c, 0x0c, 0x45, 0xe0, 0xb1,
	0x5e, 0x09, 0x83, 0xe6, 0x92, 0xab, 0x17, 0xdf, 0xc3, 0x13, 0xad, 0x03, 0x6d, 0x43, 0xba, 0x6c,
	0xb6, 0xec, 0x4a, 0xee, 0x11, 0xda, 0x81, 0x2d, 0xb3, 0x7a, 0x63, 0x3a, 0x15, 0xab, 0x9a, 0xdb,
	0x90, 0x8e, 0xaa, 0x55, 0xee, 0xd4, 0x73, 0x9b, 0x1f, 0x3f, 0xfd, 0x97, 0x5c, 0xf2, 0x0d, 0x14,
	0x95, 0xd6, 0x7a, 0xc7, 0x36, 0xf8, 0x2c, 0x1b, 0x83, 0x06, 0x3d, 0x63, 0x1c, 0xb1, 0x3e, 0x8b,
	0x58, 0xe0, 0x32, 0x5e, 0x2a, 0x96, 0x24, 0x73, 0xc3, 0x0b, 0x7e, 0x40, 0x08, 0x52, 0x82, 0xfd,
	0x24, 0xf4, 0x59, 0xc0, 0xea, 0x19, 0xe5, 0xe0, 0xf1, 0x24, 0xf2, 0xd5, 0x5e, 0x6f, 0x63, 0xf9,
	0x58, 0xfc, 0xef, 0x36, 0x1c, 0x9a, 0x63, 0xaf, 0x1e, 0xa9, 0x03, 0x64, 0xc7, 0x75, 0x68, 0x47,
	0xd4, 0x13, 0x1c, 0x7d, 0x84, 0x23, 0x37, 0x0a, 0x03, 0xf2, 0x7d, 0xd8, 0xe5, 0x24, 0xa0, 0xb7,
	0xc4, 0x13, 0x6c, 0x44, 0x58, 0x40, 0xbb, 0x3e, 0xeb, 0x29, 0xe6, 0x2d, 0xfc, 0x42, 0x22, 0xbe,
	0x09, 0xbb, 0xdc, 0xa1, 0xb7, 0xb6, 0x60, 0x23, 0x4b, 0x7b, 0x51, 0x19, 0x4e, 0xdc, 0x88, 0x51,
	0xc1, 0x48, 0x4c, 0x41, 0xa8, 0x2b, 0xbc, 0x30, 0x98, 0xc7, 0x6f, 0xaa, 0xf8, 0x23, 0x8d, 0xaa,
	0x68, 0x16, 0x53, 0x41, 0x62, 0x8e, 0xdf, 0xc1, 0xf1, 0x70, 0x12, 0x08, 0x32, 0xa2, 0x01, 0x1d,
	0xb0, 0x68, 0x55, 0x82, 0xda, 0x13, 0x7c, 0x28, 0x41, 0x57, 0x1a, 0x93, 0x50, 0xf1, 0x1b, 0x98,
	0xf1, 0x13, 0x45, 0x94, 0x50, 0x90, 0x52, 0xe1, 0x2f, 0x35, 0xe2, 0x72, 0x12, 0x88, 0xfb, 0xcb,
	0xd7, 0x40, 0x6d, 0x2e, 0xe1, 0x82, 0x0a, 0x8f, 0x0b, 0xcf, 0x5d, 0x53, 0x84, 0xb4, 0xa2, 0x28,
	0x48, 0x5c, 0x6b, 0x0e, 0x4b, 0x88, 0xf8, 0x2d, 0x14, 0x38, 0x8b, 0x6e, 0x59, 0x44, 0xfc, 0x90,
	0xf6, 0x56, 0x39, 0x9e, 0x2a, 0x8e, 0xbc, 0xc6, 0x34, 0x42, 0xda, 0x4b, 0xc4, 0xd7, 0xc0, 0xd0,
	0x15, 0x20, 0x5d, 0x4f, 0x1d, 0xa7, 0x35, 0x3a, 0xb6, 0xb5, 0x0e, 0x8d, 0x2b, 0xcf, 0x60, 0x09,
	0x9e, 0xaf, 0xa1, 0x30, 0x19, 0x2b, 0x09, 0x8a, 0xe7, 0x2e, 0x59, 0x0e, 0xd0, 0xd5, 0xd4, 0x18,
	0xc5, 0x71, 0x77, 0xbf, 0x20, 0x5f, 0xc1, 0x61, 0x7c, 0xf4, 0x56, 0x15, 0x64, 0xf4, 0x71, 0x88,
	0x01, 0x89, 0xb5, 0x2f, 0xe1, 0x13, 0x1a, 0x09, 0xaf, 0x4f, 0xdd, 0x9f, 0xd9, 0xce, 0x1d, 0x45,
	0x71, 0x1c, 0x03, 0xd7, 0x6f, 0x69, 0x05, 0x4e, 0x66, 0x59, 0xcc, 0x09, 0x13, 0x79, 0xec, 0x2a,
	0x9a, 0x57, 0x1a, 0x65, 0xce, 0x40, 0xf7, 0x33, 0x31, 0xe1, 0x98, 0x33, 0x1a, 0xb9, 0x43, 0xe2,
	0xfa, 0x1e, 0x0b, 0x04, 0x4f, 0x72, 0x64, 0xf5, 0xe1, 0xd4, 0xa0, 0x8a, 0xc6, 0xdc, 0xa7, 0xf8,
	0x13, 0x7c, 0xd6, 0x8d, 0xc2, 0x29, 0x67, 0xe4, 0xd6, 0x8b, 0xc4, 0x84, 0xfa, 0xa4, 0xef, 0xf9,
	0x8c, 0xf0, 0x3b, 0x2e, 0x53, 0x5a, 0xc9, 0x6d, 0x4f, 0x11, 0xbe, 0xd5, 0x21, 0x37, 0x3a, 0xa2,
	0xe6, 0xf9, 0xac, 0xa5, 0xf0, 0x89, 0x1c, 0x6d, 0x28, 0x72, 0x41, 0x23, 0x31, 0x53, 0x47, 0xfa,
	0x7e, 0x38, 0x5d, 0xa5, 0xcc, 0xe9, 0x72, 0x29, 0xa4, 0x96, 0x58, 0xf3, 0xc3, 0x69, 0x82, 0xea,
	0x0a, 0xde, 0xcc, 0x0e, 0xcf, 0x12, 0xd7, 0x9a, 0xed, 0xdb, 0x57, 0x64, 0xaf, 0x35, 0x76, 0xc1,
	0x96, 0xdc, 0xc7, 0x06, 0x9c, 0x8e, 0xc2, 0x9e, 0xd7, 0xbf, 0x8b, 0xe9, 0x7c, 0xda, 0x65, 0xfe,
	0x4a, 0xf9, 0xd0, 0x8c, 0x4d, 0x41, 0x35, 0x5b, 0x43, 0x01, 0xef, 0xd7, 0xf0, 0x53, 0xd8, 0xa7,
	0x13, 0x31, 0x24, 0x13, 0xee, 0x05, 0x03, 0x32, 0x08, 0xc3, 0x81, 0xcf, 0xf2, 0xcf, 0x54, 0xec,
	0x9e, 0x74, 0x74, 0xa4, 0xbd, 0xae, 0xcc, 0xcb, 0xc3, 0xe2, 0xe0, 0xfe, 0xb0, 0x38, 0x85, 0xb4,
	0xef, 0x05, 0x3f, 0xf0, 0xfc, 0x73, 0xe3, 0xf1, 0x59, 0xe6, 0x62, 0x77, 0xd6, 0xf6, 0x75, 0x23,
	0xc4, 0xda, 0x57, 0xfc, 0xdb, 0x63, 0x80, 0x45, 0xa7, 0x43, 0x5f, 0xc1, 0x56, 0x3c, 0x12, 0x67,
	0xe3, 0xf2, 0x58, 0x75, 0xf6, 0x97, 0xe8, 0xb9, 0x1c, 0x97, 0xd2, 0x1e, 0x0f, 0x3e, 0x89, 0x2b,
	0xe1, 0x39, 0x1c, 0xd9, 0xb0, 0x15, 0x1f, 0x72, 0xd5, 0xc3, 0x32, 0x17, 0x68, 0x75, 0xd0, 0x94,
	0x0f, 0x15, 0xdd, 0x33, 0xb4, 0xaf, 0xba, 0xf6, 0x52, 0xd3, 0x2e, 0xe1, 0x79, 0x38, 0xfa, 0xeb,
	0x06, 0xe4, 0xe6, 0xc3, 0x87, 0x08, 0xd5, 0x75, 0x55, 0x53, 0xcb, 0x5c, 0x18, 0x33, 0xce, 0x07,
	0xbb, 0x73, 0xb9, 0xae, 0x56, 0x30, 0xd1, 0xd7, 0xd2, 0xf9, 0x8e, 0x2f, 0x4d, 0x31, 0x4d, 0x64,
	0x9c, 0x4d, 0xe5, 0x30, 0x12, 0x43, 0x76, 0x27, 0xe7, 0x90, 0x1a, 0x16, 0x2e, 0x0d, 0xde, 0x09,
	0xa3, 0x17, 0x1a, 0x5e, 0xa0, 0x72, 0xeb, 0xd8, 0xbf, 0x28, 0xe1, 0x3d, 0x2f, 0xd1, 0xf7, 0xbf,
	0x84, 0x6d, 0x99, 0x2d, 0x11, 0x77, 0x63, 0xa6, 0x9a, 0x64, 0xf6, 0xe2, 0x68, 0x45, 0x4e, 0x49,
	0xfe, 0xb4, 0xef, 0xc6, 0x4c, 0x97, 0x46, 0x3e, 0x15, 0xbf, 0x85, 0xad, 0xd8, 0x8a, 0x10, 0x64,
	0x3b, 0x2d, 0x0b, 0x93, 0xf6, 0x77, 0xd7, 0x16, 0x71, 0x9a, 0x8e, 0x95, 0x7b, 0x84, 0x5e, 0x00,
	0x5a, 0xd8, 0x5a, 0x6d, 0xd3, 0xa9, 0x9a, 0x58, 0x4e, 0xbb, 0x67, 0xb0, 0xb7, 0xb0, 0x9b, 0xd5,
	0x2b, 0xdb, 0xc9, 0x6d, 0x16, 0x3f, 0xc0, 0x73, 0x49, 0xe6, 0x84, 0xc2, 0xeb, 0x7b, 0x2e, 0x95,
	0xe7, 0xa6, 0x12, 0x4e, 0x02, 0x75, 0x99, 0x70, 0xe5, 0x83, 0xda, 0xb8, 0x14, 0xd6, 0x2f, 0xc5,
	0xbf, 0x3f, 0x85, 0x5c, 0x12, 0x8f, 0x8e, 0x92, 0xdb, 0x7c, 0x6f, 0x1f, 0xf7, 0x83, 0x25, 0xac,
	0xce, 0x76, 0x53, 0x65, 0x5b, 0x88, 0x8f, 0x50, 0x82, 0xaf, 0xa4, 0xf2, 0xcd, 0x2d, 0x87, 0xa9,
	0x5c, 0xbf, 0x80, 0xb4, 0x1c, 0x12, 0xfa, 0x92, 0x90, 0xbd, 0x38, 0x7e, 0x28, 0x5c, 0x8e, 0x08,
	0x86, 0x35, 0x16, 0x7d, 0x0e, 0xdb, 0xc2, 0x1b, 0x31, 0x2e, 0xe8, 0x68, 0xac, 0xaa, 0x9c, 0x2a,
	0x3f, 0x53, 0x5b, 0xba, 0x0b, 0x19, 0x5c, 0xad, 0x55, 0xa9, 0x60, 0xd2, 0x8f, 0x17, 0x28, 0xf9,
	0x0d, 0x8c, 0x18, 0xe7, 0x74, 0x30, 0xbf, 0x30, 0xcd, 0x5e, 0xd1, 0x2f, 0x61, 0x7b, 0x7e, 0x0f,
	0x50, 0x77, 0xa5, 0xcc, 0xc5, 0x8b, 0x99, 0x8a, 0xa6, 0xba, 0x38, 0xe2, 0xd8, 0x8b, 0x17, 0xc0,
	0xe2, 0x3f, 0x52, 0x90, 0x52, 0x09, 0x64, 0x01, 0x54, 0xed, 0x3b, 0x4e, 0xcb, 0x6a, 0xe7, 0x1e,
	0xa1, 0x02, 0xe4, 0xd5, 0x7b, 0xa5, 0x61, 0x5b, 0x4e, 0x9b, 0xd8, 0x4e, 0xdb, 0xc2, 0xb8, 0x59,
	0x37, 0xdb, 0xea, 0x72, 0x52, 0x84, 0x93, 0x65, 0xaf, 0x79, 0x7d, 0x8d, 0x9b, 0x37, 0x66, 0x83,
	0x60, 0xeb, 0xf7, 0x1d, 0xab, 0x25, 0x31, 0x9b, 0xc8, 0x80, 0x82, 0xc2, 0x5c, 0x76, 0xd6, 0x23,
	0x1e, 0xa3, 0x37, 0x60, 0x68, 0x16, 0xdc, 0x74, 0xc8, 0x37, 0xcd, 0xf2, 0x3a, 0x54, 0x6a, 0xce,
	0x93, 0x5c, 0xab, 0x8e, 0x4d, 0x47, 0x22, 0xd2, 0xe8, 0x04, 0x8e, 0xd6, 0xac, 0x14, 0xfb, 0x9f,
	0x2c, 0xd4, 0xae, 0xac, 0x13, 0x63, 0x9e, 0xa2, 0x57, 0xf0, 0x52, 0x61, 0x6e, 0x6a, 0x2d, 0x52,
	0xb3, 0x1b, 0x16, 0xa9, 0x34, 0x1b, 0x0d, 0xab, 0x22, 0x9d, 0x5b, 0xe8, 0x14, 0x5e, 0xaf, 0x75,
	0xda, 0x4d, 0x87, 0xd4, 0x4c, 0xbb, 0x61, 0x55, 0x73, 0xdb, 0xe8, 0x39, 0xec, 0x2f, 0x54, 0xb4,
	0xda, 0xcd, 0xeb, 0x6b, 0xab, 0x9a, 0x03, 0xf4, 0x1a, 0x5e, 0x29, 0xb3, 0x8a, 0x33, 0x71, 0xe5,
	0xd2, 0xbe, 0xb1, 0x48, 0xdd, 0x72, 0x2c, 0xac, 0x6a, 0x99, 0x41, 0xef, 0xe0, 0xf4, 0x41, 0xc0,
	0xd2, 0x02, 0x3b, 0x73, 0x89, 0xb5, 0x46, 0xf3, 0x0f, 0x04, 0x77, 0x1c, 0x52, 0x69, 0x5e, 0x5d,
	0x37, 0x2c, 0xc9, 0xb2, 0x8b, 0xf2, 0x70, 0x70, 0xdf, 0x39, 0x0b, 0xcb, 0xa2, 0xb7, 0xf0, 0xc9,
	0x5c, 0x7c, 0xc3, 0x6e, 0xb5, 0x49, 0xd5, 0xc6, 0x56, 0xa5, 0xdd, 0xc4, 0xdf, 0x2d, 0x11, 0xec,
	0xa1, 0x73, 0xf8, 0x6c, 0x0e, 0xc3, 0x56, 0xa5, 0x83, 0x5b, 0x52, 0xc7, 0x83, 0x01, 0xb9, 0x62,
	0x19, 0xd2, 0xea, 0x34, 0xa3, 0x3d, 0xc8, 0xb4, 0xda, 0x66, 0x7b, 0x71, 0x76, 0xf6, 0x61, 0x57,
	0x1b, 0xae, 0x2d, 0xa7, 0x6a, 0x3b, 0xf5, 0xdc, 0x86, 0x2c, 0x8e, 0x36, 0x39, 0xcd, 0xf6, 0xdc,
	0xbc, 0x59, 0xbc, 0x82, 0x42, 0x9d, 0x89, 0xe4, 0x57, 0xc2, 0x31, 0xe3, 0xe3, 0x30, 0xe0, 0x0c,
	0x7d, 0x80, 0xb4, 0x9c, 0x51, 0x3c, 0xbf, 0xa1, 0x1a, 0xfb, 0xcb, 0x07, 0x3e, 0x2b, 0xac, 0x51,
	0xc5, 0x1f, 0xe1, 0xd5, 0x7a, 0xba, 0x1f, 0x27, 0x8c, 0x0b, 0x84, 0x61, 0xd7, 0xf5, 0x19, 0x8d,
	0xc8, 0x98, 0x05, 0x3d, 0x2f, 0x18, 0xe8, 0x0b, 0x6c, 0xf9, 0x83, 0xfa, 0xe6, 0xde, 0xa1, 0xb7,
	0x76, 0x5f, 0xf6, 0xe8, 0xf7, 0x86, 0x02, 0x71, 0x63, 0x86, 0x32, 0x96, 0x3f, 0x76, 0x5e, 0xc2,
	0x3b, 0xca, 0x7d, 0xad, 0x9d, 0xdd, 0x27, 0x4a, 0xd1, 0x17, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff,
	0xe1, 0x68, 0x3b, 0xbd, 0xee, 0x0d, 0x00, 0x00,
}
