// Code generated by protoc-gen-go. DO NOT EDIT.
// source: artifacts.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "www.velocidex.com/golang/velociraptor/actions/proto"
import _ "www.velocidex.com/golang/velociraptor/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Artifacts struct {
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Artifacts) Reset()         { *m = Artifacts{} }
func (m *Artifacts) String() string { return proto.CompactTextString(m) }
func (*Artifacts) ProtoMessage()    {}
func (*Artifacts) Descriptor() ([]byte, []int) {
	return fileDescriptor_artifacts_de5dcb37fc3cf243, []int{0}
}
func (m *Artifacts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artifacts.Unmarshal(m, b)
}
func (m *Artifacts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artifacts.Marshal(b, m, deterministic)
}
func (dst *Artifacts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artifacts.Merge(dst, src)
}
func (m *Artifacts) XXX_Size() int {
	return xxx_messageInfo_Artifacts.Size(m)
}
func (m *Artifacts) XXX_DiscardUnknown() {
	xxx_messageInfo_Artifacts.DiscardUnknown(m)
}

var xxx_messageInfo_Artifacts proto.InternalMessageInfo

func (m *Artifacts) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type ArtifactParameters struct {
	Env                  []*proto1.VQLEnv `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	Files                []*proto1.VQLEnv `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ArtifactParameters) Reset()         { *m = ArtifactParameters{} }
func (m *ArtifactParameters) String() string { return proto.CompactTextString(m) }
func (*ArtifactParameters) ProtoMessage()    {}
func (*ArtifactParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_artifacts_de5dcb37fc3cf243, []int{1}
}
func (m *ArtifactParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactParameters.Unmarshal(m, b)
}
func (m *ArtifactParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactParameters.Marshal(b, m, deterministic)
}
func (dst *ArtifactParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactParameters.Merge(dst, src)
}
func (m *ArtifactParameters) XXX_Size() int {
	return xxx_messageInfo_ArtifactParameters.Size(m)
}
func (m *ArtifactParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactParameters.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactParameters proto.InternalMessageInfo

func (m *ArtifactParameters) GetEnv() []*proto1.VQLEnv {
	if m != nil {
		return m.Env
	}
	return nil
}

func (m *ArtifactParameters) GetFiles() []*proto1.VQLEnv {
	if m != nil {
		return m.Files
	}
	return nil
}

type ArtifactCollectorArgs struct {
	Artifacts            *Artifacts          `protobuf:"bytes,1,opt,name=artifacts,proto3" json:"artifacts,omitempty"`
	Parameters           *ArtifactParameters `protobuf:"bytes,5,opt,name=parameters,proto3" json:"parameters,omitempty"`
	OpsPerSecond         float32             `protobuf:"fixed32,6,opt,name=ops_per_second,json=opsPerSecond,proto3" json:"ops_per_second,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ArtifactCollectorArgs) Reset()         { *m = ArtifactCollectorArgs{} }
func (m *ArtifactCollectorArgs) String() string { return proto.CompactTextString(m) }
func (*ArtifactCollectorArgs) ProtoMessage()    {}
func (*ArtifactCollectorArgs) Descriptor() ([]byte, []int) {
	return fileDescriptor_artifacts_de5dcb37fc3cf243, []int{2}
}
func (m *ArtifactCollectorArgs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactCollectorArgs.Unmarshal(m, b)
}
func (m *ArtifactCollectorArgs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactCollectorArgs.Marshal(b, m, deterministic)
}
func (dst *ArtifactCollectorArgs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactCollectorArgs.Merge(dst, src)
}
func (m *ArtifactCollectorArgs) XXX_Size() int {
	return xxx_messageInfo_ArtifactCollectorArgs.Size(m)
}
func (m *ArtifactCollectorArgs) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactCollectorArgs.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactCollectorArgs proto.InternalMessageInfo

func (m *ArtifactCollectorArgs) GetArtifacts() *Artifacts {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

func (m *ArtifactCollectorArgs) GetParameters() *ArtifactParameters {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *ArtifactCollectorArgs) GetOpsPerSecond() float32 {
	if m != nil {
		return m.OpsPerSecond
	}
	return 0
}

// This is stored in the ArtifactCollector state.
type ArtifactCompressionDict struct {
	Substs               []*proto1.VQLEnv `protobuf:"bytes,1,rep,name=substs,proto3" json:"substs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ArtifactCompressionDict) Reset()         { *m = ArtifactCompressionDict{} }
func (m *ArtifactCompressionDict) String() string { return proto.CompactTextString(m) }
func (*ArtifactCompressionDict) ProtoMessage()    {}
func (*ArtifactCompressionDict) Descriptor() ([]byte, []int) {
	return fileDescriptor_artifacts_de5dcb37fc3cf243, []int{3}
}
func (m *ArtifactCompressionDict) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactCompressionDict.Unmarshal(m, b)
}
func (m *ArtifactCompressionDict) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactCompressionDict.Marshal(b, m, deterministic)
}
func (dst *ArtifactCompressionDict) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactCompressionDict.Merge(dst, src)
}
func (m *ArtifactCompressionDict) XXX_Size() int {
	return xxx_messageInfo_ArtifactCompressionDict.Size(m)
}
func (m *ArtifactCompressionDict) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactCompressionDict.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactCompressionDict proto.InternalMessageInfo

func (m *ArtifactCompressionDict) GetSubsts() []*proto1.VQLEnv {
	if m != nil {
		return m.Substs
	}
	return nil
}

func init() {
	proto.RegisterType((*Artifacts)(nil), "proto.Artifacts")
	proto.RegisterType((*ArtifactParameters)(nil), "proto.ArtifactParameters")
	proto.RegisterType((*ArtifactCollectorArgs)(nil), "proto.ArtifactCollectorArgs")
	proto.RegisterType((*ArtifactCompressionDict)(nil), "proto.ArtifactCompressionDict")
}

func init() { proto.RegisterFile("artifacts.proto", fileDescriptor_artifacts_de5dcb37fc3cf243) }

var fileDescriptor_artifacts_de5dcb37fc3cf243 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0x95, 0x16, 0xd5, 0x83, 0x82, 0x2c, 0x21, 0x42, 0xc5, 0xc1, 0x0a, 0x42, 0x0a,
	0x1c, 0xd2, 0xd1, 0x49, 0x1c, 0x90, 0x86, 0x68, 0xbb, 0xc2, 0x65, 0xd2, 0x4a, 0x98, 0x10, 0xb7,
	0xc9, 0x4d, 0x5e, 0x5b, 0x83, 0x63, 0x7b, 0xcf, 0x6e, 0x3a, 0xbe, 0x1f, 0x27, 0x3e, 0x06, 0x5c,
	0xf8, 0x10, 0x1c, 0x50, 0x9d, 0xb6, 0x19, 0x13, 0x48, 0xcb, 0x25, 0xd1, 0xff, 0x3d, 0xff, 0xfe,
	0xff, 0xf7, 0x62, 0x72, 0x8f, 0xa3, 0x13, 0x33, 0x9e, 0x39, 0x9b, 0x18, 0xd4, 0x4e, 0xd3, 0xa6,
	0x7f, 0x75, 0x5f, 0xad, 0x56, 0xab, 0xa4, 0x04, 0xa9, 0x33, 0x91, 0xc3, 0x65, 0x92, 0xe9, 0xa2,
	0x37, 0xd7, 0x92, 0xab, 0x79, 0xaf, 0x12, 0x91, 0x1b, 0xa7, 0xb1, 0xe7, 0x9b, 0x7b, 0x16, 0x0a,
	0xae, 0x9c, 0xc8, 0x2a, 0x44, 0xf7, 0xe8, 0x66, 0x67, 0x79, 0xe6, 0x84, 0x56, 0x76, 0xc3, 0x28,
	0x2f, 0x64, 0x75, 0x3c, 0x1a, 0x91, 0xf6, 0x60, 0x1b, 0x8a, 0xbe, 0x24, 0x4d, 0xc5, 0x0b, 0xb0,
	0x61, 0xc0, 0x1a, 0x71, 0x7b, 0xc8, 0x7e, 0xfc, 0xfe, 0xf9, 0x2d, 0xe8, 0xd2, 0xf0, 0x6c, 0x01,
	0x6c, 0x17, 0x9d, 0x39, 0xcd, 0x24, 0x5f, 0xaa, 0x6c, 0x91, 0xa4, 0x55, 0x7b, 0xf4, 0x2b, 0x20,
	0x74, 0x4b, 0x99, 0x70, 0xe4, 0x05, 0x38, 0x40, 0x4b, 0x73, 0xd2, 0x00, 0x55, 0x86, 0x0d, 0xd6,
	0x88, 0xf7, 0xfb, 0x77, 0x2b, 0xc3, 0xe4, 0xe3, 0xfb, 0x93, 0xb1, 0x2a, 0x87, 0x23, 0xcf, 0x3e,
	0xa2, 0x87, 0x63, 0x55, 0x0a, 0xd4, 0xaa, 0x00, 0xe5, 0x58, 0xc9, 0x51, 0xf0, 0xa9, 0x04, 0xef,
	0x31, 0x05, 0x66, 0x50, 0x97, 0x22, 0x87, 0x9c, 0xcd, 0x34, 0x32, 0xb7, 0x00, 0x76, 0xb1, 0x04,
	0xfc, 0x9a, 0x44, 0x2d, 0x6f, 0x62, 0xd3, 0x35, 0x9e, 0x4a, 0xd2, 0x9c, 0x09, 0x09, 0x36, 0xbc,
	0xf5, 0x2f, 0x9f, 0x77, 0xde, 0x67, 0x40, 0x7b, 0x75, 0xae, 0x0d, 0x7c, 0x26, 0xa4, 0x84, 0x9c,
	0x09, 0xc5, 0x66, 0xa8, 0x0b, 0x06, 0x97, 0x46, 0xa3, 0x5b, 0x7b, 0xad, 0x61, 0x49, 0xd4, 0x19,
	0x6f, 0x85, 0xb7, 0x6b, 0x21, 0xad, 0x4c, 0xa2, 0xef, 0x7b, 0xe4, 0xc1, 0x76, 0xd4, 0x91, 0x96,
	0x12, 0x32, 0xa7, 0x71, 0x80, 0x73, 0x4b, 0x3f, 0x91, 0xf6, 0x6e, 0x47, 0x61, 0xc0, 0x82, 0x78,
	0xbf, 0x7f, 0x7f, 0x93, 0x65, 0xb7, 0xe1, 0x61, 0xec, 0xe3, 0x44, 0xff, 0x5f, 0x69, 0xd4, 0x3a,
	0xf1, 0x1f, 0x69, 0x0d, 0xa3, 0x5f, 0x08, 0x31, 0xbb, 0xf4, 0x61, 0xd3, 0xa3, 0x1f, 0x5d, 0x43,
	0xd7, 0xe3, 0x0d, 0x0f, 0xbc, 0xc7, 0x73, 0xfa, 0xf8, 0xef, 0x91, 0xdd, 0x55, 0xc7, 0x24, 0x22,
	0x75, 0x35, 0xbd, 0x82, 0xa7, 0x9f, 0x49, 0x47, 0x1b, 0x7b, 0x6e, 0x00, 0xcf, 0x2d, 0x64, 0x5a,
	0xe5, 0x61, 0x8b, 0x05, 0xf1, 0xde, 0xf0, 0xd8, 0x53, 0x5f, 0xd3, 0x27, 0xa7, 0x06, 0x90, 0xfb,
	0xcb, 0xc4, 0x0c, 0x20, 0xab, 0x9a, 0x58, 0x7c, 0xb6, 0x40, 0xed, 0x9c, 0x14, 0x6a, 0xfe, 0x2c,
	0x89, 0x3a, 0xa7, 0xc6, 0xb2, 0x09, 0x20, 0xfb, 0xe0, 0xab, 0xfd, 0xdb, 0x2f, 0x0e, 0xfc, 0x93,
	0xde, 0xd1, 0xc6, 0x4e, 0x00, 0x2b, 0x39, 0x7a, 0x43, 0x1e, 0xd6, 0xbb, 0x2c, 0x0c, 0x82, 0xb5,
	0x42, 0xab, 0x63, 0x91, 0x39, 0xfa, 0x94, 0xb4, 0xec, 0x72, 0x6a, 0x5d, 0x75, 0x17, 0xaf, 0xff,
	0xd6, 0x74, 0x53, 0x9c, 0xb6, 0xbc, 0x7a, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xdc, 0x28,
	0xc2, 0x5a, 0x03, 0x00, 0x00,
}
