// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vfs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	proto1 "www.velocidex.com/golang/velociraptor/actions/proto"
	_ "www.velocidex.com/golang/velociraptor/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VFSDownloadInfo struct {
	VfsPath              string   `protobuf:"bytes,1,opt,name=vfs_path,json=vfsPath,proto3" json:"vfs_path,omitempty"`
	Size                 uint64   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mtime                uint64   `protobuf:"varint,3,opt,name=mtime,proto3" json:"mtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VFSDownloadInfo) Reset()         { *m = VFSDownloadInfo{} }
func (m *VFSDownloadInfo) String() string { return proto.CompactTextString(m) }
func (*VFSDownloadInfo) ProtoMessage()    {}
func (*VFSDownloadInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_3498b34ebe55a2be, []int{0}
}

func (m *VFSDownloadInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VFSDownloadInfo.Unmarshal(m, b)
}
func (m *VFSDownloadInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VFSDownloadInfo.Marshal(b, m, deterministic)
}
func (m *VFSDownloadInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VFSDownloadInfo.Merge(m, src)
}
func (m *VFSDownloadInfo) XXX_Size() int {
	return xxx_messageInfo_VFSDownloadInfo.Size(m)
}
func (m *VFSDownloadInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VFSDownloadInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VFSDownloadInfo proto.InternalMessageInfo

func (m *VFSDownloadInfo) GetVfsPath() string {
	if m != nil {
		return m.VfsPath
	}
	return ""
}

func (m *VFSDownloadInfo) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *VFSDownloadInfo) GetMtime() uint64 {
	if m != nil {
		return m.Mtime
	}
	return 0
}

type VFSListResponse struct {
	Response  string               `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	Columns   []string             `protobuf:"bytes,2,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Query     *proto1.VQLRequest   `protobuf:"bytes,3,opt,name=Query,proto3" json:"Query,omitempty"`
	Timestamp uint64               `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalRows uint64               `protobuf:"varint,7,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	Types     []*proto1.VQLTypeMap `protobuf:"bytes,8,rep,name=types,proto3" json:"types,omitempty"`
	// The actual artifact that contains the data.
	ClientId             string   `protobuf:"bytes,9,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlowId               string   `protobuf:"bytes,10,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VFSListResponse) Reset()         { *m = VFSListResponse{} }
func (m *VFSListResponse) String() string { return proto.CompactTextString(m) }
func (*VFSListResponse) ProtoMessage()    {}
func (*VFSListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3498b34ebe55a2be, []int{1}
}

func (m *VFSListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VFSListResponse.Unmarshal(m, b)
}
func (m *VFSListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VFSListResponse.Marshal(b, m, deterministic)
}
func (m *VFSListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VFSListResponse.Merge(m, src)
}
func (m *VFSListResponse) XXX_Size() int {
	return xxx_messageInfo_VFSListResponse.Size(m)
}
func (m *VFSListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VFSListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VFSListResponse proto.InternalMessageInfo

func (m *VFSListResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *VFSListResponse) GetColumns() []string {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *VFSListResponse) GetQuery() *proto1.VQLRequest {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *VFSListResponse) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *VFSListResponse) GetTotalRows() uint64 {
	if m != nil {
		return m.TotalRows
	}
	return 0
}

func (m *VFSListResponse) GetTypes() []*proto1.VQLTypeMap {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *VFSListResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VFSListResponse) GetFlowId() string {
	if m != nil {
		return m.FlowId
	}
	return ""
}

type VFSListRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	VfsPath              string   `protobuf:"bytes,2,opt,name=vfs_path,json=vfsPath,proto3" json:"vfs_path,omitempty"`
	RecursionDepth       uint64   `protobuf:"varint,3,opt,name=recursion_depth,json=recursionDepth,proto3" json:"recursion_depth,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VFSListRequest) Reset()         { *m = VFSListRequest{} }
func (m *VFSListRequest) String() string { return proto.CompactTextString(m) }
func (*VFSListRequest) ProtoMessage()    {}
func (*VFSListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3498b34ebe55a2be, []int{2}
}

func (m *VFSListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VFSListRequest.Unmarshal(m, b)
}
func (m *VFSListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VFSListRequest.Marshal(b, m, deterministic)
}
func (m *VFSListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VFSListRequest.Merge(m, src)
}
func (m *VFSListRequest) XXX_Size() int {
	return xxx_messageInfo_VFSListRequest.Size(m)
}
func (m *VFSListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VFSListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VFSListRequest proto.InternalMessageInfo

func (m *VFSListRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VFSListRequest) GetVfsPath() string {
	if m != nil {
		return m.VfsPath
	}
	return ""
}

func (m *VFSListRequest) GetRecursionDepth() uint64 {
	if m != nil {
		return m.RecursionDepth
	}
	return 0
}

type VFSListRequestState struct {
	VfsPath              string              `protobuf:"bytes,1,opt,name=vfs_path,json=vfsPath,proto3" json:"vfs_path,omitempty"`
	Accessor             string              `protobuf:"bytes,3,opt,name=accessor,proto3" json:"accessor,omitempty"`
	Current              *proto1.VQLResponse `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *VFSListRequestState) Reset()         { *m = VFSListRequestState{} }
func (m *VFSListRequestState) String() string { return proto.CompactTextString(m) }
func (*VFSListRequestState) ProtoMessage()    {}
func (*VFSListRequestState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3498b34ebe55a2be, []int{3}
}

func (m *VFSListRequestState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VFSListRequestState.Unmarshal(m, b)
}
func (m *VFSListRequestState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VFSListRequestState.Marshal(b, m, deterministic)
}
func (m *VFSListRequestState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VFSListRequestState.Merge(m, src)
}
func (m *VFSListRequestState) XXX_Size() int {
	return xxx_messageInfo_VFSListRequestState.Size(m)
}
func (m *VFSListRequestState) XXX_DiscardUnknown() {
	xxx_messageInfo_VFSListRequestState.DiscardUnknown(m)
}

var xxx_messageInfo_VFSListRequestState proto.InternalMessageInfo

func (m *VFSListRequestState) GetVfsPath() string {
	if m != nil {
		return m.VfsPath
	}
	return ""
}

func (m *VFSListRequestState) GetAccessor() string {
	if m != nil {
		return m.Accessor
	}
	return ""
}

func (m *VFSListRequestState) GetCurrent() *proto1.VQLResponse {
	if m != nil {
		return m.Current
	}
	return nil
}

type VFSDownloadFileRequest struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	VfsPath              []string `protobuf:"bytes,2,rep,name=vfs_path,json=vfsPath,proto3" json:"vfs_path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VFSDownloadFileRequest) Reset()         { *m = VFSDownloadFileRequest{} }
func (m *VFSDownloadFileRequest) String() string { return proto.CompactTextString(m) }
func (*VFSDownloadFileRequest) ProtoMessage()    {}
func (*VFSDownloadFileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3498b34ebe55a2be, []int{4}
}

func (m *VFSDownloadFileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VFSDownloadFileRequest.Unmarshal(m, b)
}
func (m *VFSDownloadFileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VFSDownloadFileRequest.Marshal(b, m, deterministic)
}
func (m *VFSDownloadFileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VFSDownloadFileRequest.Merge(m, src)
}
func (m *VFSDownloadFileRequest) XXX_Size() int {
	return xxx_messageInfo_VFSDownloadFileRequest.Size(m)
}
func (m *VFSDownloadFileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VFSDownloadFileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VFSDownloadFileRequest proto.InternalMessageInfo

func (m *VFSDownloadFileRequest) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *VFSDownloadFileRequest) GetVfsPath() []string {
	if m != nil {
		return m.VfsPath
	}
	return nil
}

type ClientMonitoringState struct {
	Version              uint64   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	LastUpdateTimestamp  uint64   `protobuf:"varint,2,opt,name=last_update_timestamp,json=lastUpdateTimestamp,proto3" json:"last_update_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientMonitoringState) Reset()         { *m = ClientMonitoringState{} }
func (m *ClientMonitoringState) String() string { return proto.CompactTextString(m) }
func (*ClientMonitoringState) ProtoMessage()    {}
func (*ClientMonitoringState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3498b34ebe55a2be, []int{5}
}

func (m *ClientMonitoringState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientMonitoringState.Unmarshal(m, b)
}
func (m *ClientMonitoringState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientMonitoringState.Marshal(b, m, deterministic)
}
func (m *ClientMonitoringState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientMonitoringState.Merge(m, src)
}
func (m *ClientMonitoringState) XXX_Size() int {
	return xxx_messageInfo_ClientMonitoringState.Size(m)
}
func (m *ClientMonitoringState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientMonitoringState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientMonitoringState proto.InternalMessageInfo

func (m *ClientMonitoringState) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ClientMonitoringState) GetLastUpdateTimestamp() uint64 {
	if m != nil {
		return m.LastUpdateTimestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*VFSDownloadInfo)(nil), "proto.VFSDownloadInfo")
	proto.RegisterType((*VFSListResponse)(nil), "proto.VFSListResponse")
	proto.RegisterType((*VFSListRequest)(nil), "proto.VFSListRequest")
	proto.RegisterType((*VFSListRequestState)(nil), "proto.VFSListRequestState")
	proto.RegisterType((*VFSDownloadFileRequest)(nil), "proto.VFSDownloadFileRequest")
	proto.RegisterType((*ClientMonitoringState)(nil), "proto.ClientMonitoringState")
}

func init() {
	proto.RegisterFile("vfs.proto", fileDescriptor_3498b34ebe55a2be)
}

var fileDescriptor_3498b34ebe55a2be = []byte{
	// 691 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x6e, 0x13, 0x3d,
	0x14, 0xd5, 0x24, 0x69, 0x93, 0xb8, 0xfa, 0x5a, 0x7d, 0x6e, 0x4b, 0x87, 0xf0, 0x53, 0x13, 0xd1,
	0xa6, 0x42, 0x25, 0x29, 0xad, 0x58, 0x82, 0xd0, 0xb4, 0x8a, 0x88, 0xd4, 0x22, 0x3a, 0x6d, 0xb3,
	0x60, 0x41, 0x30, 0x33, 0x37, 0x8d, 0xa5, 0x89, 0x3d, 0xb5, 0x9d, 0x0c, 0xe9, 0x33, 0xf0, 0x12,
	0x3c, 0x07, 0x5b, 0x9e, 0x04, 0x5e, 0x82, 0x05, 0x0b, 0x64, 0x3b, 0xbf, 0x20, 0xb1, 0x1a, 0xdf,
	0x7b, 0xae, 0xcf, 0x3d, 0x3e, 0xbe, 0x1e, 0x54, 0x1e, 0x76, 0x55, 0x3d, 0x95, 0x42, 0x0b, 0xbc,
	0x64, 0x3f, 0x95, 0x0d, 0xfb, 0x69, 0x28, 0xe8, 0x53, 0xae, 0x59, 0xe4, 0xc0, 0xca, 0x16, 0x8d,
	0x34, 0x13, 0x5c, 0x35, 0x1c, 0x3a, 0xbc, 0x49, 0x1c, 0x50, 0x6d, 0xa3, 0xb5, 0x76, 0xf3, 0xe2,
	0x44, 0x64, 0x3c, 0x11, 0x34, 0x6e, 0xf1, 0xae, 0xc0, 0x77, 0x51, 0x69, 0xd8, 0x55, 0x9d, 0x94,
	0xea, 0x9e, 0xef, 0x11, 0x6f, 0xaf, 0x1c, 0x16, 0x87, 0x5d, 0xf5, 0x96, 0xea, 0x1e, 0xc6, 0xa8,
	0xa0, 0xd8, 0x2d, 0xf8, 0x39, 0xe2, 0xed, 0x15, 0x42, 0xbb, 0xc6, 0x1b, 0x68, 0xa9, 0xaf, 0x59,
	0x1f, 0xfc, 0xbc, 0x4d, 0xba, 0xa0, 0xfa, 0x39, 0x67, 0x89, 0x4f, 0x99, 0xd2, 0x21, 0xa8, 0x54,
	0x70, 0x05, 0xb8, 0x82, 0x4a, 0x93, 0xf5, 0x98, 0x78, 0x1a, 0x63, 0x1f, 0x15, 0x8f, 0x45, 0x32,
	0xe8, 0x73, 0xe5, 0xe7, 0x48, 0xde, 0xf4, 0x1c, 0x87, 0xb8, 0x86, 0x96, 0xce, 0x07, 0x20, 0x47,
	0x96, 0x7f, 0xe5, 0xf0, 0x7f, 0x27, 0xbc, 0xde, 0x3e, 0x3f, 0x0d, 0xe1, 0x66, 0x00, 0x4a, 0x87,
	0x0e, 0xc7, 0xf7, 0x51, 0xd9, 0xb4, 0x56, 0x9a, 0xf6, 0x53, 0xbf, 0x60, 0xc5, 0xcc, 0x12, 0xf8,
	0x01, 0x42, 0x5a, 0x68, 0x9a, 0x74, 0xa4, 0xc8, 0x94, 0x5f, 0x1c, 0xc3, 0x26, 0x13, 0x8a, 0xcc,
	0x76, 0xd1, 0xa3, 0x14, 0x94, 0x5f, 0x22, 0xf9, 0xc5, 0x2e, 0x97, 0xa3, 0x14, 0xce, 0x68, 0x1a,
	0x3a, 0x1c, 0xdf, 0x43, 0xe5, 0x28, 0x61, 0xc0, 0x75, 0x87, 0xc5, 0x7e, 0xd9, 0x9d, 0xc2, 0x25,
	0x5a, 0x31, 0xde, 0x42, 0xc5, 0x6e, 0x22, 0x32, 0x03, 0x21, 0x0b, 0x2d, 0x9b, 0xb0, 0x15, 0x57,
	0x7f, 0x7a, 0x68, 0x75, 0x6a, 0x87, 0x55, 0x8d, 0x83, 0x79, 0x22, 0x6b, 0x47, 0xb0, 0xf3, 0xfd,
	0xd7, 0x8f, 0x6f, 0xde, 0x36, 0x5a, 0x0e, 0x4f, 0x9a, 0x57, 0xe1, 0x1b, 0x8c, 0x2f, 0x7b, 0x40,
	0x5c, 0x11, 0xd1, 0x82, 0x24, 0x4c, 0xe9, 0x8a, 0x97, 0x9b, 0xeb, 0x17, 0xcc, 0x5d, 0x55, 0xce,
	0x52, 0xd4, 0x2c, 0xc5, 0x23, 0xbc, 0x6d, 0xb6, 0xb6, 0x9b, 0x17, 0xc4, 0xdc, 0xdb, 0x64, 0x33,
	0xe9, 0xb2, 0x04, 0x14, 0x61, 0x9c, 0xd4, 0x67, 0x77, 0xfa, 0x1e, 0xad, 0x49, 0x88, 0x06, 0x52,
	0x31, 0xc1, 0x3b, 0x31, 0xa4, 0xba, 0xe7, 0x6e, 0x32, 0x78, 0x6e, 0xa9, 0x1a, 0xf8, 0x49, 0xab,
	0x4b, 0x5e, 0x92, 0x03, 0xa2, 0x7b, 0xc0, 0x89, 0x2b, 0x05, 0xa2, 0x7b, 0x4c, 0x91, 0x3e, 0xe5,
	0x23, 0x12, 0x33, 0x09, 0x91, 0x16, 0x92, 0x81, 0xaa, 0x1f, 0x7a, 0x07, 0xe1, 0xea, 0x94, 0xed,
	0xc4, 0x90, 0x55, 0x6f, 0xd1, 0xfa, 0xe2, 0xc9, 0x2f, 0x34, 0xd5, 0xf0, 0xaf, 0x29, 0xab, 0xa0,
	0x12, 0x8d, 0x22, 0x50, 0x4a, 0x48, 0x2b, 0xa5, 0x1c, 0x4e, 0x63, 0xbc, 0x8f, 0x8a, 0xd1, 0x40,
	0x4a, 0xe0, 0xda, 0x1e, 0x78, 0xe5, 0x10, 0xcf, 0xcf, 0x83, 0x1b, 0xa6, 0x70, 0x52, 0x52, 0xfd,
	0xe2, 0xa1, 0x3b, 0x73, 0xe3, 0xdd, 0x64, 0x09, 0x4c, 0xec, 0x7f, 0xf1, 0xb7, 0xfd, 0xc4, 0x1e,
	0xb8, 0x32, 0xb5, 0xff, 0xbf, 0x39, 0xfb, 0x59, 0xbc, 0xe8, 0xfc, 0xeb, 0x05, 0xe7, 0xf3, 0x7b,
	0xe5, 0xe0, 0xa9, 0xdd, 0x5d, 0xc3, 0x3b, 0x7f, 0x3a, 0xaf, 0x7b, 0x60, 0x8d, 0x37, 0xeb, 0x78,
	0xac, 0x64, 0xe6, 0x7f, 0xf5, 0xab, 0x87, 0x36, 0x8f, 0x2d, 0xed, 0x99, 0xe0, 0xcc, 0x18, 0xc9,
	0xaf, 0x9d, 0x45, 0xaf, 0x50, 0x71, 0x08, 0xd6, 0x49, 0x2b, 0xb0, 0x10, 0xec, 0xda, 0x16, 0x04,
	0x3f, 0x9c, 0x09, 0xab, 0x29, 0x22, 0x21, 0x15, 0x52, 0x43, 0x4c, 0xc6, 0xc5, 0x86, 0xdb, 0xad,
	0xf0, 0x07, 0xb4, 0x99, 0x50, 0xa5, 0x3b, 0x83, 0x34, 0xa6, 0x1a, 0x3a, 0xb3, 0xe7, 0x61, 0x1f,
	0x70, 0xb0, 0x6f, 0xf9, 0x76, 0xf1, 0x63, 0xc3, 0x67, 0x0a, 0x89, 0xa9, 0x20, 0x19, 0x10, 0xb7,
	0x21, 0xb6, 0xda, 0x5d, 0xa3, 0x7a, 0xb8, 0x6e, 0x2a, 0xae, 0x2c, 0x70, 0x39, 0x21, 0x0a, 0x8e,
	0xde, 0x3d, 0xcb, 0xb2, 0xac, 0x3e, 0x84, 0x44, 0x44, 0x2c, 0x86, 0x4f, 0xf5, 0x48, 0xf4, 0x1b,
	0xd7, 0x22, 0xa1, 0xfc, 0xba, 0xe1, 0x92, 0x92, 0xa6, 0x5a, 0xc8, 0x86, 0x79, 0x08, 0xe3, 0xdf,
	0xcf, 0xc7, 0x65, 0xfb, 0x39, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x32, 0xda, 0xfc, 0x77, 0xbe,
	0x04, 0x00, 0x00,
}
