version:
  name: velociraptor
  version: 0.3.2
  commit: 955a711
  build_time: "2019-07-29T09:23:04+10:00"
Client:
  server_urls:
  - https://localhost:8000/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDKjCCAhKgAwIBAgIQad4ruc2Meq0mj+0H39ModTANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMTkwNzI5MTQ0MjQxWhcNMjAw
    NzI4MTQ0MjQxWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDM1Z0+c4QxWRRu1e1+RXpnXH4Q/WRdZDDM
    Bn7E8xS8TigEbyY/AZVDjNqE2lD3q39bsbvr7jheh7V5tI5lXtw53fwj6ifxQ6za
    Z6pcxwwUatfxxpEA4jwpK+76FAdKoOWB1STfEmrXhNAutSq2um9UinoOD/4+6zA6
    PQ/JbL6aFqUHiK/4l1pAZG4T9FShpWJOPeYz/AdrnXwfkfsrw2v7y8TCw90MIyeO
    HMML1JrCdDs4zJ+KqOK2gLYuYNfHoqdHbfVxH+s3HnCoBftQhcAbQyXpoBdxs0K3
    KhbxLfpKt4PJau/mo2iszWUiyyUWah5CU8WX7nRbMtpYa6KiQqJ3AgMBAAGjbDBq
    MA4GA1UdDwEB/wQEAwICpDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    DwYDVR0TAQH/BAUwAwEB/zAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVs
    b2NpZGV4LmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAtmNQHR7L/JRMe+09kdu3gW8c
    JxDxAvqTRgTNIc8GE4xAZJuDDsXC5N7+DPnYf3WlJ405wbV8lUkjbdnCC2/mUiOK
    1XAaTaQuEhiRTnmItNhdSckY+fFdTMxLrp0SBaTXYi7sdbyTegTbsd/RV5+4pdaQ
    Hk5ZHJACYvZMh1qNYxExcQ9mNks4pa0/Sb8hgyg1E9tCaNKrb99GPAqsHPcOCYLH
    lveOsf4CJ/ZsQ3MIOyGuH4JLk3EogkZoF/hbZgQiGOGJDURxBtoI5JJhNSLZulM0
    c0ALmzuxLX5Vhzac/fHyTE55NBd6Y+BG/5JHJcP9ctmSqjsf9pn0FA7c5X9e3A==
    -----END CERTIFICATE-----
  nonce: Tjg4PBVsO24=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  max_poll: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  max_upload_size: 5242880
API:
  bind_address: 127.0.0.1
  bind_port: 8001
  bind_scheme: tcp
GUI:
  bind_address: 127.0.0.1
  bind_port: 8889
  gw_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIC/TCCAeWgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQKEw9WZWxv
    Y2lyYXB0b3IgQ0EwHhcNMTkwNzI5MTQ0MjQyWhcNMjAwNzI4MTQ0MjQyWjApMRUw
    EwYDVQQKEwxWZWxvY2lyYXB0b3IxEDAOBgNVBAMMB0dSUENfR1cwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCpQxgYx78FikNHO9qGsQ++o5P2ffZT10+8
    xxppwuLBMt8dmsf5ab7HYzNPJ4DZiR5mMe/Vh4RyWIgEe2Dhb+Y904/ixeLzqpb/
    MCIVLMOloQTNbHm1KZK2c2pAudjh22gZ4pXAwCmIovcxHvcP37QULuoxCipu5rsE
    9FR7nrmslYiNTdIVL5XQ5qoPthguTlZU4eOcDR2LiW1c84sWVrl66QBu598mkSR4
    WEFg95mVuIe5hk0DmjT6YqVOVdOssteq1UqfJxTx7lNxEfM0MWAxiW1tuW1BRiXI
    wERrTwyXNMMS5fkirmjzQ0VyzLkQWOb4HCb7fowYJ81GOMdgdpunAgMBAAGjPzA9
    MA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw
    DAYDVR0TAQH/BAIwADANBgkqhkiG9w0BAQsFAAOCAQEAoVBn1Xhkn1kk8BLleGDt
    e8lCQOVRG2CxGG+rxdz0XDee5GwQ7M2U2tlLSzSSmPTrgNVdB4p+KjdBR+ak7pSK
    Eg6RfWI3mlGx+HmNiWfO8TFuedhNldsrmFk2wQQzBspdp9TY/M3eyxYR0S4TQEAq
    h4xNNkAt+wju4h9m6dqllkOCIW9ydT/EQqCVAhE8Q7iuZYWENRjqCgSc76S8Pbru
    kL85b0zj/X221YiKUwrFLgFHFSvmWXKjk42Ugdjlc5CArCYzrLduAgUObx+SoG4/
    yk8y+rEzkDYI1OPR6gwwieY6xuGlZ3SjU3twtS1l5NRv0mqIOXGQSxEAq4oJ1zSu
    Tg==
    -----END CERTIFICATE-----
  gw_private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAqUMYGMe/BYpDRzvahrEPvqOT9n32U9dPvMcaacLiwTLfHZrH
    +Wm+x2MzTyeA2YkeZjHv1YeEcliIBHtg4W/mPdOP4sXi86qW/zAiFSzDpaEEzWx5
    tSmStnNqQLnY4dtoGeKVwMApiKL3MR73D9+0FC7qMQoqbua7BPRUe565rJWIjU3S
    FS+V0OaqD7YYLk5WVOHjnA0di4ltXPOLFla5eukAbuffJpEkeFhBYPeZlbiHuYZN
    A5o0+mKlTlXTrLLXqtVKnycU8e5TcRHzNDFgMYltbbltQUYlyMBEa08MlzTDEuX5
    Iq5o80NFcsy5EFjm+Bwm+36MGCfNRjjHYHabpwIDAQABAoIBAQCZuNWpq79QyMFR
    cIqGyUgDW4yF0OBmRKWmTS0v4E8QJ6N6v5febKtXakCvIrFi36U8Kx4mT216a+0c
    JPFXzMjOXdXPnuj/Y26/VHefw4fsZNB3wIzIe3lDOo7FOgQ/G4Tv/VkENYGDFn5p
    njXDtOdXbURERXdEQUiYt04C96Spl6n1/Stnib7syYLzZpJdRjdYxSq+VSE5TKfx
    1c4Dscn7GQvJ/Tks4HOa3MLwnarYJ9oPOGC1sy4smVRAW2ssC96Q0NiiIvBQKTUI
    WLDJbHKCPZGrswoHKgTgSjzjfhLYPzXlfhjBG58+39thlpQZ4ljGd3o5iBe05bpg
    c3kSF6wBAoGBAMKZsYZVz+wswvhQF+Pj75qJHyNa9RuBync+rihQLHhQi4OtJuY1
    S1PjyZuUUUo+2970s2cD41y2L0KO0Z7QLaXhnuM1gB07IZedw8y7/KaB90Dyia8h
    0WNU8uXRSmXSb9zh4FLdg9GMwUbTSgRj2xVhkrJIawN7oHgjw8aCZLajAoGBAN6q
    xXFNLwzHVmnqqBbR+Mug1XRD2NXu2PgNNswXpT2rUMubulo04O06eVLizmGNAm4s
    y8+BAUnQ1LCJ6MSFBfmB/T66mazlfFU2V9BwX2jUzP7iZFz6WKFgMXEfi5Mg6BKg
    jr2r5EI6d/jWEv2v1fZMa3LWTP2dFxhGC3c1iIstAoGBAJDt+EntFQp3F8nplLFT
    6/nyz678KfoPguOmWfyKIWSF0DIEPilLXcufpWHqZ1RdVlFJe2dofOdqg+4VAcc+
    khCt5TCggsbCaDVL+Sw8gWDdAHFtcN9u10wcUz6XzcnhnRArZW8xrN/e7X87EzAL
    0nmtDp0a1CBm7U8si70HFczzAoGAVzncmLLcsIvSDTHQYQgmB1bc52vAoKWtNxau
    FatZntvijbBWgwnd5vCWIGMa59n+TrybppDpuUnmV7XeikV1/rTuSMl+c91+JD9i
    jRPIPF/IYjy7hjTHzYfKNn9eBOfKIanl4OVaSJtw7fimfdyI27A6E0Vh6aPFLUwb
    J7q/340CgYEAlUV35kNOzcjV6tr7XC3c/yQpUqsTUP8sgKUtDe+1TyAa7OFwRwzb
    xpQmweNeMxbgh6+AQz/Wbp1Xyas8nqvTnZTgudXvSJArpuNFZkKN5cbZaK4yjRLh
    o9a+ck98n3QumBmJC8TqmCaklx65pu+Yly2MP20q1WL6jWmsuglQ5rI=
    -----END RSA PRIVATE KEY-----
  internal_cidr:
  - 127.0.0.1/12
  - 192.168.0.0/16
CA:
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAzNWdPnOEMVkUbtXtfkV6Z1x+EP1kXWQwzAZ+xPMUvE4oBG8m
    PwGVQ4zahNpQ96t/W7G76+44Xoe1ebSOZV7cOd38I+on8UOs2meqXMcMFGrX8caR
    AOI8KSvu+hQHSqDlgdUk3xJq14TQLrUqtrpvVIp6Dg/+PuswOj0PyWy+mhalB4iv
    +JdaQGRuE/RUoaViTj3mM/wHa518H5H7K8Nr+8vEwsPdDCMnjhzDC9SawnQ7OMyf
    iqjitoC2LmDXx6KnR231cR/rNx5wqAX7UIXAG0Ml6aAXcbNCtyoW8S36SreDyWrv
    5qNorM1lIsslFmoeQlPFl+50WzLaWGuiokKidwIDAQABAoIBAAnTlZ+RWx4i7+AB
    U0tjeePLhCC8hzwTumOPTDWWk8AU38aWrncHVGnRMAp/jrLS/2Eeva0r2HhwejxE
    dTBXxKjiBV6TtSbV4Ez5/CpHQkUYexOWOw6Xy9sNyIEmxNLHtTrtRr+M2qNMM9CJ
    0GrDtuOPYRubmM7b6YxhsYgwN1Sc+3AM4zOO15FJysOz5KZdQzmhn+wTqroZzhXY
    88A1izkLDOQBivINGITSHYSrJLXQTOdd2+Guwa3dT9G82mtnv3NAwrnyHaADuAB8
    80DbbooUT6faaCaIeIfhqR90Mb5vQfjoJnJYc6KqxQ5gZ1QLN8RQXL/8tkqpwD90
    ta408YECgYEA0f8M63UsdkOsSruSmZQeH6sL9gkfEfHkA/ztAhuaicwrMWMYagzj
    l24MHWJ7XoTDDDKWfCZSVEIYIv6jefdk01jKkNKE0nUgond6mX198EJVoQ7ZqRjX
    TmSgOghQRm75U5hMP9G5A7KiOsmvTjEv59wG5ZxljVbqXWZcWvl4KCkCgYEA+bUT
    7iqpK6Fpo9/7bqfBGv3/AKO7Lvr75ZlHCo5tAEP2E8a36UJWzdommq/PBr+QZHdU
    fVKJF4YUFORyxLapE4ZlrLRb8ibZU2JMiwqBrDkaUwJXsV1eT31aOp7TLsJBvOF5
    77c0Kr+sKkE2u9NuqmMIZDAt2LygMKIvboF+SZ8CgYEApTkzhR7QOMzOBo7Grado
    fCosYwySMaBMcwbRw9LMKJdHdLgvQWGawE6JoaUWxCtY+4Ph+xR7ume2bfJD1Xbd
    EZzO5Ft+vcgCQVIYWCPwrtTCYtI4V1+AJ+HsXzyjTIeMDEXL2Hq+QzaNhguhrrfs
    pVTs6EPBcw9rnskm6T1XWOECgYB6yluBm4LSzK3pAsReNqnTvyD9TIZIZO0ni0cO
    3tik78Z7FRXs401SLrsbB+by95JmhPOMKOD3K1yGpYv2RahAzK8EzTAFlKr7wPPI
    z6LScMYMGbPLqREuX4LWHrHUZXv0CKBwi5Ngjh54LNdgZ2kc6lP/CF4THTZck/Rl
    D9JtGwKBgQCXYKlKSWvUiDLmZH9S4kCD6nYSQJBB1Zbdf+5DjlJjIEfiFA/ecgfr
    pZwMaHBIdCH6zW3gH6IQirbZ0e+N9Zf4RkQNL3rJKXVs7Se5YFB7F/vNWPcSXnqx
    2DyzC7t9mILP2BAJGYEC2ag++7m1HuCgA3GfBGd81SHH1ScGvXCi+A==
    -----END RSA PRIVATE KEY-----
Frontend:
  bind_address: 0.0.0.0
  bind_port: 8000
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDCDCCAfCgAwIBAgIBATANBgkqhkiG9w0BAQsFADAaMRgwFgYDVQQKEw9WZWxv
    Y2lyYXB0b3IgQ0EwHhcNMTkwNzI5MTQ0MjQyWhcNMjAwNzI4MTQ0MjQyWjA0MRUw
    EwYDVQQKEwxWZWxvY2lyYXB0b3IxGzAZBgNVBAMTElZlbG9jaXJhcHRvclNlcnZl
    cjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAOyTlxSDEBjzkPVtipmK
    G37QeIiKggG0VZh/r8go+IHMeVTjpdBWaaTQ5uUP/X06urMCawipZt9qRQsWe7Fw
    G3J8LBC2SGhSqXDldyqdweM7NrYbBoll0U+VRZp16EDBc2El8RXT0BjXKVMv08xW
    qJPz44Dk7/g7eD/6hzcQ5YCldVsewUSVdrvA9YtZhAaYQk39nRuGpyq4xGTQDERt
    Lkx9RnX5VZjnRBW4oziGgDymZlJuyaZoAxmClSsyqw/TRll0hhOeOviH96oL23Dh
    RN6POAzyG0+/kq9yWGfTpk4XPWDmohbfamx+1hc4F9Nx0sqs/EW/nPpsnSjnAfoH
    U9ECAwEAAaM/MD0wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMB
    BggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IBAQBVVcu8
    dSUcbjP73QqdCBF7XT39re4sZ0dscO9Bh76Z7TZzVuVzuJfihj1Y10akYL0w7gxA
    OVLjKa3KxHwOWJFCJrbg+T36GI8afvqkOmdbTznxH0FsGuxntb9a7TtcIbVTw1M3
    qGtEQa43TNDcrIKUPLhnM/fIR437iiV5Ih7cuBbEVq1EKc5g4X70Xhcr7QWnYzJd
    k8uFo+eo6b8Uh53elXahZaeQrVM1QwbPeGhlK0t+dxQfSqWfLPi906NKlr9bGFsJ
    Gu68Cn/suZ+yZl9kXoivtcLhj3+kM1kdpnwrkOxqAlYM+YudAu3R6O+ViEE15G87
    203/xci7bJIli58O
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEA7JOXFIMQGPOQ9W2KmYobftB4iIqCAbRVmH+vyCj4gcx5VOOl
    0FZppNDm5Q/9fTq6swJrCKlm32pFCxZ7sXAbcnwsELZIaFKpcOV3Kp3B4zs2thsG
    iWXRT5VFmnXoQMFzYSXxFdPQGNcpUy/TzFaok/PjgOTv+Dt4P/qHNxDlgKV1Wx7B
    RJV2u8D1i1mEBphCTf2dG4anKrjEZNAMRG0uTH1GdflVmOdEFbijOIaAPKZmUm7J
    pmgDGYKVKzKrD9NGWXSGE546+If3qgvbcOFE3o84DPIbT7+Sr3JYZ9OmThc9YOai
    Ft9qbH7WFzgX03HSyqz8Rb+c+mydKOcB+gdT0QIDAQABAoIBAH5Qj2o0UHQCGHPy
    eP5h7yxWwwSkb6XZU5qJEqIcvhMPyfi5U99ZRC7sG1xSnVYv9V9++wc06+h+JT82
    UfT7lqwaAK0rpp2NBUtyOZ5XfR6Gjz/MTkEuTAPh/7fpHIj2wVQtnfu5jHK27ymr
    b7q6yme04NQBaN9xYVNHwMp2CxQUPSs3AiAuqTqRm8hmhh4py4EtwFQv/4S5Cq2V
    LjjSFhOmiADt33/yAbRLBI0HKLOMqVLqfMbfP46T17LoOEaW5x/1eWuPNcUoIB0m
    TJl2kHgXN0uJoU9A0Fk7xMIqT7xaDLf6KDtf+APnbsDrs5reY+UilfiaIaQCf6Cx
    VyxtpMECgYEA8VDImwnwQ0032toDwW1P2Ai31n0aFiyjg1q491rCNNud14rwVxhQ
    YQ3ZT5oyZxAmn9zuBs4uvpR5SJeRbTU7Pyt9ZL+Ygf1pbu6TsjI/WlfkZCajNayF
    kVonPo095kZFTHunmSrGZ18Lg1LAvUt+O2H1YkiQYORTjYVX3sEEjocCgYEA+vj7
    VXeCIexKbuY6JVvyTwiR98SU7GDQqf1VCN7lgpZ47LKwQ1jHkd2FtvCIYVGRAVdG
    Wk3ktOigIzTuxHnpg+kLbd/1F0urMjCYR65Htfpg+GaYFGUN/s0vuYhNR2oxKF1p
    aEgpBhFRPaLpcxCKXiSpH1moT+HcZlqCcCT1iOcCgYEAxeoRfUabbTdJlg60gdGb
    aH1N+XZFDOazfKnNheFD4oI0ZHEpSOVCFzd6gVTf/bM7WmWiOqajo9610hmtRjog
    S2DpyNVyyToDXN4C+GVJnFj1kkY2GXFTYrDj+uNwXwpHD8Fi5bY1XtaO5LfcJ+Rg
    tWdUD7Wf5DefZzRzqtf3WsUCgYAtXS/g5PcqtpFFtmuwMQx9aKkpxei9SUquT1I9
    hjyp/BTjg/EEW1nHbekrhhLAtIOnYGUhEY9Te/DmLD00WmzxIQCl3aNpkI3jRpFf
    84qWxCke/TxkA1giRGhp+s8tJ263Qxs4dEKmDB9JKtdTqxu3pJzFQ+l+du7luVp2
    dtfC5QKBgBo7Na0nkjyiHwWE5ZVwPZbkb6RB8cv9oxIF/tW/QeCVHsNw610MKCKB
    XdcqxQizT6v3E5DMcoae2VbqGvojtC1jezSfmvg7CeeesPae9bMcXN+tDZ6b+InD
    Ia7hi7y7SZn67St7IU5ZkHtO93hS99Pj/wamwz4a8guYVGhFNkRh
    -----END RSA PRIVATE KEY-----
  max_upload_size: 10485760
Datastore:
  implementation: FileBaseDataStore
  location: /tmp
  filestore_directory: /tmp
Flows: {}
Writeback: {}
Mail: {}
Logging:
  output_directory: /tmp
  separate_logs_per_component: true
Monitoring:
  bind_address: 127.0.0.1
  bind_port: 8003
api_config: {}
