import _ from 'lodash';
import hex2a from "./utils";
import React from 'react';
import Alert from 'react-bootstrap/Alert';
import humanizeDuration from "humanize-duration";
import api from '../core/api-service.jsx';

import automated from "./vi.json";

const Vietnamese = {
    "SEARCH_CLIENTS": "Tìm máy trạm",
    "Mô tả cách ly": (
        <>
          <p>Bạn đang chuẩn bị cách ly host này.</p>
          <p>
            Trong thời gian cách ly, host không thể kết nối với bất kỳ mạng khác, ngoại trừ Velociraptor server.
          </p>
        </>),
    "Cannot Quarantine host": "Không thể cách ly host.",
    "Cannot Quarantine host message": (os_name, quarantine_artifact)=>
        <>
          <Alert variant="warning">
            { quarantine_artifact ?
              <p>Phiên bản Velociraptor này không có artifact <b>{quarantine_artifact}</b> cần thiết để cách ly hosts đang chạy {os_name}</p> :
              <p>Phiên bản Velociraptor này không có artifact xác định để cách ly hosts đang chạy {os_name}.</p>
            }
          </Alert>
        </>,
    "time_ago": function(value, unit) {
        unit = Vietnamese[unit] || unit;
        return value + ' ' + unit + ' trước';
    },
    "Edit Artifact": name=>{
        return "Sửa Artifact " + name;
    },
    "Notebook for Collection": name=>"Ghi chú cho Collection "+name,
    "ArtifactDeletionDialog": (session_id, artifacts, total_bytes, total_rows)=>
    <>
      Chuẩn bị xoá vĩnh viễn artifact collection <b>{session_id}</b>.
      <br/>
      Collection này có các artifacts <b className="wrapped-text">
         {artifacts}
      </b>
      <br/><br/>

      Ước lượng sẽ giải phóng { total_bytes.toFixed(0) } MB dung lượng và { total_rows } hàng.
    </>,
    "ArtifactFavorites": artifacts=>
    <>
      Bạn có thể dễ dàng thu thập collection từ mục yêu thích của bạn trong tương lại.
      <br/>
      Collection này có artifacts <b>{artifacts}</b>
      <br/><br/>
    </>,
    "DeleteHuntDialog": <>
                    <p>Bạn chuẩn bị dừng vĩnh viễn và xoá tất cả dữ liệu về lần hunt này.</p>
                    <p>Bạn có chắc chắn muốn hủy lần hunt này và xóa dữ liệu đã thu thập không?</p>
                        </>,

    "Notebook for Hunt": hunt_id=>"Ghi chú cho làn hunt " + hunt_id,
    "RecursiveVFSMessage": path=><>
    Bạn chuẩn bị tìm kiếm tất cả tập tin có trong <b>{path}</b>.
    <br/><br/>
    Điều này có thể tạo ra một lượng lớn dữ liệu được chuyển đi từ endpoint. Giới hạn upload mặc định là 1gb nhưng bạn có thể điều chỉnh nó ở màn hình Collected Artifacts
    </>,

    "ToolLocalDesc":
    <>
   Công cụ sẽ được cung cấp từ máy chủ Velociraptor cho máy trạm nếu cần. Máy trạm sẽ lưu công cụ vào bộ nhớ cache trên ổ cứng và so sánh hàm băm vào lần chạy tiếp theo. Các công cụ sẽ chỉ được tải xuống nếu hàm băm của chúng đã thay đổi.
    </>,
    "ServedFromURL": (url)=>
    <>
    Máy trạm sẽ tải trực tiếp công cụ
    từ <a href={api.href(url)}>{url}</a> nếu cần thiết. Lưu ý rằng nếu hàm băm không khớp với hàm băm dự kiến, máy trạm sẽ từ chối tệp.
    </>,
    "ServedFromGithub": (github_project, github_asset_regex)=>
    <>
    Công cụ sẽ được tải xuống từ GitHub dưới dạng release mới nhất
    từ <b>{github_project}</b>, phù hợp với <b>{github_asset_regex}</b>
    </>,
    "PlaceHolder":
    <>
    Hash của công cụ chưa được tính. Lần đầu khởi chạy công cụ, Velociraptor sẽ tải xuống từ URL và tính hash của nó.
    </>,
    "ToolHash":
    <>
    Hash của công cụ đã được tính. Khi máy trạm cần sử dụng công cụ này, nó sẽ kiếm tra hash khớp với những gì nó tải xuống.
    </>,
    "AdminOverride":
    <>
    Công cụ được quản trị viên tải lên thủ công - nó sẽ không được nâng cấp tự động trong lần cập nhật máy chủ Velociraptor tiếp theo.
    </>,
    "ToolError":
    <>
    Hàm băm của công cụ không được xác định và không có URL nào được xác định. Sẽ không thể sử dụng công cụ này vì Velociraptor không thể xử lý yêu cầu. Bạn có thể tải tệp lên theo cách thủ công.
    </>,
    "OverrideToolDesc":
    <>
    Là quản trị viên, bạn có thể tải lên tệp binary theo cách thủ công để sử dụng công cụ đó. Thao tác này sẽ ghi đè cài đặt URL và cung cấp công cụ của bạn cho tất cả các artifacts cần nó. Ngoài ra, hãy đặt URL để máy trạm tải xuống công cụ từ đó.
    </>,

    "X per second": x=><>{x} mỗi giây</>,
    "HumanizeDuration": difference=>{
        if (difference<0) {
            return <>
                     In {humanizeDuration(difference, {
                         round: true,
                         language: "vi",
                     })}
                   </>;
        }
        return <>
                 {humanizeDuration(difference, {
                     round: true,
                     language: "vi",
                 })} trước
               </>;
    },
    "EventMonitoringCard":
    <>
    Giám sát sự kiện nhắm tới nhóm nhãn cụ thể. Chọn một nhóm nhãn ở trên để cấu hình các sự kiện, artifacts nhắm tới nhóm đó.
    </>,
    // Below need verification
    "Role_administrator": "Quản trị viên của Server",
     "Role_org_admin": "Quản trị viên của Tổ chức",
     "Role_reader": "Người dùng chỉ đọc",
     "Role_analyst": "Nhà phân tích",
     "Role_investigator": "Điều tra viên",
     "Role_artifact_writer": "Artifact Writer",
     "Role_api": "API Client",

     "Perm_ANY_QUERY": "Any Query",
     "Perm_PUBISH": "Publish",
     "Perm_READ_RESULTS" : "Đọc kết quả",
     "Perm_LABEL_CLIENT": "Dán nhãn cho máy trạm",
     "Perm_COLLECT_CLIENT": "Thu thập từ máy trạm",
     "Perm_START_HUNT": "Bắt đầu hunt",
     "Perm_COLLECT_SERVER": "Collect Server",
     "Perm_ARTIFACT_WRITER": "Artifact Writer",
     "Perm_SERVER_ARTIFACT_WRITER": "Server Artifact Writer",
     "Perm_EXECVE": "EXECVE",
     "Perm_NOTEBOOK_EDITOR": "Sửa ghi chú",
     "Perm_SERVER_ADMIN": "Quản trị viên của Server",
     "Perm_ORG_ADMIN": "Quản trị viên của Tổ chức",
     "Perm_IMPERSONATION": "Impersonation",
     "Perm_FILESYSTEM_READ": "Đọc tập tin hệ thống",
     "Perm_FILESYSTEM_WRITE": "Ghi tập tin hệ thống",
     "Perm_MACHINE_STATE": "Trạng thái thiết bị",
     "Perm_PREPARE_RESULTS": "Chuẩn bị kết quả",
     "Perm_DATASTORE_ACCESS": "Truy cập Datastore",

     "ToolPerm_ANY_QUERY": "Thực hiện query bất kỳ trên tất cả",
     "ToolPerm_PUBISH": "Xuất sự kiện lên hàng đợi của máy chủ (thường không cần thiết)",
     "ToolPerm_READ_RESULTS": "Đọc kết quả từ các lần hunt đã chạy, flows hoặc ghi chú",
     "ToolPerm_LABEL_CLIENT": "Có thể thao tác với nhãn và metadata",
     "ToolPerm_COLLECT_CLIENT": "Lên lịch hoặc hủy các collection mới trên máy trạm",
     "ToolPerm_START_HUNT": "Bắt đầu một lần hunt mới",
     "ToolPerm_COLLECT_SERVER": "Lên lịch một artifact collections trên Velociraptor servers",
     "ToolPerm_ARTIFACT_WRITER": "Thêm hoặc chỉnh sửa các artifacts tùy chỉnh chạy trên máy chủ",
     "ToolPerm_SERVER_ARTIFACT_WRITER": "Thêm hoặc chỉnh sửa các artifacts tùy chỉnh chạy trên máy chủ",
     "ToolPerm_EXECVE": "Được phép thực thi các lệnh tùy ý trên máy trạm",
     "ToolPerm_NOTEBOOK_EDITOR": "Được phép thay đổi ghi chú và cell",
     "ToolPerm_SERVER_ADMIN": "Được phép quản lý máy chủ",
     "ToolPerm_ORG_ADMIN" : "Được phép quản lý tổ chức",
     "ToolPerm_IMPERSONATION": "Cho phép người dùng chỉ định tên người dùng khác cho plugin query()",
     "ToolPerm_FILESYSTEM_READ": "Được phép đọc các tệp tùy ý từ hệ thống tệp",
     "ToolPerm_FILESYSTEM_WRITE": "Được phép tạo tệp trên hệ thống tệp",
     "ToolPerm_MACHINE_STATE": "Được phép thu thập thông tin trạng thái từ các máy (ví dụ: pslist())",
     "ToolPerm_PREPARE_RESULTS": "Được phép tạo tệp zip",
     "ToolPerm_DATASTORE_ACCESS": "Được phép truy cập dữ liệu raw",

    "FINISHED": "HOÀN THÀNH",
    "RUNNING": "ĐANG CHẠY",
    "STOPPED": "NGỪNG",
    "PAUSED": "TẠM DỪNG",
    "ERROR": "LỖI",
    "INFO": "THÔNG TIN",
    "DEBUG": "GỠ LỖI",
    "CANCELLED": "HỦY BỎ",

     // From vi.json
     "New Key": " Khóa mới",
     "Running...": " Đang chạy...",
     "1 Day actives": "Hoạt động trong ngày",
     "1 Month actives": "Hoạt động trong tháng",
     "1 Week actives": "Hoạt động trong tuần",
     "? for suggestions": "? để được gợi ý",
     "A new label": "Một nhãn mới",
     "ALL": "TẤT CẢ",
     "AWS Bucket": "AWS Bucket",
     "Add Cell": "Thêm cell",
     "Add Cell From Flow": "Thêm cell từ flow",
     "Add Cell From Hunt": "Thêm cell từ hunt",
     "Add Cell From This Cell": "Thêm cell từ cell này",
     "Add Label": "Thêm nhãn",
     "Add Timeline": "Thêm Dòng thời gian",
     "Add a new  User": "Thêm người dùng mới",
     "Add a new user": "Thêm người dùng mới",
     "Add an Artifact": "Thêm một Artifact",
     "Add cell from Flow": "Thêm cell từ flow",
     "Add cell from Hunt": "Thêm cell từ hunt",
     "Add it!": "Thêm vào!",
     "Add to hunt": "Thêm để hunt",
     "Admin Override": "Ghi đè quản trị viên",
     "Agent Build Time": "Thời gian xây dựng agent",
     "Agent Version": "Phiên bản agent",
     "All Artifacts": "Tất cả Artifacts",
     "All Known Clients": "Tất cả máy trạm đã biết",
     "All Orgs": "Tất cả tổ chức",
     "All known Clients": "Tất cả máy trạm đã biết",
     "Append prefix to all artifact names": "Thêm tiền tố vào tất cả các tên artifact",
     "Architecture": "Architecture",
     "Are you sure you want to delete all logs within the time range?": "Bạn có chắc chắn muốn xóa tất cả logs trong khoảng thời gian đó không?",
     "Are you sure you want to run this hunt?": "Bạn có muốn chạy lần hunt này không?",
     "Artifact": "Artifact",
     "Artifact Collected": "Artifact được thu thập",
     "Artifact Collection": "Artifact Collection",
     "Artifact Definition": "Định nghĩa Artifact",
     "Artifact Name": "Tên Artifact",
     "Artifact Names": "Tên Artifact",
     "Artifact Selection Step": "Bước lựa chọn artifact",
     "Artifact details": "Chi tiết artifact",
     "Artifacts": "Artifact",
     "Artifacts with Results": "Artifact có kết quả",
     "Assign user to Orgs": "Chỉ định người dùng cho Tổ chức",
     "Atime": "Atime",
     "Available Downloads": "Bản tải xuống khả dụng",
     "Azure SAS URL": "Azure SAS URL",
     "Btime": "Btime",
     "Bucket name": "Tên bucket",
     "Build offline collector": "Build offline collector",
     "BuiltIn Only": "Chỉ tích hợp sẵn",
     "CPU Limit": "Giới hạn CPU",
     "CPU Limit Percent": "Giới hạn CPU theo phần trăm",
     "CSV and JSON": "CSV và JSON",
     "Cancel": "Hủy",
     "Cancel Artifact Collection": "Hủy bộ Artifact Collection",
     "Checking": "Đang kiểm tra",
     "Child timeline name": "Tên dòng thời gian con",
     "Clear": "Xóa",
     "Clear All": "Xóa tất cả",
     "Click on a file in the table above.": "Nhấp vào tệp trong bảng trên.",
     "Click to accept": "Nhấp để chấp nhận",
     "Click to upload artifact pack file": "Nhấp để tải lên tệp đóng gói artifact",
     "Click to upload file": "Nhấp để tải tệp lên",
     "Client Artifacts": "Client Artifacts",
     "Client Events": "Client Events",
     "Client ID": "ID máy trạm",
     "Client Metadata": "Client Metadata",
     "Client Monitoring": "Giám sát máy trạm",
     "Clients": "Máy trạm",
     "Clipboard": "Khay nhớ tạm",
     "Close": "Đóng",
     "Close All": "Đóng tất cả",
     "Collaborators": "Cộng tác viên",
     "Collapse": "Thu gọn",
     "Collect Artifact": "Collect Artifact",
     "Collected": "Đã thu thập",
     "Collected Artifacts": "Collected Artifacts",
     "Collected artifacts": "Collected Artifacts",
     "Collection Type": "Loại Collection",
     "Collection resource specification": "Collection resource specification",
     "Compressed": "Đã nén",
     "Compression Level": "Mức nén",
     "Configure": "Cấu hình",
     "Configure Editor": "Cấu hình trình soạn thảo",
     "Configuring Label": "Cấu hình nhãn",
     "Confirm tool definition reset": "Xác nhận đặt lại định nghĩa công cụ",
     "Connected": "Đã kết nối",
     "Container Files": "Container Files",
     "Cool Gray (dark)": "Cool Gray (dark)",
     "Copy Collection": "Sao chép Collection",
     "Copy Hunt": "Sao chép ",
     "Create Artifact from VQL": "Tạo Artifact từ VQL",
     "Create Offline collector:  Configure Collector": "Tạo Offline collector: Cấu hình Collector",
     "Create Time": "Tạo thời gian",
     "Create a new Notebook": "Tạo ghi chú mới",
     "Create a new artifact": "Tạo một artifact mới",
     "Created": "Đã tạo",
     "Creation Time": "Thời gian tạo",
     "Creator": "Người tạo",
     "Credentials Key": "Credentials Key",
     "Credentials Secret": "Credentials Secret",
     "Ctime": "Ctime",
     "Currently fetching files from the client": "Hiện đang tìm nạp tệp từ máy trạm",
     "Currently refreshing": "Đang làm mới",
     "Currently refreshing from the client": "Hiện đang làm mới từ máy trạm",
     "Custom": "Tùy chỉnh",
     "Custom Only": "Chỉ tùy chỉnh",
     "Data": "Dữ liệu",
     "Date": "Ngày",
     "Debug": "Gỡ lỗi",
     "Default password to use for downloads": "Mật khẩu mặc định sử dụng để tải xuống",
     "Delete": "Xóa",
     "Delete Artifact": "Xóa Artifact",
     "Delete Artifact Collection": "Xóa Artifact Collection",
     "Delete Cell": "Xóa cell",
     "Delete Clients": "Xóa máy trạm",
     "Delete Events": "Xóa sự kiện",
     "Delete Hunt": "Xóa hunt",
     "Delete Notebook": "Xóa ghi chú",
     "Delete Time Range": "Xóa khoảng thời gian",
     "Delete an artifact": "Xóa một artifact",
     "DeleteMessage": "Xóa tin nhắn",
     "Describe this favorite": "Mô tả mục yêu thích này",
     "Description": "Mô tả",
     "Details": "Chi tiết",
     "Deutsch": "Tiếng Đức",
     "Directory is empty.": "Thư mục trống.",
     "Disable tracing": "Tắt theo dõi",
     "Display timezone": "Hiển thị múi giờ",
     "Do it!": "Làm đi!",
     "Down Cell": "Xuống cell",
     "Download": "Tải xuống",
     "Download CSV": "Tải xuống CSV",
     "Download Error": "Lỗi tải xuống",
     "Download JSON": "Tải xuống JSON",
     "Download Results": "Tải xuống kết quả",
     "Download from client": "Tải xuống từ máy trạm",
     "Downloads Password": "Mật khẩu tải xuống",
     "Duration": "Thời lượng",
     "Duration (Sec)": "Thời lượng (giây)",
     "Edit Cell": "Chỉnh sửa cell",
     "Edit Notebook": "Chỉnh sửa ghi chú",
     "Edit an Artifact": "Chỉnh sửa Artifact",
     "Edit notebook ": "Chỉnh sửa ghi chú",
     "Edit the dashboard": "Chỉnh sửa trang tổng quan",
     "Editor shortcuts": "Phím tắt của trình chỉnh sửa",
     "Effective Permissions": "Quyền hiệu lực",
     "Encryption Scheme": "Encryption Scheme",
     "Endpoint": "Endpoint",
     "Endpoint (blank for AWS)": "Endpoint (để trống cho AWS)",
     "Endpoint Filename": "Tên Endpoint",
     "English": "Tiếng Anh",
     "Enter a username": "Nhập tên người dùng",
     "Error": "Lỗi",
     "Estimated affected clients": "Ước tính các Máy trạm bị ảnh hưởng",
     "Event Monitoring Label Groups": "Nhóm nhãn giám sát sự kiện",
     "Event Monitoring: Configure Label groups": "Giám sát sự kiện: Cấu hình nhóm nhãn",
     "Event Monitoring: Configure artifact parameters for label group ": "Giám sát sự kiện: Cấu hình tham số artifact cho nhóm nhãn ",
     "Event Monitoring: Review new event tables": "Giám sát sự kiện: Xem lại các bảng sự kiện mới",
     "Event Monitoring: Select artifacts to collect from label group ": "Giám sát sự kiện: Chọn artifacts để thu thập từ nhóm nhãn ",
     "Every 10 Seconds": "Mỗi 10 giây",
     "Every 30 Seconds": "Mỗi 30 giây",
     "Every 60 Seconds": "Mỗi 60 giây",
     "Exchange": "Trao đổi",
     "Exclude Condition": "Điều kiện loại trừ",
     "Exclude Labels": "Loại trừ nhãn",
     "Excluded Labels": "Nhãn bị loại trừ",
     "Existing": "Hiện tại",
     "Exit Fullscreen": "Thoát toàn màn hình",
     "Expand": "Mở rộng",
     "Expected Hash": "Hash dự kiến",
     "Expires": "Hết hạn",
     "Expiry": "Hết hạn",
     "Expiry Time": "Thời gian hết hạn",
     "Export Notebook": "Xuất ghi chú",
     "Export notebooks": "Xuất ghi chú",
     "Export to HTML": "Xuất sang HTML",
     "Export to Zip": "Xuất sang Zip",
     "Extra Permissions": "Quyền bổ sung",
     "FQDN": "FQDN",
     "Favorite Name": "Tên ưa thích",
     "Fetch from Client": "Tìm nạp từ Máy trạm",
     "Files uploaded": "Tệp đã tải lên",
     "Filter": "Bộ lọc",
     "Filter artifact": "Lọc artifact",
     "Filter name of artifacts to load": "Lọc tên của artifacts cần tải",
     "Finished clients": "Máy trạm đã hoàn thành",
     "First Seen At": "Xuất hiện lần đầu tại",
     "Flow Details": "Chi tiết flow",
     "Flow ID": "ID flow",
     "FlowId": "ID flow",
     "Focus client search box": "Focus client search box",
     "French": "Tiếng Pháp",
     "Full Download": "Tải xuống đầy đủ",
     "Full Screen": "Toàn màn hình",
     "GCS Blob": "GCS Blob",
     "GCS Bucket": "GCS Bucket",
     "GCS Key Blob": "GCS Key Blob",
     "Github Asset Regex": "Github Asset Regex",
     "Github Project": "Github Project",
     "Github dimmed (dark)": "Github dimmed (dark)",
     "Global hotkeys": "Phím tắt chung",
     "Go to next step": "Chuyển sang bước tiếp theo",
     "Go to previous step": "Quay lại bước trước",
     "Google Cloud Bucket": "Google Cloud Bucket",
     "Goto Offset": "Đi tới Offset",
     "Goto Page": "Đi tới trang",
     "Goto dashboard": "Đi tới trang tổng quan",
     "Goto notebooks": "Truy cập ghi chú",
     "Hash": "Hash",
     "Hex Offset": "Hex Offset",
     "Hide Output": "Ẩn output",
     "Home": "Trang chủ",
     "Host Information": "Thông tin host",
     "Host Key": "Host Key",
     "Hostname": "Hostname",
     "Hunt Artifact": "Hunt Artifact",
     "Hunt ID": "Hunt ID",
     "Hunt Manager": "Người quản lý hunt",
     "Hunt State": "Trạng thái hunt",
     "Hunt description": "Mô tả hunt",
     "HuntId": "HuntID",
     "IOPS Limit": "Giới hạn IOPS",
     "IOps/Sec": "IOps/Giây",
     "If set collection will be terminated after this many seconds with no progress.": "Nếu đặt, collection sẽ bị chấm dứt sau khoảng thời gian mà không có tiến triển.",
     "Include Condition": "Bao gồm điều kiện",
     "Include Labels": "Bao gồm nhãn",
     "Include OS": "Bao gồm hệ điều hành",
     "Info": "Thông tin",
     "Inspect Raw JSON": "Kiểm tra Raw JSON",
     "Interrogate": "Interrogate",
     "Japanese": "Tiếng Nhật",
     "Key": "Key",
     "Keyboard shortcuts": "Phím tắt",
     "Kill it!": "Kill it!",
     "Label": "Nhãn",
     "Label Clients": "Nhãn Máy trạm",
     "Labels": "Nhãn",
     "Language": "Ngôn ngữ",
     "Last Active": "Hoạt động lần cuối",
     "Last Collected": "Được thu thập lần cuối",
     "Last Seen At": "Được nhìn thấy lần cuối lúc",
     "Last Seen IP": "IP nhìn thấy lần cuối",
     "Launch artifact": "Chạy artifact",
     "Leave Blank to disable host key checking": "Để trống để tắt kiểm tra khóa máy chủ",
     "Linux Only": "Chỉ Linux",
     "Load Output": "Tải đầu ra",
     "Loading ACLs": "Đang tải ACL",
     "Log": "Nhật ký",
     "Logs": "Nhật ký",
     "Main Menu": "Menu chính",
     "Manually add collection to hunt": "Thêm collection để hunt theo cách thủ công",
     "Match by label": "Khớp theo nhãn",
     "Materialize Hash": "Materialize Hash",
     "Max Execution Time in Seconds": "Thời gian thực hiện tối đa tính bằng giây",
     "Max Idle Time in Seconds": "Thời gian rỗi tối đa tính bằng giây",
     "Max Mb": "Mb tối đa",
     "Max bytes Uploaded": "Mb tối đa đã tải lên",
     "Max Rows": "Số hàng tối đa",
     "Mb": "Mb",
     "Midnight Inferno (very dark)": "Midnight Inferno (very dark)",
     "Mode": "Chế độ",
     "Modified Time": "Thời gian sửa đổi",
     "Mtime": "Mtime",
     "Name": "Tên",
     "Ncurses (light)": "Ncurses (light)",
     "New Artifact Collection Wizard": "Trình hướng dẫn thu thập Artifact mới",
     "New Collection": "Collection mới",
     "New Collection: Launch collection": "Collection mới: Chạy Collection",
     "New Favorite name": "Tên ưa thích mới",
     "New Hunt": "Hunt mới",
     "New Hunt - Configure Hunt": "Hunt mới - Cấu hình hunt",
     "New Notebook": "Ghi chú mới",
     "New Value": "Giá trị mới",
     "No Data Available.": "Không có dữ liệu.",
     "No artifacts configured. Please add some artifacts to collect": "Không có cấu hình artifacts nào. Vui lòng thêm một số artifacts để thu thập",
     "No compatible hunts.": "Không có hunt tương thích.",
     "No data available. Refresh directory from client by clicking above.": "Không có dữ liệu. Làm mới thư mục từ máy trạm bằng cách nhấp vào bên trên.",
     "No events": "Không có sự kiện",
     "No hunts exist in the system. You can start a new hunt by clicking the New Hunt button above.": "Không có hunt nào tồn tại trong hệ thống. Bạn có thể bắt đầu hunt mới bằng cách nhấp vào nút hunt mới ở trên.",
     "None": "Không có",
     "Notebook": "ghi chú",
     "Notebook Uploads": "Tải lên ghi chú",
     "Notebook uploads": "Tải lên ghi chú",
     "NotebookId": "ID ghi chú",
     "Notebooks": "ghi chú",
     "OS Version": "Phiên bản hệ điều hành",
     "OSX Only": "Chỉ OSX",
     "Offset": "Offset",
     "Online": "Trực tuyến",
     "Open All": "Mở tất cả",
     "Operating System": "Hệ điều hành",
     "Operating System Included": "Bao gồm hệ điều hành",
     "Ops/Sec": "Ops/Sec",
     "Organization": "Tổ chức",
     "Orgs": "Tổ chức",
     "Other Definitions": "Các định nghĩa khác",
     "Output Prefix": "Prefix đầu ra",
     "Output filename prefix": "prefix tên tệp output",
     "Output format": "Định dạng đầu ra",
     "Override Tool": "Công cụ ghi đè",
     "Overview": "Tổng quan",
     "PGP Encryption": "Mã hóa PGP",
     "Parameters configuration Step": "Bước cấu hình tham số",
     "Password": "Mật khẩu",
     "Passwords do not match": "Mật khẩu không khớp",
     "Permanently delete Notebook": "Xóa vĩnh viễn ghi chú",
     "Permanently delete collection": "Xóa vĩnh viễn collection",
     "Permanently delete this hunt?": "Xóa vĩnh viễn hunt này?",
     "Placeholder Definition": "Định nghĩa placeholder",
     "Please Select a User": "Vui lòng chọn người dùng",
     "Please Select an Org": "Vui lòng chọn một tổ chức",
     "Please click a collection in the above table": "Vui lòng nhấp vào một collection trong bảng trên",
     "Please create a hunt that collects one or more of the following artifacts.": "Vui lòng tạo một hunt để thu thập một hoặc nhiều artifacts sau.",
     "Please select a hunt above": "Vui lòng chọn một hunt ở trên",
     "Please select a hunt to view above.": "Vui lòng chọn một hunt để xem ở trên.",
     "Popup the editor configuration dialog": "Mở trình chỉnh sửa cấu hình",
     "Portuguese": "Tiếng Bồ Đào Nha",
     "Prefix": "Tiền tố",
     "Prepare CSV And JSON Download": "Chuẩn bị tải xuống CSV và JSON",
     "Prepare CSV Download": "Chuẩn bị tải xuống CSV",
     "Prepare Download": "Chuẩn bị tải xuống",
     "Preview": "Xem trước",
     "Private Key": "Private Key",
     "Properties": "Thuộc tính",
     "Public": "Công khai",
     "Public Key/Cert": "Public Key/Cert",
     "Quarantine Host": "Cách ly host",
     "Quarantine Message": "Thông báo cách ly",
     "Quarantine host": "Cách ly host",
     "Raw Response JSON": "Raw Response JSON",
     "Re-Download File": "Tải xuống lại tệp",
     "Recalculate": "Tính toán lại",
     "Recent Hosts": "Hosts gần đây",
     "Recursively download files": "Tải xuống tất cả tệp",
     "Recursively download this directory from the client": "Tải xuống tất cả tệp tin trong thư mục này từ máy trạm",
     "Recursively refresh this directory (sync its listing with the client)": "Làm mới tất cả nội dung thư mục này (đồng bộ hóa danh sách với máy trạm)",
     "Redraw dashboard": "Vẽ lại trang tổng quan",
     "Reformat Format VQL": "Định dạng lại Format VQL",
     "Refresh Github": "Làm mới Github",
     "Refresh this directory (sync its listing with the client)": "Làm mới thư mục này (đồng bộ hóa danh sách với máy trạm)",
     "Regex": "Regex",
     "Region": "Khu vực",
     "Release": "Phát hành",
     "Remove": "Xóa",
     "Rendered": "Đã hiển thị",
     "Request sent to client": "Đã gửi yêu cầu tới máy trạm",
     "Requests": "Yêu cầu",
     "Results": "Kết quả",
     "Retype Password": "Nhập lại mật khẩu",
     "Roles": "Vai trò",
     "Rows": "Hàng",
     "Run Hunt": "Chạy hunt",
     "Run VQL on client": "Chạy VQL trên máy trạm",
     "Run command on client": "Chạy lệnh trên máy trạm",
     "Run everywhere": "Chạy mọi nơi",
     "Run it!": "Chạy đi!",
     "Run this hunt?": "Chạy hunt này?",
     "Running": "Đang chạy",
     "S3 Bucket": "S3 Bucket",
     "SAS URL as generated from the Azure console": "URL SAS được tạo từ Azure console",
     "SFTP Upload": "Tải lên SFTP",
     "SHA256 Hash": "SHA256 Hash",
     "SMB Share": "Chia sẻ SMB",
     "SMB Share address (e.g. \\\\192.168.1.1:445\\Sharename)": "Địa chỉ chia sẻ SMB (ví dụ: \\\\192.168.1.1:445\\Sharename)",
     "SMB Share login password": "Mật khẩu đăng nhập SMB Share",
     "SMB Share login username": "Tên đăng nhập SMB Share",
     "Save": "Lưu",
     "Save Collection": "Lưu collection",
     "Save editor contents": "Lưu nội dung",
     "Save this collection to your Favorites": "Lưu collection này vào Mục ưa thích của bạn",
     "Scheduled": "Đã lên lịch",
     "Search": "Tìm kiếm",
     "Search for an artifact to view it": "Tìm kiếm một artifact để xem nó",
     "Search for artifact": "Tìm kiếm artifact",
     "Search for artifacts...": "Tìm kiếm artifact...",
     "Search for string or hex": "Tìm kiếm chuỗi hoặc hex",
     "Select a download method": "Chọn phương thức tải xuống",
     "Select a label": "Chọn nhãn",
     "Select a language": "Chọn ngôn ngữ",
     "Select a notebook from the list above.": "Chọn ghi chú từ danh sách trên.",
     "Select a theme": "Chọn chủ đề",
     "Select a timezone": "Chọn múi giờ",
     "Select a user": "Chọn người dùng",
     "Select an org": "Chọn tổ chức",
     "Select artifact": "Chọn artifact",
     "Select artifact pack (Zip file with YAML definitions)": "Chọn artifact pack (tệp Zip với YAML definitions)",
     "Select file": "Chọn tệp",
     "Select label to edit its event monitoring table": "Chọn nhãn để chỉnh sửa bảng giám sát sự kiện của nó",
     "Select next collection": "Chọn collection tiếp theo",
     "Select other definition to reset inventory": "Chọn định nghĩa khác để reset inventory",
     "Select previous collection": "Chọn collection trước",
     "Serve Locally": "Tải về từ nội bộ",
     "Serve URL": "URL tải về",
     "Serve from upstream": "Tải về từ URL chính chủ",
     "Served Locally": "Tải về từ nội bộ",
     "Served from GitHub": "Tải về từ GitHub",
     "Served from URL": "Tải về từ URL",
     "Server Address": "Địa chỉ máy chủ",
     "Server Artifacts": "Artifacts máy chủ",
     "Server Event Monitoring: Configure artifact parameters for server": "Giám sát sự kiện máy chủ: Cấu hình tham số artifact cho máy chủ",
     "Server Event Monitoring: Review new event tables": "Giám sát sự kiện máy chủ: Xem lại các bảng sự kiện mới",
     "Server Event Monitoring: Select artifacts to collect on the server": "Giám sát sự kiện máy chủ: Chọn artifact để thu thập trên máy chủ",
     "Server Events": "Sự kiện máy chủ",
     "Server Side Encryption": "Mã hóa phía máy chủ",
     "Server Monitoring": "Giám sát máy chủ",
     "Set All": "Đặt tất cả",
     "Set Serve URL": "Đặt URL tải về",
     "Set a password in user preferences to lock the download file.": "Đặt mật khẩu trong tùy chọn người dùng để khóa tệp tải xuống.",
     "Shell": "Shell",
     "Show All": "Hiển thị tất cả",
     "Show all hunts": "Hiển thị tất cả các hunt",
     "Show client monitoring tables": "Hiển thị bảng giám sát máy trạm",
     "Show only my hunts": "Chỉ hiển thị các lần hunt của tôi",
     "Show server monitoring tables": "Hiển thị bảng giám sát máy chủ",
     "Show/Hide Columns": "Hiện/Ẩn cột",
     "Show/Hide keyboard hotkeys help": "Hiện/ẩn phím tắt",
     "Size": "Kích cỡ",
     "Skip Cert Verification": "Bỏ qua xác minh chứng chỉ",
     "Skip queues and run query urgently": "Bỏ qua hàng đợi và chạy truy vấn ngay lập tức",
     "Spanish": "Tây Ban Nha",
     "Sparse": "Sparse",
     "Sparse files will be expanded in export.": "Sparse files sẽ được mở rộng khi xuất.",
     "Sparse files will remain sparse in export.": "Sparse files sẽ vẫn thưa thớt khi xuất.",
     "Start Hunt Immediately": "Bắt đầu hunt ngay",
     "Start Time": "Thời gian bắt đầu",
     "Started": "Đã bắt đầu",
     "State": "Trạng thái",
     "Stats Toggle": "Mở số liệu thống kê",
     "Stop": "Dừng lại",
     "Stop Calculating": "Dừng tính toán",
     "Stop Hunt": "Dừng hunt",
     "Strawberry Milkshake (light)": "Strawberry Milkshake (light)",
     "Submit": "Gửi",
     "Suggestion": "Đề xuất",
     "Suggestions": "Đề xuất",
     "Summary (CSV Only)": "Tổng quan (Chỉ CSV)",
     "Summary (JSON Only)": "Tổng quan (Chỉ JSON)",
     "Summary Download": "Tải xuống Tổng quan",
     "Super Timeline": "Super Timeline",
     "Super-timeline name": "Tên Super Timeline",
     "Switch to a different org": "Chuyển sang tổ chức khác",
     "Table is Empty": "Bảng trống",
     "Target Operating System": "Hệ điều hành đích",
     "Temp directory": "Thư mục tạm thời",
     "Temp location": "Vị trí tạm thời",
     "Theme": "Chủ đề",
     "This is a notebook for processing a hunt.": "Đây là ghi chú để xử lý một hunt.",
     "This will reset the tool to its original definition": "Thao tác này sẽ đặt lại công cụ",
     "Time": "Thời gian",
     "Time Column": "Cột thời gian",
     "Time column": "Cột thời gian",
     "Timeline Name": "Tên Dòng thời gian",
     "Timeline name": "Tên dòng thời gian",
     "Timeout": "Hết giờ",
     "To enable tracing, specify trace update frequency in seconds ": "Để kích hoạt theo dõi, chỉ định tần suất cập nhật theo dõi tính bằng giây ",
     "Toggle Main Menu": "Mở Menu chính",
     "Tool": "Công cụ",
     "Tool Hash Known": "Hash của công cụ đã biết",
     "Tool Name": "Tên công cụ",
     "Tool Version": "Phiên bản Công cụ",
     "Total Rows": "Tổng số hàng",
     "Total scheduled": "Tổng số đã lên lịch",
     "Trace Frequency Seconds": "Tần số theo dõi (giây)",
     "Transformed": "Đã chuyển đổi",
     "Type": "Loại",
     "Type VQL to run on the client": "Nhập VQL để chạy trên máy trạm",
     "Type a URL": "Nhập URL",
     "Uncompressed": "Không nén",
     "Undo": "Hoàn tác",
     "Unlimited": "Không giới hạn",
     "Unquarantine Host": "Máy chủ không được cách ly",
     "Up Cell": "Lên cell",
     "Update Password": "Cập nhật mật khẩu",
     "Update User Password": "Cập nhật mật khẩu người dùng",
     "Update client monitoring table": "Cập nhật bảng giám sát máy trạm",
     "Update server monitoring table": "Cập nhật bảng giám sát máy chủ",
     "Update server monitoring tables": "Cập nhật bảng giám sát máy chủ",
     "Upload": "Tải lên",
     "Upload Artifact Pack": "Tải lên Artifact Pack",
     "Upload Path": "Đường dẫn tải lên",
     "Upload artifacts from a Zip pack": "Tải lên artifacts từ Zip",
     "Uploaded Bytes": "Số byte đã tải lên",
     "Uploaded Files": "Tệp đã tải lên",
     "Upstream Hash": "Hash chính chủ",
     "Upstream URL": "URL chính chủ",
     "Urgent": "Khẩn cấp",
     "User": "Người dùng",
     "User Settings": "Cài đặt người dùng",
     "Username": "Tên người dùng",
     "Users": "Người dùng",
     "Using Tools": "Sử dụng Công cụ",
     "VFS": "VFS",
     "VQL Drilldown": "VQL Drilldown",
     "Value": "Giá trị",
     "Velociraptor (dark)": "Velociraptor (dark)",
     "Velociraptor (light)": "Velociraptor (light)",
     "Velociraptor Binary": "Velociraptor Binary",
     "Velociraptor Classic (light)": "Velociraptor Classic (light)",
     "View Artifacts": "Xem Artifacts",
     "View Collection": "Xem collection",
     "View selected collection logs": "Xem nhật ký collection đã chọn",
     "View selected collection overview": "Xem tổng quan về collection đã chọn",
     "View selected collection results": "Xem kết quả của collection đã chọn",
     "View selected collection uploaded files": "Xem các tệp đã tải lên collection đã chọn",
     "Virtual Filesystem": "Virtual Filesystem",
     "Warn": "Cảnh báo",
     "Warning": "Cảnh báo",
     "Welcome": "Xin chào",
     "Width": "Chiều rộng",
     "Windows Only": "Chỉ Windows",
     "X509 Certificate/Frontend Cert": "X509 Certificate/Frontend Cert",
     "Yeah do it!": "Thực hiện!",
     "Yes do it!": "Thực hiện!",
     "You are about to permanently delete the notebook for this hunt": "Bạn sắp xóa vĩnh viễn ghi chú cho lần hunt này",
     "Zip Archive": "Lưu trữ Zip",
     "date": "ngày",
     "rows": "hàng",
     "seconds": "giây",
     "size": "kích thước",
     "Vietnamese": "Tiếng Việt",
     " New Key": " Khóa mới",
     " Running...": " Đang chạy...",
     "Quarantine description": "Mô tả cách ly"
};

_.each(automated, (v, k)=>{
    Vietnamese[hex2a(k)] = v;
});

export default Vietnamese;
