name: Notebooks.Default
description: |
  A default notebook.

type: NOTEBOOK

sources:
  - notebook:
    - type: markdown
      template: |
        # Welcome to Velociraptor notebooks!

        * Update this notebook with any VQL or markdown cells.
        * You can copy cells into this notebook from other collection or hunt notebooks.

    - type: vql_suggestion
      name: A Cell Suggestion
      template: |
        /*
        # This is a cell suggestion
        */
        SELECT * FROM info()
